[[ael]]
= AEL
__Asterisk Extension Language__

In diesem Kapitel:

* xref:ael-cli.adoc[CLI-Befehle für AEL]
* xref:aelparse.adoc[aelparse]
* xref:extensions.ael.adoc[extensions.conf <-> extensions.ael]
** xref:extensions.ael.adoc#ael-command-termination[Zeilenende/Befehlsende]
** xref:extensions.ael.adoc#ael-contexts-extensions-priorities[Kontexte, Extensions, Prioritäten]
** xref:extensions.ael.adoc#ael-comments[Kommentare]
** xref:extensions.ael.adoc#ael-include-contexts[Includes – Andere Contexte einbinden]
** xref:extensions.ael.adoc#ael-global-variables[Globale Variablen]
** xref:extensions.ael.adoc#ael-expressions-assignments[Ausdrücke und Zuweisungen]
** xref:extensions.ael.adoc#ael-labels-goto-jump[Labels, goto und jump]
** xref:extensions.ael.adoc#ael-conditionals[Bedingte Anweisungen (_conditionals_)]
** xref:extensions.ael.adoc#ael-loops[Schleifen (_loops_)]
** xref:extensions.ael.adoc#ael-macros[Makros (_macros_)]
** xref:extensions.ael.adoc#ael-hints[Hints]
** xref:extensions.ael.adoc#ael-match-caller-id[Filtern nach Anrufernummer]
* xref:extensions.ael-oder-conf.adoc[extensions.ael oder extensions.conf?]

Seit Asterisk 1.4 haben Sie die Möglichkeit, den aus xref:dialplan-grundlagen.adoc[Kapitel 3, _Dialplan – die Grundlagen_] und xref:kapitel-programmieren.adoc[Kapitel 6, _Programmieren im Dialplan_] bekannten „Dialplan“ nicht
nur im Format `extensions.conf` zu schreiben, sondern Sie
können sich alternativ auch für AEL, die „Asterisk Extension
Language“, entscheiden. Die Datei dafür heißt
`extensions.ael`.

AEL ist vor allem für diejenigen interessant, die sich immer schon
geärgert haben, dass eine größere `extensions.conf`
schwer zu lesen ist. AEL ähnelt mehr einer „richtigen“
Skript-Programmiersprache. Übrigens schließen sich
`extensions.conf` und `extensions.ael`
nicht gegenseitig aus, man kann auch beide benutzen, also Kontexte in der
einen oder in der anderen Datei definieren. Wenn beide Dateien vorhanden
sind, überschreibt die `extensions.conf` Teile, die in
der `extensions.ael` parallel vorhanden sind.

Hier ein kleiner Vorgeschmack:

[cols="2*"]
|===
| `extensions.conf` | `extensions.ael`

| *[meine-telefone]* *exten => 20,1,*Answer() *exten => 20,n,*Playback(beep) *exten => 20,n,*Hangup() | *context meine-telefone {* *20 => {* Answer(); Playback(beep); Hangup(); *}* *}*
|===

Es sei auch auf das bei Asterisk mitgelieferte Kommandozeilen-Werkzeug
+`aelparse`+ hingewiesen, mit dem Sie jederzeit seine
`extensions.ael` wieder in das
`extensions.conf`-Format konvertieren können. Wir werden
später noch darauf eingehen (siehe xref:aelparse.adoc[Abschnitt 7.2, „aelparse“]).

[NOTE]
====
Am Rande sei noch gesagt, dass hier, wie bei Asterisk üblich, mit
AEL immer AEL2 gemeint ist, denn die erste Version war nur ein
experimenteller Versuch.
====
