[[aelparse]]
= aelparse

Bei Asterisk wird das Kommandozeilen-Werkzeug
+`aelparse`+ mitgeliefert, mit dem Sie
jederzeit Ihre `extensions.ael` wieder in das
`extensions.conf`-Format konvertieren können, falls Sie
das jemals tun wollen. +`aelparse`+
ist also so eine Art Test-Compiler für die im Vergleich zu
`extensions.conf` etwas höhere Programmiersprache
AEL.

`aelparse` liest immer automatisch die Datei
`/etc/asterisk/extensions.ael`, außer man ruft es mit
der Option `-d` auf. Dann wird in dem Verzeichnis, in dem
man sich gerade befindet, nach der `extensions.ael`
gesucht.

Ohne die Option `-n` werden viele Informationen
ausgegeben, die hauptsächlich für die Entwickler von Asterisk interessant
sind. Für eine übersichtliche Ausgabe ruften Sie
`aelparse` immer mit `-n` auf –
oder mit `-q` für noch weniger Zeilen.

[TIP]
====
+`aelparse`+ ist gut geeignet,
um Syntaxfehler in der `extensions.ael` zu
finden.
====

Mit der Option `-w` wird der eingelesene Dialplan
in die Datei `extensions.conf.aeldump` im aktuellen
Verzeichnis ausgegeben.

[source,shell]
----
asterisk:/etc/asterisk# aelparse -q -w
LOG: lev:4 file:ael2_parse line:543 func: main 19 contexts, 25 extensions, 62 priorities
----
