[[agi-command-exec]]
= `EXEC`

[source]
----
EXEC Applikation Argumente
----

Führt eine Dialplan-Applikation aus (siehe xref:applications.adoc[Anhang C, _Applikationen im Dialplan_]). Die _`Argumente`_ werden
dabei der Applikation übergeben. Mehrere Argumente werden durch ein
Pipe-Zeichen (`|`) getrennt.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -2 | Fehler. Konnte die Applikation nicht finden/aufrufen.
| _`Wert`_ | Erfolgreich. Ergebniswert der Applikation.
|===

Beispiel:

[source]
----
EXEC Dial Zap/g1/123456
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: EXEC <application> <options>
Executes <application> with given <options>.
Returns whatever the application returns, or -2 on failure to find application

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,3 +1,4 @@
Usage: EXEC <application> <options>
Executes <application> with given <options>.
Returns whatever the application returns, or -2 on failure to find application
+ Runs Dead : Yes
