[[agi-command-record-file]]
= `RECORD FILE`

[source]
----
RECORD FILE Dateiname Format Escape_Ziffern Timeout [Offset] [BEEP] [s=Stille]
----

Funktioniert wie ein Rekorder, der alle Audiosignale in der Datei
_`Dateiname`_ im angegebenen
_`Format`_ aufzeichnet. Beendet werden kann dies durch
einen definierten DTMF-Ton _`Escape_Ziffern`_ oder
durch einen _`Timeout`_ in Millisekunden. (Dabei steht
-1 für keinen Timeout.)

_`BEEP`_ spielt vor der Aufnahme einen Signalton.
_`Stille`_ definiert die Anzahl der Stille-Sekunden,
bis die Applikation auch ohne Eingabe von DTMF-Tönen einen Timeout
ausgibt.

Mit _`Offset`_ wird vor Beginn der Aufnahme so
viele Sekunden wie angegeben gewartet.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Erfolgreich
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: RECORD FILE <filename> <format> <escape digits> <timeout> \
[offset samples] [BEEP] [s=silence]
Record to a file until a given dtmf digit in the sequence is received
Returns -1 on hangup or error. The format will specify what kind of file
will be recorded. The timeout is the maximum record time in milliseconds, or
-1 for no timeout. "Offset samples" is optional, and, if provided, will seek
to the offset without exceeding the end of the file. "silence" is the number
of seconds of silence allowed before the function returns despite the
lack of dtmf digits or reaching timeout. Silence value must be
preceeded by "s=" and is also optional.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -8,3 +8,4 @@
of seconds of silence allowed before the function returns despite the
lack of dtmf digits or reaching timeout. Silence value must be
preceeded by "s=" and is also optional.
+ Runs Dead : No
