[[agi-command-send-text]]
= `SEND TEXT`

[source]
----
SEND TEXT "zu sendender Text"
----

Sendet den angegebenen Text auf den aktuellen Kanal. Diese Funktion
wird von den meisten Channels nicht unterstützt.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Erfolgreich
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SEND TEXT "<text to send>"
Sends the given text on a channel. Most channels do not support the
transmission of text. Returns 0 if text is sent, or if the channel does not
support text transmission. Returns -1 only on error/hangup. Text
consisting of greater than one word should be placed in quotes since the
command only accepts a single argument.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,3 +4,4 @@
support text transmission. Returns -1 only on error/hangup. Text
consisting of greater than one word should be placed in quotes since the
command only accepts a single argument.
+ Runs Dead : No
