[[agi-command-control-stream-file]]
= `CONTROL STREAM FILE`

[source]
----
CONTROL STREAM FILE Datei EscapeZiffern [skipms] [ffchar] [rewchr] [pausechr]
----

Spielt die angegebene Audio-Datei (Angabe ohne den Dateinamen) ab.
Die Wiedergabe kann mit den angegebenen Zifferntasten gesteuert
werden.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler, oder der Kanal wurde getrennt
| 0 | Wiedergabe ohne Tastendruck abgeschlossen
| _`x`_ | numerischer ASCII-Wert der Zifferntaste: `0`: 48, `1`: 49, ..., `9`: 57, `*`: 42, `#`: 35
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: CONTROL STREAM FILE <filename> <escape digits> [skipms] [ffchar] [rewchr] [pausechr]
Send the given file, allowing playback to be controled by the given
digits, if any. Use double quotes for the digits if you wish none to be
permitted. Returns 0 if playback completes without a digit
being pressed, or the ASCII numerical value of the digit if one was pressed,
or -1 on error or if the channel was disconnected. Remember, the file
extension must not be included in the filename.

Note: ffchar and rewchar default to * and # respectively.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -7,3 +7,4 @@
extension must not be included in the filename.

Note: ffchar and rewchar default to * and # respectively.
+ Runs Dead : No
