[[agi-command-wait-for-digit]]
= `WAIT FOR DIGIT`

[source]
----
WAIT FOR DIGIT Timeout
----

Wartet auf die Eingabe eines DTMF-Tons.
_`Timeout`_ gibt den Timeout der Applikation in
Millisekunden an.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Timeout
| _`Wert`_ | ASCII-Wert der Eingabe, die zum Abbruch geführt hat
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: WAIT FOR DIGIT <timeout>
Waits up to 'timeout' milliseconds for channel to receive a DTMF digit.
Returns -1 on channel failure, 0 if no digit is received in the timeout, or
the numerical value of the ascii of the digit if one is received. Use -1
for the timeout value if you desire the call to block indefinitely.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -3,3 +3,4 @@
Returns -1 on channel failure, 0 if no digit is received in the timeout, or
the numerical value of the ascii of the digit if one is received. Use -1
for the timeout value if you desire the call to block indefinitely.
+ Runs Dead : No
