[[agi-command-tdd-mode]]
= `TDD MODE`

[source]
----
TDD MODE [on|off]
----

Aktiviert (`on`) oder deaktiviert (`off`) die
Übertragung und den Empfang des TDD-Protokolls (Baudot) für TDD-Geräte
(Telecommunications Device für the Deaf, Telekommunikationsgerät für
Taubstumme, auch Schreibtelefon genannt) auf dem aktiven Kanal. Bisher
wird TDD nur von Zap-Kanälen unterstützt.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Der Channel ist nicht TDD-fähig.
| 1 | Erfolgreich
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: TDD MODE <on|off>
Enable/Disable TDD transmission/reception on a channel. Returns 1 if
successful, or 0 if channel is not TDD-capable.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,3 +1,4 @@
Usage: TDD MODE <on|off>
Enable/Disable TDD transmission/reception on a channel. Returns 1 if
successful, or 0 if channel is not TDD-capable.
+ Runs Dead : No
