[[agi-command-stream-file]]
= `STREAM FILE`

[source]
----
STREAM FILE Dateiname Escape_Ziffern [Offset]
----

Spielt die angegebene Datei _`Dateiname`_ ab
(dabei darf keine Dateiendung wie `.wav` oder `.gsm`
angegeben werden). Das Abspielen kann dabei durch die Eingabe einer Ziffer
abgebrochen werden, die in `Escape_Ziffern` definiert wurde.
Ist dies nicht erwünscht (soll also kein Abbruch möglich sein), so muss an
dieser Stelle `""` angegeben werden. Mit
_`Offset`_ kann ein Offset zum Start der Datei bestimmt
werden.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Erfolgreich (die Datei wurde komplett abgespielt)
| _`Wert`_ | ASCII-Wert der Eingabe, die zum Abbruch geführt hat
|===

[IMPORTANT]
====
`STREAM FILE` funktioniert manchmal nicht korrekt mit
anderen Sprachen als Englisch. Stattdessen kann man +EXEC Playback
_`Dateiname`_+ verwenden.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: STREAM FILE <filename> <escape digits> [sample offset]
Send the given file, allowing playback to be interrupted by the given
digits, if any. Use double quotes for the digits if you wish none to be
permitted. If sample offset is provided then the audio will seek to sample
offset before play starts. Returns 0 if playback completes without a digit
being pressed, or the ASCII numerical value of the digit if one was pressed,
or -1 on error or if the channel was disconnected. Remember, the file
extension must not be included in the filename.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -6,3 +6,4 @@
being pressed, or the ASCII numerical value of the digit if one was pressed,
or -1 on error or if the channel was disconnected. Remember, the file
extension must not be included in the filename.
+ Runs Dead : No
