[[agi-command-set-music]]
= `SET MUSIC`

[source]
----
SET MUSIC [on [Klasse]|off]
----

Aktiviert (`on`) oder deaktiviert (`off`) die
Warteschleifenmusik. Wenn _`Klasse`_ nicht angegeben
wurde, wird die Musikklasse `default` benutzt (siehe
Konfigurationsdatei
`/etc/asterisk/musiconhold.conf`).

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| 0 | Gibt immer 0 zurück.
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SET MUSIC ON <on|off> <class>
Enables/Disables the music on hold generator. If <class> is
not specified, then the default music on hold class will be used.
Always returns 0.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -2,3 +2,4 @@
Enables/Disables the music on hold generator. If <class> is
not specified, then the default music on hold class will be used.
Always returns 0.
+ Runs Dead : No
