[[agi-command-set-priority]]
= `SET PRIORITY`

[source]
----
SET PRIORITY Priorität
----

Setzt die Priorität, die nach dem Ausführen der AGI-Applikation
angesprungen wird. (Als Priorität kann auch ein Label angegeben
werden.)

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| 0 | Gibt immer 0 zurück.
|===

[IMPORTANT]
====
Es wird nicht überprüft, ob die Priorität existiert. Wenn Sie eine
ungültige Priorität angeben, wird der Anruf nach Beendigung des Skriptes
aufgelegt.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SET PRIORITY <priority>
Changes the priority for continuation upon exiting the application.
The priority must be a valid priority or label.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,3 +1,4 @@
Usage: SET PRIORITY <priority>
Changes the priority for continuation upon exiting the application.
The priority must be a valid priority or label.
+ Runs Dead : No
