[[agi-datenstroeme]]
= Datenströme
:description: AGI-Datenströme in Asterisk: stdin, stdout, stderr im Skript.

Für AGI-Skripte ist ein Verständnis des Unix-Datenstrom-Models
unabdingbar. Im Anhang dieses Buches finden Sie Informationen zu diesem
Prinzip.

[[agi-stdin]]
== STDIN

Das AGI-Skript bekommt über den „standard input“
(STDIN) einige Informationen von Asterisk. Das Format sieht
folgendermaßen aus:

[source]
----
agi_request: mein-skript.py
agi_channel: PJSIP/2000-00000001
agi_language: de
agi_callerid: 2000
agi_calleridname: Hans Beispiel
agi_context: intern
agi_extension: 1234
agi_priority: 2
----

Nach dem Übergeben dieser Grundinformationen sendet Asterisk
noch eine Leerzeile, um dem AGI-Skript mitzuteilen, dass die Übertragung
beendet ist.

[[agi-headers]]
=== AGI-Header

Die folgende Aufstellung listet alle von Asterisk
weitergegebenen Header auf:

* `agi_request`
+
Der Dateiname des aufgerufenen AGI-Programms
* `agi_channel`
+
Der Channel
* `agi_language`
+
Die eingestellte Sprache (z. B. `en` für Englisch
oder `de` für Deutsch)
* `agi_type`
+
Die Channel-Art (z. B. `PJSIP` für SIP, `IAX2` für IAX, `Local` für
Local-Channels)
* `agi_uniqueid`
+
Eine im System unique (einmalige) ID für das Gespräch
* `agi_callerid`
+
Die Caller-ID (z. B. `Hans Meier
<2000>`)
* `agi_context`
+
Der Ursprungs-Context
* `agi_extension`
+
Die Ursprungs-Extension
* `agi_priority`
+
Die Priorität in der Extension beim Aufruf des
AGI-Skripts
* `agi_accountcode`
+
Abrechnungscode
* `agi_calleridname`
+
Name aus der Caller-ID (z. B. `Hans
Meier`)
* `agi_callingpres`
+
Presentation-Indicator der Caller-ID (z. B. `allowed_not_screened`,
`prohib`), steuert die Anzeige beim Angerufenen

[[agi-stdout]]
== STDOUT

Nachdem das AGI-Skript die Grundinformationen von Asterisk
erhalten hat, beginnt es mit seiner Arbeit und gibt Befehle über
„standard out“ (STDOUT) zurück an Asterisk. Um sich diese
Kommunikation anzuschauen, kann man im CLI mit `set verbose
5` den Verbosity-Level entsprechend hochsetzen.

[[agi-stderr]]
== STDERR

„Standard error“ (STDERR) ist der formale Weg, um
Fehler- oder Debug-Meldungen vom AGI-Skript auf die Console (das CLI)
von Asterisk zu bringen.
