[[agi-command-database-get]]
= `DATABASE GET`

[source]
----
DATABASE GET Familie Schlüssel
----

Gibt den entsprechenden Eintrag für
_`Familie`_/_`Schlüssel`_ aus der
Asterisk-Datenbank aus.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| 0 | Fehler
| 1 (_`Wert`_) | Erfolgreich mit dem gefundenen Wert
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: DATABASE GET <family> <key>
Retrieves an entry in the Asterisk database for a
given family and key.
Returns 0 if <key> is not set. Returns 1 if <key>
is set and returns the variable in parentheses.
Example return code: 200 result=1 (testvariable)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,3 +4,4 @@
Returns 0 if <key> is not set. Returns 1 if <key>
is set and returns the variable in parentheses.
Example return code: 200 result=1 (testvariable)
+ Runs Dead : Yes
