[[agi-commands]]
= AGI-Befehle
__Befehle auf der AGI-Schnittstelle („Asterisk Gateway
Interface“)__

Die folgenden Steuerungsbefehle ermöglichen es einem AGIfootnote:[AGI = die Schnittstelle „Asterisk Gateway Interface“]-Skript (siehe xref:kapitel-agi.adoc[Kapitel 20, _Asterisk Gateway Interface (AGI)_]), mit Asterisk zu
interagieren. Die meisten dieser Befehle sind von Dialplan-Applikationen
(siehe xref:applications.adoc[Anhang C, _Applikationen im Dialplan_]) oder Funktionen (siehe xref:functions.adoc[Anhang D, _Funktionen im Dialplan_]) mit ähnlichen Namen abgeleitet.

[IMPORTANT]
====
Falls Sie Parameter, die nicht am Ende stehen, auslassen wollen,
müssen Sie stattdessen `""` angeben!
====

[NOTE]
====
Der Hinweis +Runs Dead:
_`Yes|No`_+ in der jeweiligen Beschreibung
ab Asterisk 1.6 besagt, ob der Befehl auch (mit
`DeadAGI()`, siehe xref:applications-deadagi.adoc[Abschnitt C.37, „`DeadAGI()`“]) für einen toten, d. h. einen bereits
aufgelegten Anruf (genauer: Kanal) ausgeführt werden kann.
====
