[[agi-command-say-date]]
= `SAY DATE`

[source]
----
SAY DATE Timestamp [Escape_Ziffern]
----

Sagt das übergebene Datum an. _`Timestamp`_ ist
dabei die Anzahl der Sekunden seit 00:00:00 Uhr am 1. Januar 1970. Die
Ausgabe kann durch die Eingabe einer Ziffer abgebrochen werden, die in
`Escape_Ziffern` bestimmt wird.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Erfolgreich
| _`Wert`_ | ASCII-Wert der Eingabe, die zum Abbruch geführt hat
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SAY DATE <date> <escape digits>
Say a given date, returning early if any of the given DTMF digits are
received on the channel. <date> is number of seconds elapsed since 00:00:00
on January 1, 1970, Coordinated Universal Time (UTC). Returns 0 if playback
completes without a digit being pressed, or the ASCII numerical value of the
digit if one was pressed or -1 on error/hangup.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,3 +4,4 @@
on January 1, 1970, Coordinated Universal Time (UTC). Returns 0 if playback
completes without a digit being pressed, or the ASCII numerical value of the
digit if one was pressed or -1 on error/hangup.
+ Runs Dead : No
