[[agi-command-say-alpha]]
= `SAY ALPHA`

[source]
----
SAY ALPHA String [Escape_Ziffern]
----

Buchstabiert den übergebenen _`String`_. Die
Ausgabe kann durch die Eingabe einer Ziffer abgebrochen werden, die in
_`Escape_Ziffern`_ bestimmt wird.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler
| 0 | Erfolgreich
| _`Wert`_ | ASCII-Wert der Eingabe, die zum Abbruch geführt hat
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SAY ALPHA <number> <escape digits>
Say a given character string, returning early if any of the given DTMF digits
are received on the channel. Returns 0 if playback completes without a digit
being pressed, or the ASCII numerical value of the digit if one was pressed or
-1 on error/hangup.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -3,3 +3,4 @@
are received on the channel. Returns 0 if playback completes without a digit
being pressed, or the ASCII numerical value of the digit if one was pressed or
-1 on error/hangup.
+ Runs Dead : No
