[[agi-command-receive-text]]
= `RECEIVE TEXT`

[source]
----
RECEIVE TEXT Timeout
----

Wenn ein Channel die Übermittlung von Text unterstützt, dann kann
mit `RECEIVE CHAR` ein solcher Text empfangen werden.
_`Timeout`_ gibt die Wartezeit für den Empfang in
Millisekunden an (0 für unendlich).

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| -1 | Fehler oder Hangup
| _`Wert`_ (timeout) | Der empfangene Text bei Timeout
| _`Wert`_ | Der empfangene Text
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: RECEIVE TEXT <timeout>
Receives a string of text on a channel. Specify timeout to be the
maximum time to wait for input in milliseconds, or 0 for infinite. Most channels
do not support the reception of text. Returns -1 for failure or 1 for success, and the string in parentheses.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -2,3 +2,4 @@
Receives a string of text on a channel. Specify timeout to be the
maximum time to wait for input in milliseconds, or 0 for infinite. Most channels
do not support the reception of text. Returns -1 for failure or 1 for success, and the string in parentheses.
+ Runs Dead : No
