[[agi-command-set-autohangup]]
= `SET AUTOHANGUP`

[source]
----
SET AUTOHANGUP Timeout
----

Stellt ein automatisches Auflegen nach der angegebenen Anzahl von
Sekunden ein. Mit dem Wert `0` kann diese Funktion wieder
deaktiviert werden.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| 0 | Erfolgreich (Wert wurde gesetzt)
|===

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SET AUTOHANGUP <time>
Cause the channel to automatically hangup at <time> seconds in the
future. Of course it can be hungup before then as well. Setting to 0 will
cause the autohangup feature to be disabled on this channel.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -2,3 +2,4 @@
Cause the channel to automatically hangup at <time> seconds in the
future. Of course it can be hungup before then as well. Setting to 0 will
cause the autohangup feature to be disabled on this channel.
+ Runs Dead : No
