[[agi-command-set-extension]]
= `SET EXTENSION`

[source]
----
SET EXTENSION Extension
----

Setzt die Extension, die nach dem Ausführen der AGI-Applikation
angesprungen wird.

Ergebniswerte nach Ausführung:

[cols="2*"]
|===
| 0 | Gibt immer 0 zurück.
|===

[IMPORTANT]
====
Es wird nicht überprüft, ob die Extension existiert. Wenn Sie eine
ungültige Extension angeben, wird Asterisk nach Beendigung des Skripts
bei der `i`-Extension weitermachen, falls vorhanden.
Ansonsten wird der Anruf aufgelegt.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AGI-Befehl in Asterisk 1.4:
Usage: SET EXTENSION <new extension>
Changes the extension for continuation upon exiting the application.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,2 +1,3 @@
Usage: SET EXTENSION <new extension>
Changes the extension for continuation upon exiting the application.
+ Runs Dead : No
