[[anhang-conf-templates]]
= Konfigurations-Templates

Konfigurationsdateien wie die `sip.conf`,
`iax.conf` etc. haben oft viele ähnliche Einträge und
sind dadurch schlecht wartbar.

Das könnte in einer normalen `sip.conf` Folgendes
stehen:

[source]
----
[201]
username=201
secret=1111
context=default
type=friend
qualify=yes
host=dynamic
canreinvite=no

[202]
username=202
secret=2222
context=default
type=friend
qualify=yes
host=dynamic
canreinvite=no

[203]
username=203
secret=3333
context=default
type=friend
qualify=yes
host=dynamic
canreinvite=no
----

Asterisk bietet aber die kaum bekannte Möglichkeit, hierfür
_Templates_ (Vorlagen) zu verwenden. Mit einem Template
für unsere Telefone sähe das so aus:

[source]
----
[meine-telefone](!)     ; dieser Abschnitt ist das Template
context=default
type=friend
qualify=yes
host=dynamic
canreinvite=no

[201](meine-telefone)   ; Telefon 201
username=201
secret=1111

[202](meine-telefone)   ; Telefon 202
username=202
secret=2222

[203](meine-telefone)   ; Telefon 203
username=203
secret=3333
----

Hier erben die Abschnitte `201`, `202` und
`203` alle im Abschnitt (dem Template)
`meine-telefone` gesetzten Werte.

Das ist besonders interssant, wenn man verschiedene Gruppen oder
Klassen von sehr ähnlichen Einträgen hat, also wenn nicht die Möglichkeit
besteht, einfach alle Gemeinsamkeiten in den Abschnitt
`[general]` zu schreiben. Schon in diesem einfachen Beispiel
haben wir uns ein paar Zeilen gespart und können vor allem Veränderungen für
alle Telefone der „Klasse“ `meine-telefone` an
zentraler Stelle vornehmen.
