[[applications-waituntil]]
= `WaitUntil()`

Wartet bis zu einer vorgegebenen Zeit.

[source]
----
WaitUntil(Unixzeit)
----

Wartet bis zu einer bestimmten Uhrzeit (Unix-Timestamp).

Setzt danach die Channel-Variable `WAITUNTILSTATUS`
auf einen der folgenden Werte:

`OK`:: Erfolgreich gewartet.
`FAILURE`:: Ungültige Zeitangabe.
`HANGUP`:: Erfolgreich gewartet.
`PAST`:: Erfolgreich gewartet.

[source]
----
exten => s,1,Answer()
exten => s,n,WaitUntil(${STRPTIME(2008-12-06 14:30:00|Europe/Berlin|%Y-%m-%d %H:%M:%S)})
exten => s,n,SayUnixTime()
----

Anders gesagt: Eine Applikation, die niemand braucht.

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'WaitUntil' =-

[Synopsis]
Wait (sleep) until the current time is the given epoch

[Description]
WaitUntil(<epoch>): Waits until the given time. Sets WAITUNTILSTATUS to
one of the following values:
OK Wait succeeded
FAILURE Invalid argument
HANGUP Channel hung up before time elapsed
PAST The time specified was already past

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-waituntil.adoc[Abschnitt C.194, „`WaitUntil()`“]
