[[applications-agentlogin]]
= `AgentLogin()`

Erlaubt es einem Anruf-Agenten, sich in das System einzuloggen bzw.
sich am System anzumelden.

[source]
----
AgentLogin([Agenten-Nr][,Optionen])
----

Meldet den gegenwärtigen Anrufer als Call Agent (optional durch
`Agenten-Nr` zu identifizieren) im Anruf-Warteschlangen-System
an. Solange er als Agent angemeldet ist, kann er Anrufe entgegennehmen und
hört bei neuen eingehenden Anrufen einen Piepton in der Leitung. Der Agent
kann den Anruf durch Betätigen der Stern-Taste (`*`)
beenden.

Der `Optionen`-Parameter kann den Wert `s`
enthalten, der ein Silent Login (stille Anmeldung) bewirkt.

[source]
----
; still als Agent 33 (wie in agents.conf definiert) einloggen
exten => 123,1,AgentLogin(33,s)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'AgentLogin' =-

[Synopsis]
Call agent login

[Description]
AgentLogin([AgentNo][|options]):
Asks the agent to login to the system. Always returns -1. While
logged in, the agent can receive calls and will hear a 'beep'
when a new call comes in. The agent can dump the call by pressing
the star key.
The option string may contain zero or more of the following characters:
's' -- silent login - do not announce the login ok segment after agent logged in/off

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,10 +4,10 @@
Call agent login

[Description]
- AgentLogin([AgentNo][|options]):
+ AgentLogin([AgentNo][,options]):
Asks the agent to login to the system. Always returns -1. While
logged in, the agent can receive calls and will hear a 'beep'
when a new call comes in. The agent can dump the call by pressing
the star key.
The option string may contain zero or more of the following characters:
- 's' -- silent login - do not announce the login ok segment after agent logged in/off
+ 's' -- silent login - do not announce the login ok segment after agent logged on/off

.Siehe auch
xref:applications-agentcallbacklogin.adoc[Abschnitt C.4, „`AgentCallbackLogin()`“]
