[[applications-privacymanager]]
= `PrivacyManager()`

Verlangt die Eingabe der Telefonnummer eines Teilnehmers, falls
keine Caller-ID-Informationen empfangen werden.

[source]
----
PrivacyManager([Versuche[,Länge[,Optionen]]])
----

Wird keine Caller-ID empfangen, wird der Channel beantwortet und
der Anrufer aufgefordert, seine Telefonnummer einzugeben. Wird auf dem
Channel eine Caller-ID empfangen, tut `PrivacyManager()`
nichts.

Dem Anrufer werden dabei `Versuche` Versuche (Default: 3)
gewährt, um eine Telefonnummer mit mindestens `Länge` Stellen
(Default: 10) einzugeben. Diese Default-Werte werden aus der Datei
`privacy.conf` gelesen. Sie enthält die beiden folgenden
Einträge:

`maxretries`:: Gibt die Anzahl der Versuche an, die einem Anrufer zur Eingabe einer Caller-ID gewährt werden (Standard: 3).
`minlength`:: Gibt die minimale erlaubte Anzahl von Ziffern in der eingegebenen Caller-ID-Nummer an (Standard: 10).

Wenn Sie nicht wollen, dass bei jedem Aufruf aus der Datei
gelesen werden muss, geben Sie bei `PrivacyManager()` explizit
Werte an.

Mit der Option `j` wird zur Priorität n+101 gesprungen,
wenn der Anrufer nicht innerhalb der erlaubten Versuche eine Nummer der
erforderlichen Länge eingibt.

Die Channel-Variable `PRIVACYMGRSTATUS` wird entweder
auf `SUCCESS` oder auf `FAILED` gesetzt.

[source]
----
exten => 123,1,Answer()
exten => 123,n,PrivacyManager()
exten => 123,n,GotoIf($["${PRIVACYMGRSTATUS}" = "FAILED"]?pm-fehler,1)
exten => 123,n,Dial(Zap/1)

exten => pm-fehler,1,Playback(tut-uns-leid)
exten => pm-fehler,n,Playback(vm-goodbye)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'PrivacyManager' =-

[Synopsis]
Require phone number to be entered, if no CallerID sent

[Description]
PrivacyManager([maxretries[|minlength[|options]]]): If no Caller*ID
is sent, PrivacyManager answers the channel and asks the caller to
enter their phone number. The caller is given 3 attempts to do so.
The application does nothing if Caller*ID was received on the channel.
Configuration file privacy.conf contains two variables:
maxretries default 3 -maximum number of attempts the caller is allowed
to input a callerid.
minlength default 10 -minimum allowable digits in the input callerid number.
If you don't want to use the config file and have an i/o operation with
every call, you can also specify maxretries and minlength as application
parameters. Doing so supercedes any values set in privacy.conf.
The option string may contain the following character:
'j' -- jump to n+101 priority after <maxretries> failed attempts to collect
the minlength number of digits.
The application sets the following channel variable upon completion:
PRIVACYMGRSTATUS The status of the privacy manager's attempt to collect
a phone number from the user. A text string that is either:
SUCCESS | FAILED

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,20 +4,14 @@
Require phone number to be entered, if no CallerID sent

[Description]
- PrivacyManager([maxretries[|minlength[|options]]]): If no Caller*ID
+ PrivacyManager([maxretries][,minlength][,context]): If no Caller*ID
is sent, PrivacyManager answers the channel and asks the caller to
- enter their phone number. The caller is given 3 attempts to do so.
+ enter their phone number. The caller is given 'maxretries' attempts to do so.
The application does nothing if Caller*ID was received on the channel.
- Configuration file privacy.conf contains two variables:
maxretries default 3 -maximum number of attempts the caller is allowed
to input a callerid.
minlength default 10 -minimum allowable digits in the input callerid number.
- If you don't want to use the config file and have an i/o operation with
- every call, you can also specify maxretries and minlength as application
- parameters. Doing so supercedes any values set in privacy.conf.
- The option string may contain the following character:
- 'j' -- jump to n+101 priority after <maxretries> failed attempts to collect
- the minlength number of digits.
+ context context to check the given Caller*ID against patterns.
The application sets the following channel variable upon completion:
PRIVACYMGRSTATUS The status of the privacy manager's attempt to collect
a phone number from the user. A text string that is either:

.Siehe auch
xref:applications-zapateller.adoc[Abschnitt C.196, „`Zapateller()`“]
