[[applications-alarmreceiver]]
= `AlarmReceiver()`

Bietet Unterstützung für den Empfang von Alarm-Reporten von einem
Einbrecher- oder Feueralarm-Bedienfeld.

[source]
----
AlarmReceiver()
----

Emuliert einen Alarm-Empfänger und ermöglicht es Asterisk,
spezielle Daten von Einbrecher- und/oder Feueralarm-Bedienfeldern zu
empfangen und zu dekodieren. Zum jetzigen Zeitpunkt wird ausschließlich das
Ademco-Contact-ID-Format unterstützt.

Nachdem `AlarmReceiver()` aufgerufen worden ist, wird
ein Handshake mit dem Alarm-Bedienfeld durchgeführt, werden Events empfangen
und validiert und anschließend gespeichert, bis das Bedienfeld die
Verbindung beendet. Nachdem das Bedienfeld die Verbindung beendet hat, wird
die in der `eventsmd`-Einstellung der Datei
`alarmreceiver.conf` spezifizierte Befehlskette von der
Anwendung ausgeführt, und die Events werden auf die Standardeingabe der
Anwendung umgeleitet. Die Datei `alarmreceiver.conf`
enthält ebenfalls Einstellungen zum DTMF-Timing und für die Lautstärke der
Meldetöne.

Für die zuverlässige Funktion dieser Anwendung kann keine Garantie
übernommen werden. Verlassen Sie sich also nicht ausschließlich auf diese
Anwendung, wenn Sie sie nicht bereits ausgiebig getestet haben!

Diese Applikation gibt immer 0 zurück.

[source]
----
; Asterisk soll Meldungen eines Feueralarm-Knopfes empfangen:
exten => s,1,AlarmReceiver()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'AlarmReceiver' =-

[Synopsis]
Provide support for receiving alarm reports from a burglar or fire alarm panel

[Description]
AlarmReceiver(): Only 1 signalling format is supported at this time: Ademco
Contact ID. This application should be called whenever there is an alarm
panel calling in to dump its events. The application will handshake with the
alarm panel, and receive events, validate them, handshake them, and store them
until the panel hangs up. Once the panel hangs up, the application will run the
system command specified by the eventcmd setting in alarmreceiver.conf and pipe
the events to the standard input of the application. The configuration file also
contains settings for DTMF timing, and for the loudness of the acknowledgement
tones.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -1,7 +1,7 @@
-= Info about application 'AlarmReceiver' =-

[Synopsis]
- Provide support for receving alarm reports from a burglar or fire alarm panel
+ Provide support for receiving alarm reports from a burglar or fire alarm panel

[Description]
AlarmReceiver(): Only 1 signalling format is supported at this time: Ademco

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
`alarmreceiver.conf`
