[[applications-continuewhile]]
= `ContinueWhile()`

Springt während der Ausführung einer While-Schleife wieder zum
Anfang.

[source]
----
ContinueWhile()
----

Mit `ContinueWhile()` kann die Ausführung einer
While-Schleife im Dialplan unterbrochen werden. Es wird dann direkt zum
Beginn der While-Schleife gesprungen und die Bedingung erneut
geprüft.

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ContinueWhile' =-

[Synopsis]
Restart a While loop

[Description]
Usage: ContinueWhile()
Returns to the top of the while loop and re-evaluates the conditional.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,5 +4,4 @@
Restart a While loop

[Description]
- Usage: ContinueWhile()
- Returns to the top of the while loop and re-evaluates the conditional.
+ ContinueWhile(): Returns to the top of the while loop and re-evaluates the conditional.

.Siehe auch
xref:applications-while.adoc[Abschnitt C.195, „`While()`“], xref:applications-exitwhile.adoc[Abschnitt C.53, „`ExitWhile()`“]
