[[applications-trysystem]]
= `TrySystem()`

Versucht die Ausführung eines Shell-Befehls.

[source]
----
TrySystem(Befehl)
----

Führt wie `System()` einen Befehl auf der Shell
`sh` aus, liefert aber stets 0 zurück, wohingegen
`System()` bei einem Fehler -1 zurückgibt.

Setzt die Channel-Variable `SYSTEMSTATUS` auf
`SUCCESS` (erfolgreich ausgeführt), `FAILURE` (konnte
nicht ausgeführt werden) oder `APPERROR` (Befehl ausgeführt, aber
mit Exit-Code ungleich 0).

[source]
----
exten => 123,1,TrySystem(echo 'Hallo Welt' > /tmp/hallo.txt)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'TrySystem' =-

[Synopsis]
Try executing a system command

[Description]
TrySystem(command): Executes a command by using system().
on any situation.
Result of execution is returned in the SYSTEMSTATUS channel variable:
FAILURE Could not execute the specified command
SUCCESS Specified command successfully executed
APPERROR Specified command successfully executed, but returned error code

Old behaviour:
If the command itself executes but is in error, and if
there exists a priority n + 101, where 'n' is the priority of the current
instance, then the channel will be setup to continue at that
priority level. Otherwise, System will terminate.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -10,9 +10,3 @@
FAILURE Could not execute the specified command
SUCCESS Specified command successfully executed
APPERROR Specified command successfully executed, but returned error code
-
- Old behaviour:
- If the command itself executes but is in error, and if
- there exists a priority n + 101, where 'n' is the priority of the current
- instance, then the channel will be setup to continue at that
- priority level. Otherwise, System will terminate.

.Siehe auch
xref:applications-system.adoc[Abschnitt C.176, „`System()`“], xref:functions-shell.adoc[Abschnitt D.88, „`SHELL()`“]
