[[applications-sipdtmfmode]]
= `SIPdtmfMode()`

Ändert das DTMF-Verfahren für einen SIP-Anruf.

[source]
----
SIPdtmfMode(Methode)
----

Ändert den DTMF-Modus für einen Anruf, der von einem SIP-Channel
ausgeht (nicht für einen Anruf auf einen SIP-Channel). `Methode`
kann die Werte `inband` (RTP), `info` oder
`rfc2833` annehmen.

[source]
----
exten => 123,n,SIPdtmfMode(rfc2833)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SIPDtmfMode' =-

[Synopsis]
Change the dtmfmode for a SIP call

[Description]
SIPDtmfMode(inband|info|rfc2833): Changes the dtmfmode for a SIP call

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,4 +4,4 @@
Change the dtmfmode for a SIP call

[Description]
- SIPDtmfMode(inband|info|rfc2833): Changes the dtmfmode for a SIP call
+ SIPDtmfMode(inband|info|rfc2833): Changes the dtmfmode for a SIP call

.Siehe auch
RFC 2833footnote:[http://www.ietf.org/rfc/rfc2833.txt], RFC 2976footnote:[http://www.ietf.org/rfc/rfc2976.txt]
