[[applications-receivefax]]
= `ReceiveFAX()`

Empfängt ein Fax.

[source]
----
ReceiveFAX(Dateiname[,Optionen])
----

`SendFax()` und `ReceiveFax()`
ersetzen den bekannten Patch zum Faxen durch `TxFax()` und
`RxFax()`. Sie verwenden ebenfalls die SpanDSP-Library.

`ReceiveFax()` empfängt ein eingehendes Fax und
speichert es als TIFF-Datei.

[source]
----
exten => 123,1,Verbose(1,### Eingehendes Fax ${CDR(uniqueid)})
exten => 123,n,Set(LOCALSTATIONID=Meine Firma)
exten => 123,n,ReceiveFAX(/tmp/fax-${CDR(uniqueid)}.tif)
exten => 123,n,Verbose(1,###       FAXSTATUS: ${FAXSTATUS})
exten => 123,n,Verbose(1,###        FAXERROR: ${FAXERROR})
exten => 123,n,Verbose(1,###         FAXMODE: ${FAXMODE})
exten => 123,n,Verbose(1,###        FAXPAGES: ${FAXPAGES})
exten => 123,n,Verbose(1,###      FAXBITRATE: ${FAXBITRATE})
exten => 123,n,Verbose(1,###   FAXRESOLUTION: ${FAXRESOLUTION})
exten => 123,n,Verbose(1,### REMOTESTATIONID: ${REMOTESTATIONID})
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'ReceiveFAX' =-

[Synopsis]
Receive a FAX

[Description]
ReceiveFAX(filename[|options]):
Receives a fax from the channel into the given filename overwriting
the file if it already exists. File created will have TIFF format.
The option string may contain zero or more of the following characters:
'c' -- makes the application behave as a calling machine
The default behaviour is to behave as an answering machine.

This application uses following variables:
LOCALSTATIONID to identify itself to the remote end.
LOCALHEADERINFO to generate a header line on each page.

This application sets the following channel variables upon completion:
FAXSTATUS - status of operation:
SUCCESS | FAILED
FAXERROR - Error when FAILED
FAXMODE - Mode used:
audio | T38
REMOTESTATIONID - CSID of the remote side.
FAXPAGES - number of pages sent.
FAXBITRATE - transmition rate.
FAXRESOLUTION - resolution.

Returns -1 in case of user hang up or any channel error.
Returns 0 on success.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-sendfax.adoc[Abschnitt C.145, „`SendFAX()`“]
