[[applications-incomplete]]
= `Incomplete()`

Signalisiert, dass die Extension unvollständig ist.

[source]
----
Incomplete(Optionen)
----

Signalisiert auf dem anrufenden Kanal, dass die gewählte Extension
noch nicht vollständig ist. Mit der Option `n` wird der
anrufende Kanal nicht beantwortet.

[source]
----
exten => 123,1,Incomplete(n)

exten => 1234,1,Verbose(1,### Hallo Welt);
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'Incomplete' =-

[Synopsis]
returns AST_PBX_INCOMPLETE value

[Description]
Incomplete([n]): Signals the PBX routines that the previous matched extension
is incomplete and that further input should be allowed before matching can
be considered to be complete. Can be used within a pattern match when
certain criteria warrants a longer match.
If the 'n' option is specified, then Incomplete will not attempt to answer
the channel first. Note that most channel types need to be in Answer state
in order to receive DTMF.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-progress.adoc[Abschnitt C.121, „`Progress()`“], xref:applications-proceeding.adoc[Abschnitt C.120, „`Proceeding()`“]
