[[applications-realtimeupdate]]
= `RealTimeUpdate()`

Aktualisiert einen Wert mithilfe des
RealTime-Konfigurationssteuerprogramms.

[source]
----
RealTimeUpdate(Familie,Spalte,Wert,UpdateSpalte,UpdateWert)
----

Benutzt das RealTime-Konfigurationssteuerprogrammsystem, um einen
Wert zu aktualisieren. Das Feld `UpdateSpalte` in der Zeile, bei
der die Spalte `UpdateSpalte` in der Familie `Familie`
mit `Wert` übereinstimmt, wird auf den Wert
`UpdateWert` aktualisiert.

[source]
----
; bei der Situation wie im Beispiel zu RealTime() könnten wir diesen
; Befehl ausführen:
exten => 123,1,RealTimeUpdate(sipusers,ext,5678,vorname,Peter)
; resultierender SQL-Befehl:
UPDATE sip_users SET vorname = 'Peter' WHERE ext = '5678'
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'RealTimeUpdate' =-

[Synopsis]
Realtime Data Rewrite

[Description]
Use the RealTime config handler system to update a value
RealTimeUpdate(<family>|<colmatch>|<value>|<newcol>|<newval>)

The column <newcol> in 'family' matching column <colmatch>=<value> will be
updated to <newval>. REALTIMECOUNT will be set with the number of rows
updated or -1 if an error occurs.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -7,4 +7,6 @@
Use the RealTime config handler system to update a value
RealTimeUpdate(<family>|<colmatch>|<value>|<newcol>|<newval>)

- The column <newcol> in 'family' matching column <colmatch>=<value> will be updated to <newval>
+ The column <newcol> in 'family' matching column <colmatch>=<value> will be
+ updated to <newval>. REALTIMECOUNT will be set with the number of rows
+ updated or -1 if an error occurs.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:applications-realtime.adoc[Abschnitt C.129, „`RealTime()`“], xref:functions-realtime.adoc[Abschnitt D.81, „`REALTIME()`“], xref:functions-realtime_store.adoc[Abschnitt D.83, „`REALTIME_STORE()`“]
