[[applications-digittimeout]]
= `DigitTimeout()`

Setzt einen Timeout auf einem Kanal.

[source]
----
DigitTimeout(Sekunden)
----

[IMPORTANT]
====
`DigitTimeout()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `TIMEOUT()` (xref:functions-timeout.adoc[Abschnitt D.101, „`TIMEOUT()`“]) ersetzt:

[source]
----
Set(TIMEOUT(digit)=Sekunden)
----
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'DigitTimeout' =-

[Synopsis]
Set maximum timeout between digits

[Description]
DigitTimeout(seconds): Set the maximum amount of time permitted between
digits when the user is typing in an extension. When this timeout expires,
after the user has started to type in an extension, the extension will be
considered complete, and will be interpreted. Note that if an extension
typed in is valid, it will not have to timeout to be tested, so typically
at the expiry of this timeout, the extension will be considered invalid
(and thus control would be passed to the 'i' extension, or if it doesn't
exist the call would be terminated). The default timeout is 5 seconds.
DigitTimeout has been deprecated in favor of Set(TIMEOUT(digit)=timeout)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-absolutetimeout.adoc[Abschnitt C.1, „`AbsoluteTimeout()`“], xref:applications-responsetimeout.adoc[Abschnitt C.135, „`ResponseTimeout()`“], xref:functions-timeout.adoc[Abschnitt D.101, „`TIMEOUT()`“]
