[[applications-getgroupmatchcount]]
= `GetGroupMatchCount()`

Gibt die Anzahl der Kanäle in einer Gruppe von Kanälen
zurück.

[source]
----
GetGroupMatchCount(Muster[@Kategorie])
----

[IMPORTANT]
====
`GetGroupMatchCount()` ist ab Asterisk 1.4 nicht
mehr vorhanden und wurde durch die Funktion
`GROUP_MATCH_COUNT()` (xref:functions-group_match_count.adoc[Abschnitt D.42, „`GROUP_MATCH_COUNT()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'GetGroupMatchCount' =-

[Synopsis]
Get the channel count of all groups that match a pattern

[Description]
Usage: GetGroupMatchCount(groupmatch[@category])
Calculates the group count for all groups that match the specified
pattern. Uses standard regular expression matching (see regex(7)).
Stores result in GROUPCOUNT. Always returns 0.
Note: This application has been deprecated, please use the function
GROUP_MATCH_COUNT.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-setgroup.adoc[Abschnitt C.158, „`SetGroup()`“], xref:applications-checkgroup.adoc[Abschnitt C.21, „`CheckGroup()`“], xref:applications-getgroupcount.adoc[Abschnitt C.61, „`GetGroupCount()`“], xref:functions-group_match_count.adoc[Abschnitt D.42, „`GROUP_MATCH_COUNT()`“]
