[[applications-iax2provision]]
= `IAX2Provision()`

Versorgt eine anrufende IAXy-Einheit.

[source]
----
IAX2Provision([Template])
----

Stellt einer anrufenden IAXy-Einheit die Vorlage
`Template` bereit. Ist keine Vorlage angegeben, wird die
Standard-Vorlage benutzt. IAXy-Versorgungsvorlagen sind in der
Konfigurationsdatei `iaxprov.conf` definiert.

Liefert 0 bei Erfolg oder -1 bei einem Fehler.

[source]
----
exten => 123,1,IAX2Provision(default)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'IAX2Provision' =-

[Synopsis]
Provision a calling IAXy with a given template

[Description]
IAX2Provision([template]): Provisions the calling IAXy (assuming
the calling entity is in fact an IAXy) with the given template or
default if one is not specified. Returns -1 on error or 0 on success.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —
