[[applications-zapras]]
= `ZapRAS()`

Führt den _Zaptel ISDN Remote Access Server_
aus.

[source]
----
ZapRAS(args)
----

Startet über `pppd` einen ISDN-RAS-Server auf dem
aktuellen Channel. Der Channel muss ein freier Channel (z. B. PRI Source)
und ein Zaptel-Channel sein, um diese Funktion durchführen zu können. (Eine
Modem-Emulation ist nicht enthalten.)

Um Zaptel zu kennen, muss `pppd` entsprechend
vorbereitet sein. `Argumente` ist eine Liste von durch das
`|`-Symbol getrennten Argumentenfootnote:[deren Erklärung hier zu weit führen würde; siehe http://www.voip-info.org/wiki/view/Asterisk+cmd+ZapRAS].

Liefert stets -1 zurück.

Diese Anwendungen ist nur für die Benutzung mit ISDN-Leitungen
ausgelegt, und Ihr Kernel muss mit einem Patch für die Unterstützung von
`ZapRAS()` versehen sein. Außerdem muss Ihr Kernel
ppp-Unterstützung bereitstellen.

[source]
----
exten => 123,1,Answer()
exten => 123,n,ZapRAS(debug|64000|noauth|netmask|255.255.255.0|10.0.0.1:10.0.0.2)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6**|————————
(* anderer Name)

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ZapRAS' =-

[Synopsis]
Executes Zaptel ISDN RAS application

[Description]
ZapRAS(args): Executes a RAS server using pppd on the given channel.
The channel must be a clear channel (i.e. PRI source) and a Zaptel
channel to be able to use this function (No modem emulation is included).
Your pppd must be patched to be zaptel aware. Arguments should be
separated by | characters.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6 (xref:applications-dahdiras.adoc[Abschnitt C.29, „`DAHDIRAS()`“]):
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,11 +1,11 @@
- -= Info about application 'ZapRAS' =-
+ -= Info about application 'DAHDIRAS' =-

[Synopsis]
- Executes Zaptel ISDN RAS application
+ Executes DAHDI ISDN RAS application

[Description]
- ZapRAS(args): Executes a RAS server using pppd on the given channel.
- The channel must be a clear channel (i.e. PRI source) and a Zaptel
+ DAHDIRAS(args): Executes a RAS server using pppd on the given channel.
+ The channel must be a clear channel (i.e. PRI source) and a DAHDI
channel to be able to use this function (No modem emulation is included).
- Your pppd must be patched to be zaptel aware. Arguments should be
- separated by | characters.
+ Your pppd must be patched to be DAHDI aware. Arguments should be
+ separated by , characters.

.Siehe auch
xref:applications-dahdiras.adoc[Abschnitt C.29, „`DAHDIRAS()`“]
