[[applications-waitexten]]
= `WaitExten()`

Wartet auf die Eingabe einer Extension.

[source]
----
WaitExten([Sekunden][,Optionen])
----

Wartet die angegebene Anzahl Sekunden auf die Eingabe einer neuen
Extension durch den Teilnehmer und liefert dann 0 zurück. Es können auch
Sekundenbruchteile übergeben werden (z. B. `1.5` für 1,5
Sekunden). Falls keine Zeitdauer spezifiziert wird, wird die Standardfrist
(Default Extension-Timeout) gewartet.

Als Option ist `m` möglich, was dem Anrufer Wartemusik
vorspielt, während auf eine Eingabe gewartet wird. Dabei kann optional in
runden Klammern die Musikklasse angegeben werden, z. B.
`m(rock)`.

[source]
----
; 10 Sekunden auf die Eingabe einer Extension warten:
exten => s,1,Answer()
exten => s,n,Playback(enter-ext-of-person)
exten => s,n,WaitExten(10)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'WaitExten' =-

[Synopsis]
Waits for an extension to be entered

[Description]
WaitExten([seconds][|options]): This application waits for the user to enter
a new extension for a specified number of seconds.
Note that the seconds can be passed with fractions of a second. For example,
'1.5' will ask the application to wait for 1.5 seconds.
Options:
m[(x)] - Provide music on hold to the caller while waiting for an extension.
Optionally, specify the class for music on hold within parenthesis.
See Also: Playback(application), Background(application).

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -11,3 +11,4 @@
Options:
m[(x)] - Provide music on hold to the caller while waiting for an extension.
Optionally, specify the class for music on hold within parenthesis.
+ See Also: Playback(application), Background(application).

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Waits for an extension to be entered

[Description]
- WaitExten([seconds][|options]): This application waits for the user to enter
+ WaitExten([seconds][,options]): This application waits for the user to enter
a new extension for a specified number of seconds.
Note that the seconds can be passed with fractions of a second. For example,
'1.5' will ask the application to wait for 1.5 seconds.

.Siehe auch
xref:applications-wait.adoc[Abschnitt C.188, „`Wait()`“]
