[[applications-sayunixtime]]
= `SayUnixTime()`

Zeitansage in einem spezifischen Format

[source]
----
SayUnixTime([Unixzeit][,Zeitzone[,Format]])
----

Sagt die angegebene Zeit unter Berücksichtigung der angegebenen
Zeitzone und des vorgegebenen Formats. Die Parameter sind:

`Unixzeit`:: Unix-Timestamp, also die Anzahl der Sekunden seit dem 1. Januar 1970, 0 Uhr GMT. Kann negative Werte annehmen. Standardwert ist die aktuelle Zeit.
`Zeitzone`:: Die Zeitzone. Eine Liste findet sich in `/usr/share/zoneinfo/`. Standardwert ist die Geräteeinstellung.
`Format`:: Das Format, in dem die Zeit gesprochen werden soll. Eine Liste von Formaten findet sich in `voicemail.conf`. Als Standardformat wird `ABdY 'digits/at' IMp` verwendet.

Liefert 0 zurück oder -1, wenn aufgelegt wird.

[source]
----
exten => 123,1,SayUnixTime(,,IMp)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SayUnixTime' =-

[Synopsis]
Says a specified time in a custom format

[Description]
SayUnixTime([unixtime][|[timezone][|format]])
unixtime: time, in seconds since Jan 1, 1970. May be negative.
defaults to now.
timezone: timezone, see /usr/share/zoneinfo for a list.
defaults to machine default.
format: a format the time is to be said in. See voicemail.conf.
defaults to "ABdY 'digits/at' IMp"

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,10 +4,10 @@
Says a specified time in a custom format

[Description]
- SayUnixTime([unixtime][|[timezone][|format]])
- unixtime: time, in seconds since Jan 1, 1970. May be negative.
+ SayUnixTime([unixtime][,[timezone][,format]])
+ unixtime - time, in seconds since Jan 1, 1970. May be negative.
defaults to now.
- timezone: timezone, see /usr/share/zoneinfo for a list.
+ timezone - timezone, see /usr/share/zoneinfo for a list.
defaults to machine default.
- format: a format the time is to be said in. See voicemail.conf.
+ format - a format the time is to be said in. See voicemail.conf.
defaults to "ABdY 'digits/at' IMp"
