[[applications-lookupblacklist]]
= `LookupBlacklist()`

Schlägt die Caller-ID-Nummer in der lokalen Blacklist-Datenbank in
der AstDB nach.

[source]
----
LookupBlacklist([Optionen])
----

Sucht die Caller-ID-Nummer (/-Name) des aktiven Channels in der
AstDB in der Familie `blacklist`. Wenn die Option j (jump)
angegeben ist, die Nummer gefunden wird und eine Priorität n+101 existiert,
geht die Ausführung bei dieser Priorität weiter. Wird auf dem Channel keine
Caller-ID empfangen, tut die Anwendung nichts.

Die Applikation setzt auch die Channel-Variable
`LOOKUPBLSTATUS` auf `FOUND` (gefunden) oder
`NOTFOUND` (nicht gefunden).

Um der Blacklist Einträge hinzuzufügen, geben Sie im CLI
+database put blacklist "_`Nummer`_" "1"+
ein bzw. +database del blacklist
"_`Nummer`_"+ zum Löschen oder `database
show blacklist` für eine Auflistung.

[source]
----
; Nummern aus der schwarzen Liste nicht zulassen,
; andernfalls die Nummer in der Variablen ${PETER} wählen:
exten => 123,1,Answer()
exten => 123,n,LookupBlacklist()
exten => 123,n,GotoIf($["${LOOKUPBLSTATUS}" = "FOUND"]?black,1)
exten => 123,n,Dial(${PETER},30)

exten => black,1,Playback(tt-allbusy)
exten => black,n,Hangup()
----

Die Applikation `LookupBlacklist()` könnte folgendermaßen
ersetzt werden:

[source]
----
exten => 123,1,Macro(blacklist,${CALLERID(num)})
exten => 123,n,Dial(IAX2/benutzer:passwort@beispiel.de/500)

[macro-blacklist]
; Aufruf: Macro(blacklist,${CALLERID(num)})
exten => s,1,GotoIf(${DB_EXISTS(blacklist/${ARG1})}?black)
exten => s,10(black),NoOp(Nummer ${ARG1} ist auf der Blacklist)
exten => s,n,Busy(5)
exten => s,n,Hangup()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'LookupBlacklist' =-

[Synopsis]
Look up Caller*ID name/number from blacklist database

[Description]
LookupBlacklist(options): Looks up the Caller*ID number on the active
channel in the Asterisk database (family 'blacklist').
The option string may contain the following character:
'j' -- jump to n+101 priority if the number/name is found in the blacklist
This application sets the following channel variable upon completion:
LOOKUPBLSTATUS The status of the Blacklist lookup as a text string, one of
FOUND | NOTFOUND
Example: exten => 1234,1,LookupBlacklist()

This application is deprecated and may be removed from a future release.
Please use the dialplan function BLACKLIST() instead.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -12,3 +12,6 @@
LOOKUPBLSTATUS The status of the Blacklist lookup as a text string, one of
FOUND | NOTFOUND
Example: exten => 1234,1,LookupBlacklist()
+
+ This application is deprecated and may be removed from a future release.
+ Please use the dialplan function BLACKLIST() instead.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:functions-blacklist.adoc[Abschnitt D.7, „`BLACKLIST()`“], xref:functions-db.adoc[Abschnitt D.17, „`DB()`“]
