[[applications-startmusiconhold]]
= `StartMusicOnHold()`

Startet das Abspielen von Wartemusik.

[source]
----
StartMusicOnHold([Klasse])
----

Spielt die durch _`Klasse`_ spezifizierte
Wartemusik, wie in `musiconhold.conf` konfiguriert. Wird
_`Klasse`_ nicht angegeben, wird die
Standardmusik-Klasse für diesen Channel verwendet.

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'StartMusicOnHold' =-

[Synopsis]
Play Music On Hold

[Description]
StartMusicOnHold(class): Starts playing music on hold, uses default music class for channel.
Starts playing music specified by class. If omitted, the default
music source for the channel will be used. Always returns 0.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,6 +4,7 @@
Play Music On Hold

[Description]
- StartMusicOnHold(class): Starts playing music on hold, uses default music class for channel.
+ StartMusicOnHold(class):
+ Starts playing music on hold, uses default music class for channel.
Starts playing music specified by class. If omitted, the default
music source for the channel will be used. Always returns 0.

.Siehe auch
xref:applications-stopmusiconhold.adoc[Abschnitt C.174, „`StopMusicOnHold()`“], xref:applications-musiconhold.adoc[Abschnitt C.104, „`MusicOnHold()`“]
