[[applications-waitfornoise]]
= `WaitForNoise()`

Wartet auf Geräusche.

[source]
----
WaitForNoise(Dauer[,Wiederholungen[,Timeout]])
----

Wartet auf `Dauer` Millisekunden Geräusche. Mit der
Angabe von `Wiederholungen` wird auf so viele Auftreten von
Geräuschen gewartet, sonst auf das einmalige Auftreten. Nach maximal
`Timeout` Sekunden wird abgebrochen, wenn dieser Parameter
angegeben ist.

[source]
----
; auf 3 Vorkommen von Geräuschen von jeweils 500 ms warten:
exten => 123,1,Answer()
exten => 123,n,WaitForNoise(500,3)
exten => 123,n,Playback(endlich-sagen-sie-mal-was)
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'WaitForNoise' =-

[Synopsis]
Waits for a specified amount of noise

[Description]
WaitForNoise(noiserequired[,iterations][,timeout])
Wait for Noise: The same as Wait for Silance but waits for noise that is above the threshold specified

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-waitforsilence.adoc[Abschnitt C.192, „`WaitForSilence()`“]
