[[applications-adsiprog]]
= `ADSIProg()`

Lädt ein ADSI-Skript in ein ADSI-fähiges Telefon.

[source]
----
ADSIProg([Script])
----

Programmiert ein ADSIfootnote:[Analog Display Services Interface]-Telefon mit einem vorhandenen Skript. Wird kein Skript
angegeben, wird das Default-Skript `asterisk.adsi`
verwendet. Die Pfadangabe zum `Script` versteht sich relativ zum
Asterisk-Konfigurationsverzeichnis. In der Regel ist das
`/etc/asterisk/`, es kann aber ebenso ein vollständiger
(absoluter) Pfad zu der Skript-Datei angegeben werden.

Benutzen Sie die `GetCPEID()`-Anwendung, um die CPE-ID
und weitere Informationen über das ADSI-fähige Telefon zu
erfahren.

[source]
----
; das ADSI-Telefon mit dem Skript telcordia-1.adsi programmieren:
exten => 123,1,ADSIProg(telcordia-1.adsi)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ADSIProg' =-

[Synopsis]
Load Asterisk ADSI Scripts into phone

[Description]
ADSIProg(script): This application programs an ADSI Phone with the given
script. If nothing is specified, the default script (asterisk.adsi) is used.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-getcpeid.adoc[Abschnitt C.60, „`GetCPEID()`“],
`adsi.conf`
