[[applications-parkedcall]]
= `ParkedCall()`

Beantwortet einen geparkten Anruf.

[source]
----
ParkedCall(Extension)
----

Verbindet den Anrufer mit dem Anruf, der auf dem durch
`Extension` identifizierten Parkplatz geparkt ist. Diese
Anwendung ist intern ständig registriert und muss daher dem Wählplan nicht
explizit hinzugefügt werden. Sie sollten jedoch den
`parkedcalls`-Context einbinden.

[source]
----
; den Anruf auf "Parkplatz" 701 wiederaufnehmen:
exten => 123,1,Answer()
exten => 123,n,ParkedCall(701)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ParkedCall' =-

[Synopsis]
Answer a parked call

[Description]
ParkedCall(exten):Used to connect to a parked call. This application is always
registered internally and does not need to be explicitly added
into the dialplan, although you should include the 'parkedcalls'
context.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,8 @@
Answer a parked call

[Description]
- ParkedCall(exten):Used to connect to a parked call. This application is always
+ ParkedCall(exten): Used to connect to a parked call. This application is always
registered internally and does not need to be explicitly added
into the dialplan, although you should include the 'parkedcalls'
- context.
+ context. If no extension is provided, then the first available
+ parked call will be acquired.

.Siehe auch
xref:applications-park.adoc[Abschnitt C.110, „`Park()`“], xref:applications-parkandannounce.adoc[Abschnitt C.111, „`ParkAndAnnounce()`“]
