[[applications-meetme]]
= `MeetMe()`

Nimmt den Anrufer in eine MeetMe-Konferenz auf.

[source]
----
MeetMe([KonferenzNr][,Optionen[,PIN]])
----

Verbindet den Anrufer auf dem aktuellen Channel zu einer
MeetMe-Konferenz, angegeben durch den Parameter `KonferenzNr`.
Ohne Angabe der Konferenznummer wird der Teilnehmer zur Eingabe derselben
aufgefordert.

Wird als `PIN`-Parameter die PIN-Nummer der Konferenz
(statisch in `meetme.conf` oder dynamisch vom Ersteller
festgelegt) übergeben, so wird der Anrufer direkt in die Konferenz geleitet.
Ansonsten muss der Anrufer die PIN eingeben, um beitreten zu
können.

[IMPORTANT]
====
Damit MeetMe-Konferenzen funktionieren, muss ein passendes
Zaptel-Interface installiert sein. Alternativ kann auch der
`ztdummy`-Treiber für Timing-Zwecke verwendet werden.
====

Die `Optionen` können sich aus folgenden Zeichen
zusammensetzen:

`a`:: Aktiviert den Administrator-Modus.
`A`:: Markiert den eintretenden User als besonderen Teilnehmer (siehe `w` und `x`).
`b`:: Startet das in `${MEETME_AGI_BACKGROUND}` spezifizierte AGI-Skript, standardmäßig `conf-background.agi`. (Funktioniert nur dann korrekt, wenn alle Kanäle in einer Konferenz Zap-Kanäle sind.) Das Skript erhält alle DTMF-Tastenkürzel, wodurch die Kombination mit Optionen, die auch das Abfangen von Tasten zur Folge haben (`p`), nicht möglich ist.
`c`:: Kündigt beim Betreten des Konferenzraums die Zahl der Teilnehmer an.
`d`:: Legt dynamisch einen neuen Konferenzraum an.
`D`:: Legt dynamisch einen neuen Konferenzraum an, wobei die Festlegung der PIN verlangt wird. (Wenn der User keine PIN will, muss er `#` drücken.)
`e`:: Wählt eine leere Konferenz aus.
`E`:: Wählt eine leere Konferenz aus, die keine PIN verlangt.
`i`:: Kündigt das Betreten oder Verlassen des Konferenzraums durch einen Teilnehmer an (nur mit Zap-Kanälen).
`m`:: Aktiviert den Monitor-Modus (nur hören, nicht sprechen).
`M`:: Aktiviert Wartemusik (Music on Hold), wenn nur ein Teilnehmer in der Konferenz ist.
`p`:: Ermöglicht es dem Teilnehmer, die Konferenz durch Drücken von `#` zu verlassen.
`P`:: Fragt immer nach der PIN, auch wenn sie hier im Befehl angegeben ist.
`q`:: Aktiviert den ruhigen Modus (spielt keine Eintritts-/Austrittsklänge ab).
`r`:: Zeichnet eine Konferenz auf. Datei: `${MEETME_RECORDINGFILE}`, Format: `${MEETME_RECORDINGFORMAT}`. Der Standard-Dateiname lautet +meetme-conf-rec-${_`KonferenzNr`_}-${_`UniqueID`_}+, wobei `UniqueID` eine einmalige ID ist. Das Standardformat ist `wav`. (Funktioniert nur mit Zap-Kanälen.)
`s`:: Wechselt beim Drücken von `*` in das (Teilnehmer- oder Administrator-)Menü.
`t`:: Aktiviert den Nur-Sprechen-Modus (nur reden, nicht hören).
`T`:: Aktiviert die Sprecher-Erkennung (wird zum Manager-Interface gesendet und in der MeetMe-Liste im CLI angezeigt).
`v`:: Aktiviert den Video-Modus (bisher ohne Funktion).
`w`:: Wartet, bis ein gekennzeichneter Teilnehmer (siehe `A`) zur Konferenz hinzukommt. Bis dahin hören alle Teilnehmer Wartemusik.
`x`:: Schließt die Konferenz, wenn sie vom letzten gekennzeichneten Teilnehmer (siehe `A`) verlassen wird.
`X`:: Ermöglicht es dem Teilnehmer, die Konferenz durch Eingabe einer einziffrigen Extension im Context `${MEETME_EXIT_CONTEXT}` zu verlassen, oder durch Eingabe der Nummer einer Extension des aktuellen Contexts, falls diese Variable nicht definiert ist.

Die Option `X` funktioniert nicht zusammen mit
`p` oder `s`.

Verwenden Sie `e` (oder `E`) zusammen mit
`d` (oder `D`), um dynamisch einen neuen Konferenzraum
zu eröffnen, wobei Asterisk automatisch die `KonferenzNr`
festlegt. Sie müssen dann natürlich den anderen Teilnehmern die Nummer
mitteilen oder eine entsprechende Dialplan-Logik einsetzen.

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'MeetMe' =-

[Synopsis]
MeetMe conference bridge

[Description]
MeetMe([confno][,[options][,pin]]): Enters the user into a specified MeetMe
conference. If the conference number is omitted, the user will be prompted
to enter one. User can exit the conference by hangup, or if the 'p' option
is specified, by pressing '#'.
Please note: The Zaptel kernel modules and at least one hardware driver (or ztdummy)
must be present for conferencing to operate properly. In addition, the chan_zap
channel driver must be loaded for the 'i' and 'r' options to operate at all.

The option string may contain zero or more of the following characters:
'a' -- set admin mode
'A' -- set marked mode
'b' -- run AGI script specified in ${MEETME_AGI_BACKGROUND}
Default: conf-background.agi (Note: This does not work with
non-Zap channels in the same conference)
'c' -- announce user(s) count on joining a conference
'd' -- dynamically add conference
'D' -- dynamically add conference, prompting for a PIN
'e' -- select an empty conference
'E' -- select an empty pinless conference
'F' -- Pass DTMF through the conference.
'i' -- announce user join/leave with review
'I' -- announce user join/leave without review
'l' -- set listen only mode (Listen only, no talking)
'm' -- set initially muted
'M' -- enable music on hold when the conference has a single caller
'o' -- set talker optimization - treats talkers who aren't speaking as
being muted, meaning (a) No encode is done on transmission and
(b) Received audio that is not registered as talking is omitted
causing no buildup in background noise. Note that this option
will be removed in 1.6 and enabled by default.
'p' -- allow user to exit the conference by pressing '#'
'P' -- always prompt for the pin even if it is specified
'q' -- quiet mode (don't play enter/leave sounds)
'r' -- Record conference (records as ${MEETME_RECORDINGFILE}
using format ${MEETME_RECORDINGFORMAT}). Default filename is
meetme-conf-rec-${CONFNO}-${UNIQUEID} and the default format is
wav.
's' -- Present menu (user or admin) when '*' is received ('send' to menu)
't' -- set talk only mode. (Talk only, no listening)
'T' -- set talker detection (sent to manager interface and meetme list)
'w[(<secs>)]'
-- wait until the marked user enters the conference
'x' -- close the conference when last marked user exits
'X' -- allow user to exit the conference by entering a valid single
digit extension ${MEETME_EXIT_CONTEXT} or the current context
if that variable is not defined.
'1' -- do not play message when first person enters

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -4,10 +4,10 @@
MeetMe conference bridge

[Description]
- MeetMe([confno][,[options][,pin]]): Enters the user into a specified MeetMe conference.
- If the conference number is omitted, the user will be prompted to enter
- one.
- User can exit the conference by hangup, or if the 'p' option is specified, by pressing '#'.
+ MeetMe([confno][,[options][,pin]]): Enters the user into a specified MeetMe
+ conference. If the conference number is omitted, the user will be prompted
+ to enter one. User can exit the conference by hangup, or if the 'p' option
+ is specified, by pressing '#'.
Please note: The Zaptel kernel modules and at least one hardware driver (or ztdummy)
must be present for conferencing to operate properly. In addition, the chan_zap
channel driver must be loaded for the 'i' and 'r' options to operate at all.
@@ -16,22 +16,31 @@
'a' -- set admin mode
'A' -- set marked mode
'b' -- run AGI script specified in ${MEETME_AGI_BACKGROUND}
- Default: conf-background.agi
- (Note: This does not work with non-Zap channels in the same conference)
+ Default: conf-background.agi (Note: This does not work with
+ non-Zap channels in the same conference)
'c' -- announce user(s) count on joining a conference
'd' -- dynamically add conference
'D' -- dynamically add conference, prompting for a PIN
'e' -- select an empty conference
'E' -- select an empty pinless conference
- 'i' -- announce user join/leave
- 'm' -- set monitor only mode (Listen only, no talking)
+ 'F' -- Pass DTMF through the conference.
+ 'i' -- announce user join/leave with review
+ 'I' -- announce user join/leave without review
+ 'l' -- set listen only mode (Listen only, no talking)
+ 'm' -- set initially muted
'M' -- enable music on hold when the conference has a single caller
+ 'o' -- set talker optimization - treats talkers who aren't speaking as
+ being muted, meaning (a) No encode is done on transmission and
+ (b) Received audio that is not registered as talking is omitted
+ causing no buildup in background noise. Note that this option
+ will be removed in 1.6 and enabled by default.
'p' -- allow user to exit the conference by pressing '#'
'P' -- always prompt for the pin even if it is specified
'q' -- quiet mode (don't play enter/leave sounds)
'r' -- Record conference (records as ${MEETME_RECORDINGFILE}
using format ${MEETME_RECORDINGFORMAT}). Default filename is
- meetme-conf-rec-${CONFNO}-${UNIQUEID} and the default format is wav.
+ meetme-conf-rec-${CONFNO}-${UNIQUEID} and the default format is
+ wav.
's' -- Present menu (user or admin) when '*' is received ('send' to menu)
't' -- set talk only mode. (Talk only, no listening)
'T' -- set talker detection (sent to manager interface and meetme list)
@@ -41,3 +50,4 @@
'X' -- allow user to exit the conference by entering a valid single
digit extension ${MEETME_EXIT_CONTEXT} or the current context
if that variable is not defined.
+ '1' -- do not play message when first person enters

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -8,8 +8,8 @@
conference. If the conference number is omitted, the user will be prompted
to enter one. User can exit the conference by hangup, or if the 'p' option
is specified, by pressing '#'.
- Please note: The Zaptel kernel modules and at least one hardware driver (or ztdummy)
- must be present for conferencing to operate properly. In addition, the chan_zap
+ Please note: The DAHDI kernel modules and at least one hardware driver (or dahdi_dummy)
+ must be present for conferencing to operate properly. In addition, the chan_dahdi
channel driver must be loaded for the 'i' and 'r' options to operate at all.

The option string may contain zero or more of the following characters:
@@ -17,8 +17,9 @@
'A' -- set marked mode
'b' -- run AGI script specified in ${MEETME_AGI_BACKGROUND}
Default: conf-background.agi (Note: This does not work with
- non-Zap channels in the same conference)
+ non-DAHDI channels in the same conference)
'c' -- announce user(s) count on joining a conference
+ 'C' -- continue in dialplan when kicked out of conference
'd' -- dynamically add conference
'D' -- dynamically add conference, prompting for a PIN
'e' -- select an empty conference
@@ -28,13 +29,19 @@
'I' -- announce user join/leave without review
'l' -- set listen only mode (Listen only, no talking)
'm' -- set initially muted
- 'M' -- enable music on hold when the conference has a single caller
+ 'M[(<class>)]'
+ -- enable music on hold when the conference has a single caller.
+ Optionally, specify a musiconhold class to use. If one is not
+ provided, it will use the channel's currently set music class,
+ or "default".
'o' -- set talker optimization - treats talkers who aren't speaking as
being muted, meaning (a) No encode is done on transmission and
(b) Received audio that is not registered as talking is omitted
- causing no buildup in background noise. Note that this option
- will be removed in 1.6 and enabled by default.
- 'p' -- allow user to exit the conference by pressing '#'
+ causing no buildup in background noise
+ 'p[(<keys>)]'
+ -- allow user to exit the conference by pressing '#' (default)
+ or any of the defined keys. If keys contain '*' this will override
+ option 's'. The key used is set to channel variable MEETME_EXIT_KEY.
'P' -- always prompt for the pin even if it is specified
'q' -- quiet mode (don't play enter/leave sounds)
'r' -- Record conference (records as ${MEETME_RECORDINGFILE}
@@ -51,3 +58,10 @@
digit extension ${MEETME_EXIT_CONTEXT} or the current context
if that variable is not defined.
'1' -- do not play message when first person enters
+ 'S(x)' -- Kick the user 'x' seconds *after* he entered into the conference.
+ 'L(x[:y][:z])' - Limit the conference to 'x' ms. Play a warning when 'y' ms are
+ left. Repeat the warning every 'z' ms. The following special
+ variables can be used with this option:
+ * CONF_LIMIT_TIMEOUT_FILE File to play when time is up.
+ * CONF_LIMIT_WARNING_FILE File to play as warning if 'y' is defined.
+ The default is to say the time remaining.

.Siehe auch
xref:applications-meetmecount.adoc[Abschnitt C.92, „`MeetMeCount()`“], xref:applications-meetmeadmin.adoc[Abschnitt C.90, „`MeetMeAdmin()`“], xref:applications-meetmechanneladmin.adoc[Abschnitt C.91, „`MeetMeChannelAdmin()`“], xref:functions-meetme_info.adoc[Abschnitt D.63, „`MEETME_INFO()`“]
