[[applications-dundilookup]]
= `DUNDiLookup()`

Schlägt eine Telefonnummer mit DUNDi nach.

[source]
----
DUNDiLookup(Nummer[|DUNDi-Context[|Optionen]])
----

[IMPORTANT]
====
`DUNDiLookup()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `DUNDILOOKUP()`
(xref:functions-dundilookup.adoc[Abschnitt D.24, „`DUNDILOOKUP()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'DUNDiLookup' =-

[Synopsis]
Look up a number with DUNDi

[Description]
DUNDiLookup(number[|context[|options]])
Looks up a given number in the global context specified or in
the reserved 'e164' context if not specified. Returns -1 if the channel
is hungup during the lookup or 0 otherwise. On completion, the variable
${DUNDTECH} and ${DUNDDEST} will contain the technology and destination
of the appropriate technology and destination to access the number. If no
answer was found, and the priority n + 101 exists, execution will continue
at that location. Note that this will only occur if the global priority
jumping option is enabled in extensions.conf. If the 'b' option is specified,
the internal DUNDi cache will by bypassed.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-dundilookup.adoc[Abschnitt D.24, „`DUNDILOOKUP()`“]
