[[applications-waitmusiconhold]]
= `WaitMusicOnHold()`

Wartet für eine in Sekunden vorgegebene Dauer, wobei Wartemusik
abgespielt wird.

[source]
----
WaitMusicOnHold(Dauer)
----

Spielt die in Sekunden angegebene `Dauer`
Wartemusik. Ist keine Wartemusik vorhanden, wird die Verzögerung dennoch
ausgeführt, jedoch ohne Musik.

Liefert nach Abschluss 0, oder -1, falls aufgelegt wurde.

[source]
----
; 5 Minuten Wartemusik:
exten => 123,1,Answer()
exten => 123,n,WaitMusicOnHold(300)
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'WaitMusicOnHold' =-

[Synopsis]
Wait, playing Music On Hold

[Description]
WaitMusicOnHold(delay): Plays hold music specified number of seconds. Returns 0 when
done, or -1 on hangup. If no hold music is available, the delay will
still occur with no sound.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,6 +4,12 @@
Wait, playing Music On Hold

[Description]
- WaitMusicOnHold(delay): Plays hold music specified number of seconds. Returns 0 when
+ WaitMusicOnHold(delay):
+
+ !!! DEPRECATED. Use MusicOnHold instead !!!
+
+ Plays hold music specified number of seconds. Returns 0 when
done, or -1 on hangup. If no hold music is available, the delay will
still occur with no sound.
+
+ !!! DEPRECATED. Use MusicOnHold instead !!!

.Siehe auch
xref:applications-musiconhold.adoc[Abschnitt C.104, „`MusicOnHold()`“],
`musiconhold.conf`
