[[applications-followme]]
= `FollowMe()`

Follow-Me/Find-Me-Funktionalität.

[source]
----
FollowMe(FollowMeID,Optionen)
----

Bitte lesen Sie die Konfigurationsdatei
`followme.conf`.

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'FollowMe' =-

[Synopsis]
Find-Me/Follow-Me application

[Description]
FollowMe(followmeid|options):
This application performs Find-Me/Follow-Me functionality for the caller
as defined in the profile matching the <followmeid> parameter in
followme.conf. If the specified <followmeid> profile doesn't exist in
followme.conf, execution will be returned to the dialplan and call
execution will continue at the next priority.

Options:
s - Playback the incoming status message prior to starting the follow-me step(s)
a - Record the caller's name so it can be announced to the callee on each step
n - Playback the unreachable status message if we've run out of steps to reach the
or the callee has elected not to be reachable.
Returns -1 on hangup

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Find-Me/Follow-Me application

[Description]
- FollowMe(followmeid|options):
+ FollowMe(followmeid[,options]):
This application performs Find-Me/Follow-Me functionality for the caller
as defined in the profile matching the <followmeid> parameter in
followme.conf. If the specified <followmeid> profile doesn't exist in
