[[applications-setcallerpres]]
= `SetCallerPres()`

Setzt Caller-ID-Anzeige.

[source]
----
SetCallerPres(Wert)
----

Setzt die Caller-ID-Darstellungsflags („presentation
indicator“ und „screening indicator“) zur
Rufnummernanzeige bzw. -unterdrückung (CLIR) auf einer ITU-Q.931footnote:[http://www.itu.int/rec/T-REC-Q.931/]-PRI-Verbindung. Darin ist die „presentation“
enthalten, also die Information, ob beim angerufenen Teilnehmer die eigene
Nummer angezeigt werden soll, und das „screening“, also die
Information, ob die gesetzte Rufnummer von verlässlicher Quelle verifiziert
wurde.

Gültige Werte sind:

`allowed_not_screened`:: Anzeige erlaubt. Die Nummer wurde vom Teilnehmer gesetzt, nicht überprüft.
`allowed_passed_screen`:: Anzeige erlaubt. Die Nummer wurde vom Teilnehmer gesetzt, Überprüfung erfolgreich.
`allowed_failed_screen`:: Anzeige erlaubt. Die Nummer wurde vom Teilnehmer gesetzt, Überprüfung fehlgeschlagen.
`allowed`:: Anzeige erlaubt. Die Nummer wurde vom Netz-Provider gesetzt.
`prohib_not_screened`:: Anzeige unterdrückt. Die Nummer wurde vom Teilnehmer gesetzt, nicht überprüft.
`prohib_passed_screen`:: Anzeige unterdrückt. Die Nummer wurde vom Teilnehmer gesetzt, Überprüfung erfolgreich.
`prohib_failed_screen`:: Anzeige unterdrückt. Die Nummer wurde vom Teilnehmer gesetzt, Überprüfung fehlgeschlagen.
`prohib`:: Anzeige unterdrückt. Die Nummer wurde vom Netz-Provider gesetzt.
`unavailable`:: Die Nummer ist nicht verfügbar.

Liefert stets 0 zurück.

[source]
----
exten => 123,1,SetCallerPres(prohib_not_screened)
exten => 123,n,Dial(Zap/4/1234567)
----

[NOTE]
====
Damit der eingestellte Wert beim Rauswählen über ISDN beachtet wird,
muss `usecallingpres=yes` in der
`zapata.conf` gesetzt sein.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SetCallerPres' =-

[Synopsis]
Set CallerID Presentation

[Description]
SetCallerPres(presentation): Set Caller*ID presentation on a call.
Valid presentations are:

allowed_not_screened : Presentation Allowed, Not Screened
allowed_passed_screen : Presentation Allowed, Passed Screen
allowed_failed_screen : Presentation Allowed, Failed Screen
allowed : Presentation Allowed, Network Number
prohib_not_screened : Presentation Prohibited, Not Screened
prohib_passed_screen : Presentation Prohibited, Passed Screen
prohib_failed_screen : Presentation Prohibited, Failed Screen
prohib : Presentation Prohibited, Network Number
unavailable : Number Unavailable

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:functions-callerpres.adoc[Abschnitt D.9, „`CALLERPRES()`“]
