[[applications-tryexec]]
= `TryExec()`

Versucht die Ausführung einer Dialplan-Applikation.

[source]
----
TryExec(Applikation(Argumente))
----

Versucht, wie `Exec()`, eine Applikation auszuführen,
aber ohne den Anruf abzubrechen, wenn die Applikation nicht gefunden wird
oder einen Fehler zurückgibt. Stattdessen wird die Variable
`TRYSTATUS` auf einen der folgenden Werte gesetzt:

`SUCCESS`:: Die Applikation hat 0 zurückgegeben.
`FAILED`:: Die Applikation hat einen Fehler zurückgegeben (Wert ungleich 0).
`NOAPP`:: Die Applikation wurde nicht gefunden.

Für weitere Informationen siehe xref:applications-exec.adoc[Abschnitt C.50, „`Exec()`“].

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'TryExec' =-

[Synopsis]
Executes dialplan application, always returning

[Description]
Usage: TryExec(appname(arguments))
Allows an arbitrary application to be invoked even when not
hardcoded into the dialplan. To invoke external applications
see the application System. Always returns to the dialplan.
The channel variable TRYSTATUS will be set to:
SUCCESS if the application returned zero
FAILED if the application returned non-zero
NOAPP if the application was not found or was not specified

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,11 +4,11 @@
Executes dialplan application, always returning

[Description]
- Usage: TryExec(appname(arguments))
- Allows an arbitrary application to be invoked even when not
+ TryExec(appname(arguments)):
+ Allows an arbitrary application to be invoked even when not
hardcoded into the dialplan. To invoke external applications
see the application System. Always returns to the dialplan.
- The channel variable TRYSTATUS will be set to:
+ The channel variable TRYSTATUS will be set to one of:
SUCCESS if the application returned zero
FAILED if the application returned non-zero
NOAPP if the application was not found or was not specified

.Siehe auch
xref:applications-exec.adoc[Abschnitt C.50, „`Exec()`“], xref:applications-execif.adoc[Abschnitt C.51, „`ExecIf()`“], xref:applications-trysystem.adoc[Abschnitt C.179, „`TrySystem()`“]
