[[applications-jabbersend]]
= `JabberSend()`

Sendet eine Nachricht per Jabber.

[source]
----
JabberSend(absender,empfänger,nachricht)
----

Sendet die Text-Nachricht _`nachricht`_ per
Jabber (XMPP, Google Talk) von einem in der `jabber.conf`
definierten _`absender`_ an den Jabber-Account
_`empfänger`_.

[source]
----
exten => 123,1,JabberSend(asterisk,philipp@example.com,Eingehender Anruf)
exten => 123,n,Dial(SIP/philipp)
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'JabberSend' =-

[Synopsis]
JabberSend(jabber,screenname,message)

[Description]
JabberSend(Jabber,ScreenName,Message)
Jabber - Client or transport Asterisk uses to connect to Jabber
ScreenName - User Name to message.
Message - Message to be sent to the buddy

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -6,5 +6,5 @@
[Description]
JabberSend(Jabber,ScreenName,Message)
Jabber - Client or transport Asterisk uses to connect to Jabber
- ScreenName - User Name to message.
- Message - Message to be sent to the buddy
+ ScreenName - XMPP/Jabber JID (Name) of recipient
+ Message - Message to be sent to the budd (UTF8)y

.Siehe auch
xref:applications-jabberstatus.adoc[Abschnitt C.76, „`JabberStatus()`“], xref:functions-jabber_status.adoc[Abschnitt D.54, „`JABBER_STATUS()`“],
`jabber.conf`
