[[applications-unpausemonitor]]
= `UnpauseMonitor()`

Hebt das vorübergehende Unterbrechen der Aufzeichnung
auf.

[source]
----
UnpauseMonitor()
----

Hebt das vorübergehende Unterbrechen des Mitschnitts eines Kanals
wieder auf, das mit `PauseMonitor()` erzwungen wurde.

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'UnpauseMonitor' =-

[Synopsis]
Unpause monitoring of a channel

[Description]
UnpauseMonitor
Unpauses monitoring of a channel on which monitoring had
previously been paused with PauseMonitor.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,6 +4,6 @@
Unpause monitoring of a channel

[Description]
- UnpauseMonitor
+ UnpauseMonitor():
Unpauses monitoring of a channel on which monitoring had
previously been paused with PauseMonitor.

.Siehe auch
xref:applications-monitor.adoc[Abschnitt C.100, „`Monitor()`“], xref:applications-pausemonitor.adoc[Abschnitt C.113, „`PauseMonitor()`“]
