[[applications-setglobalvar]]
= `SetGlobalVar()`

Setzt den Wert einer globalen Variable.

[source]
----
SetGlobalVar(Variable=Wert)
----

Setzt eine globale Variable. Falls die Variable nicht existiert,
wird sie gleichzeitig definiert.

[IMPORTANT]
====
`SetGlobalVar()` ist ab Asterisk 1.6 nicht mehr
vorhanden und sollte auch in 1.4 nicht mehr genutzt werden. Eine globale
Variable setzt man ab da mittels `Set()` (xref:applications-set.adoc[Abschnitt C.149, „`Set()`“]) in Verbindung mit
`GLOBAL()` (xref:functions-global.adoc[Abschnitt D.38, „`GLOBAL()`“]):

[source]
----
Set(GLOBAL(Variable)=Wert)
----
Bitte verwenden Sie also in Asterisk 1.2 `Set()` mit der
Option `g` und ab Asterisk 1.4 `GLOBAL()`.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SetGlobalVar' =-

[Synopsis]
Set a global variable to a given value

[Description]
SetGlobalVar(variable=value): This application sets a given global variable to
the specified value.

This application is deprecated in favor of Set(GLOBAL(var)=value)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -6,3 +6,6 @@
[Description]
SetGlobalVar(variable=value): This application sets a given global variable to
the specified value.
+
+
+ This application is deprecated in favor of Set(GLOBAL(var)=value)

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:applications-set.adoc[Abschnitt C.149, „`Set()`“], xref:functions-global.adoc[Abschnitt D.38, „`GLOBAL()`“]
