[[applications-saynumber]]
= `SayNumber()`

Spricht die angegebene Zahl.

[source]
----
SayNumber(Nummer[,Genus])
----

Spricht die angegebene Zahl unter Verwendung der aktuellen
Spracheinstellung für den Channel. Die Sprache kann mit der Funktion
`LANGUAGE()` geändert werden.

Bisher werden Ganzzahlen von 1 bis 99.999.999 in den folgenden
Sprachen syntaktisch unterstützt:

`da`:: Dänisch
`de`:: Deutsch
`en`:: Englisch
`es`:: Spanisch
`fr`:: Französisch
`it`:: Italienisch
`nl`:: Niederländisch
`no`:: Norwegisch
`pl`:: Polnisch
`pt`:: Portugiesisch
`se`:: Schwedisch
`tw`:: Taiwanesisch

Kennt die aktuelle Sprache Geschlechter (Genus), kann der Parameter
`Genus` übergeben werden und das Genus der zu sprechenden Zahl zu
ändern.

Benutzen Sie bei europäischen Sprachen wie Deutsch, Französisch,
Spanisch, Portugiesisch das Genus `f` für Femininum,
`m` für Maskulinum und `n` für Neutrum.

Benutzen Sie bei nordischen Sprachen wie Dänisch, Schwedisch oder
Norwegisch das `Genus` `c` für Commune (/Utrum,
belebt) und `n` für Neutrum (/Ne-utrum, unbelebt).

Benutzen Sie für Aufzählungen im deutschen Plural das
`Genus` `p`.

Damit diese Anwendung mit anderen Sprachen als Englisch
funktioniert, müssen die entsprechenden Audiodateien für die jeweilige
gewünschte Sprache in `/var/lib/asterisk/sounds/digits/`
(bzw. Unterverzeichnissen wie `de/`) vorhanden
sein.

[source]
----
; in Englisch sprechen:
exten => 123,1,Set(LANGUAGE=en)
exten => 123,n,SayNumber(1234)
; "one - thousand - two - hundred - and - thirty - four"

; in Deutsch sprechen:
exten => 123,1,Set(LANGUAGE=de)
exten => 123,n,SayNumber(1234)
; "ein - Tausend - zwei - Hundert - und - vier - und - dreißig"
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SayNumber' =-

[Synopsis]
Say Number

[Description]
SayNumber(digits[,gender]): This application will play the sounds that
correspond to the given number. Optionally, a gender may be specified.
This will use the language that is currently set for the channel. See the
LANGUAGE function for more information on setting the language for the channel.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-sayalpha.adoc[Abschnitt C.139, „`SayAlpha()`“], xref:applications-saydigits.adoc[Abschnitt C.140, „`SayDigits()`“], xref:applications-sayphonetic.adoc[Abschnitt C.142, „`SayPhonetic()`“]
