[[applications-noop]]
= `NoOp()`

Tut nichts (no operation).

[source]
----
NoOp(Text)
----

Diese Anwendung tut nichts – dem Namen nach. Mit
`NoOp()` kann man aber Text auf dem Asterisk-CLI ausgeben: eine
zum Debugging sehr nützliche Eigenschaft.

Sie müssen den Text nicht in Anführungszeichen betten. Stehen
Anführungszeichen innerhalb der Klammern, werden diese auf der Konsole
ausgegeben.

[IMPORTANT]
====
Die Ausgabe von `NoOp()` auf dem CLI erfolgt erst ab dem
Verbose-Level 3. Dieser kann im CLI mit `set verbose 3`
gesetzt werden.
====

[source]
----
exten => 123,1,NoOp(Caller-ID: ${CALLERID})
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'NoOp' =-

[Synopsis]
Do Nothing

[Description]
NoOp(): This applicatiion does nothing. However, it is useful for debugging
purposes. Any text that is provided as arguments to this application can be
viewed at the Asterisk CLI. This method can be used to see the evaluations of
variables or functions without having any effect.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,10 +1,11 @@
-= Info about application 'NoOp' =-

[Synopsis]
- Do Nothing
+ Do Nothing (No Operation)

[Description]
- NoOp(): This applicatiion does nothing. However, it is useful for debugging
+ NoOp(): This application does nothing. However, it is useful for debugging
purposes. Any text that is provided as arguments to this application can be
viewed at the Asterisk CLI. This method can be used to see the evaluations of
- variables or functions without having any effect.
+ variables or functions without having any effect. Alternatively, see the
+ Verbose() application for finer grain control of output at custom verbose levels.

.Siehe auch
xref:applications-dumpchan.adoc[Abschnitt C.43, „`DumpChan()`“], xref:applications-log.adoc[Abschnitt C.78, „`Log()`“], xref:applications-verbose.adoc[Abschnitt C.184, „`Verbose()`“]
