[[applications-txtcidname]]
= `TXTCIDName()`

Schlägt den Namen des Anrufers zu einer Nummer mittels DNS (im
TXT-Record) nach.

[source]
----
TXTCIDName(param)
----

[IMPORTANT]
====
`TXTCIDName()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `TXTCIDNAME()`
(xref:functions-txtcidname.adoc[Abschnitt D.105, „`TXTCIDNAME()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'TXTCIDName' =-

[Synopsis]
Lookup caller name from TXT record

[Description]
TXTCIDName(<CallerIDNumber>[|options]): Looks up a Caller Name via DNS and sets
the variable 'TXTCIDNAME'. TXTCIDName will either be blank
or return the value found in the TXT record in DNS.
The option string may contain the following character:
'j' -- jump to n+101 priority if the lookup fails
This application sets the following channel variable upon completion:
TXTCIDNAMESTATUS The status of the lookup as a text string, one of
SUCCESS | FAILED

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-txtcidname.adoc[Abschnitt D.105, „`TXTCIDNAME()`“]
