[[applications-minivmnotify]]
= `MinivmNotify()`

Sendet E-Mail-Benachrichtigung für
Mini-VoiceMail-Nachrichten.

[source]
----
MinivmNotify(benutzer@domain,template)
----

Benachrichtigt einen Benutzer des Mini-VoiceMail-Systems (xref:minivm.adoc[Abschnitt 13.7, „Mini-VoiceMail (MiniVM)“]) per E-Mail über neue Nachrichten.

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'MinivmNotify' =-

[Synopsis]
Notify voicemail owner about new messages.

[Description]
MinivmNotify(username@domain[,template]):
This application is part of the Mini-Voicemail system, configured in minivm.conf.
MiniVMnotify forwards messages about new voicemail to e-mail and pager.
If there's no user account for that address, a temporary account will
be used with default options (set in minivm.conf).
The recorded file name and path will be read from MVM_FILENAME and the
duration of the message will be accessed from MVM_DURATION (set by MinivmRecord() )
If the channel variable MVM_COUNTER is set, this will be used in the
message file name and available in the template for the message.
If not template is given, the default email template will be used to send email and
default pager template to send paging message (if the user account is configured with
a paging address.

Result is given in channel variable MINIVM_NOTIFY_STATUS
The possible values are: SUCCESS | FAILED

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-minivmaccmess.adoc[Abschnitt C.94, „`MinivmAccMess()`“], xref:applications-minivmdelete.adoc[Abschnitt C.95, „`MinivmDelete()`“], xref:applications-minivmgreet.adoc[Abschnitt C.96, „`MinivmGreet()`“], xref:applications-minivmrecord.adoc[Abschnitt C.98, „`MinivmRecord()`“], xref:functions-minivmaccount.adoc[Abschnitt D.64, „`MINIVMACCOUNT()`“], xref:functions-minivmcounter.adoc[Abschnitt D.65, „`MINIVMCOUNTER()`“]
