[[applications-dbdel]]
= `DBdel()`

Löscht einen Schlüssel aus der AstDB.

[source]
----
DBdel(Familie/Schlüssel)
----

Löscht den durch `key` spezifizierten Schlüssel aus
der Schlüsselfamilie `Familie` aus der AstDB.

Liefert stets 0 zurück.

[source]
----
exten => 123,1,Set(DB(test/name)=Peter)    ; in AstDB speichern
exten => 123,n,Set(name=${DB(test/name)})  ; abfragen
exten => 123,n,DBdel(test/name)            ; löschen
----

[IMPORTANT]
====
Die Applikation `DBdel()` ist seit 1.4
„deprecated“ und wird durch die Funktion
`DB_DELETE()` ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'DBdel' =-

[Synopsis]
Delete a key from the database

[Description]
DBdel(family/key): This application will delete a key from the Asterisk
database.
This application has been DEPRECATED in favor of the DB_DELETE function.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -6,3 +6,4 @@
[Description]
DBdel(family/key): This application will delete a key from the Asterisk
database.
+ This application has been DEPRECATED in favor of the DB_DELETE function.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-dbdeltree.adoc[Abschnitt C.34, „`DBdeltree()`“], xref:functions-db.adoc[Abschnitt D.17, „`DB()`“], xref:functions-db_delete.adoc[Abschnitt D.18, „`DB_DELETE()`“]
