[[applications-senddtmf]]
= `SendDTMF()`

Sendet beliebige DTMF-Ziffern zu dem Channel.

[source]
----
SendDTMF(Ziffern[,Timeout_ms])
----

Sendet die angegebenen DTMF-Ziffern auf einem Channel. Gültige
DTMF-Symbole sind `0`-`9`, `*`,
`#` und `A`-`D`. Sie können auch den
Buchstaben `w` als eine Ziffer verwenden, er steht für eine
Wartezeit von 500 Millisekunden. Der Parameter `Timeout_ms`
bezeichnet die Zeitdauer in Millisekunden zwischen den Ziffern. Falls nicht
angegeben, wird ein Wert von 250 Millisekunden für `Timeout_ms`
angenommen.

Liefert bei Erfolg 0 zurück oder -1, wenn aufgelegt wird.

[source]
----
exten => 123,1,SendDTMF(123w456w789,200)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SendDTMF' =-

[Synopsis]
Sends arbitrary DTMF digits

[Description]
SendDTMF(digits[|timeout_ms]): Sends DTMF digits on a channel.
Accepted digits: 0-9, *#abcd, w (.5s pause)
The application will either pass the assigned digits or terminate if it
encounters an error.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,10 @@
Sends arbitrary DTMF digits

[Description]
- SendDTMF(digits[|timeout_ms]): Sends DTMF digits on a channel.
- Accepted digits: 0-9, *#abcd, w (.5s pause)
+ SendDTMF(digits[,[timeout_ms][,duration_ms]]): Sends DTMF digits on a channel.
+ Accepted digits: 0-9, *#abcd, (default .25s pause between digits)
The application will either pass the assigned digits or terminate if it
encounters an error.
+ Optional Params:
+ timeout_ms: pause between digits.
+ duration_ms: duration of each digit.

.Siehe auch
xref:applications-read.adoc[Abschnitt C.126, „`Read()`“]
