[[applications-lookupcidname]]
= `LookupCIDName()`

Sucht einen Caller-ID-Namen in der AstDB.

[source]
----
LookupCIDName()
----

Schlägt die Caller-ID-Nummer des aktiven Channels in der AstDB
(Familie `cidname`) nach und setzt den Caller-ID-Namen –
wenn vorhanden – auf den gespeicherten Wert. Diese Anwendung tut
nichts, wenn auf dem Channel keine Caller-ID empfangen wird.
`LookupCIDName()` kann nützlich sein, wenn Sie nur eine
Caller-ID-Nummer, aber keinen -Namen empfangen oder wenn Sie den
Caller-ID-Namen für einige eingehende Anrufe ändern möchten.

Liefert stets 0 zurück.

Um der Liste Einträge hinzuzufügen, geben Sie im CLI +database
put cidname "_`Nummer`_"
"_`Name`_"+ ein bzw. +database del cidname
"_`Nummer`_"+ zum Löschen oder `database
show cidname` für eine Auflistung.

[source]
----
exten => 123,1,Answer()
exten => 123,n,LookupCIDName()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'LookupCIDName' =-

[Synopsis]
Look up CallerID Name from local database

[Description]
LookupCIDName: Looks up the Caller*ID number on the active
channel in the Asterisk database (family 'cidname') and sets the
Caller*ID name. Does nothing if no Caller*ID was received on the
channel. This is useful if you do not subscribe to Caller*ID
name delivery, or if you want to change the names on some incoming
calls.

LookupCIDName is deprecated. Please use ${DB(cidname/${CALLERID(num)})}
instead.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -10,3 +10,6 @@
channel. This is useful if you do not subscribe to Caller*ID
name delivery, or if you want to change the names on some incoming
calls.
+
+ LookupCIDName is deprecated. Please use ${DB(cidname/${CALLERID(num)})}
+ instead.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:functions-db.adoc[Abschnitt D.17, „`DB()`“]
