[[applications-hasnewvoicemail]]
= `HasNewVoicemail()`

Prüft, ob neue Voicemail-Nachrichten in einer Mailbox vorhanden
sind.

[source]
----
HasNewVoicemail(Mailbox[/Ordner][@Context][,Variable,[Optionen]])
----

[IMPORTANT]
====
`HasVoicemail()` ist ab Asterisk 1.6 nicht mehr
vorhanden und sogar schon ab 1.2 überflüssig, denn mit der Funktion
`VMCOUNT()` (xref:functions-vmcount.adoc[Abschnitt D.111, „`VMCOUNT()`“]) kann
man das Gleiche erreichen:

[source]
----
Set(anzahl=${VMCOUNT(4000)})
----
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'HasNewVoicemail' =-

[Synopsis]
Conditionally branches to priority + 101 with the right options set

[Description]
HasNewVoicemail(vmbox[/folder][@context][|varname[|options]])
Assumes folder 'INBOX' if folder is not specified. Optionally sets <varname> to the number of messages
in that folder.
The option string may contain zero of the following character:
'j' -- jump to priority n+101, if there is new voicemail in folder 'folder' or INBOX
This application sets the following channel variable upon completion:
HASVMSTATUS The result of the new voicemail check returned as a text string as follows
<# of messages in the folder, 0 for NONE>

This application has been deprecated in favor of the VMCOUNT() function

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -12,3 +12,5 @@
This application sets the following channel variable upon completion:
HASVMSTATUS The result of the new voicemail check returned as a text string as follows
<# of messages in the folder, 0 for NONE>
+
+ This application has been deprecated in favor of the VMCOUNT() function

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:applications-hasvoicemail.adoc[Abschnitt C.70, „`HasVoicemail()`“], xref:functions-vmcount.adoc[Abschnitt D.111, „`VMCOUNT()`“]
