[[applications-waitforring]]
= `WaitForRing()`

Wartet die in Sekunden vorgegebene Dauer auf ein
Klingelzeichen.

[source]
----
WaitForRing(Timeout)
----

Wartet nach dem Abschluss des nächsten Klingelns
`Timeout` Sekunden auf ein Klingelzeichen.

Liefert bei Erfolg 0, falls aufgelegt wurde, -1 zurück.

[source]
----
; 5 Sekunden auf Klingeln warten, dann ein paar DTMF-Töne senden:
exten => 123,1,Answer()
exten => 123,n,WaitForRing(5)
exten => 123,n,SendDTMF(1234)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'WaitForRing' =-

[Synopsis]
Wait for Ring Application

[Description]
WaitForRing(timeout)
Returns 0 after waiting at least timeout seconds. and
only after the next ring has completed. Returns 0 on
success or -1 on hangup

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Wait for Ring Application

[Description]
- WaitForRing(timeout)
+ WaitForRing(timeout):
Returns 0 after waiting at least timeout seconds. and
only after the next ring has completed. Returns 0 on
success or -1 on hangup
