[[applications-sendtext]]
= `SendText()`

Sendet Text zu dem Channel.

[source]
----
SendText(Text[,Optionen])
----

Überträgt den Text auf einem Channel (z. B. zur Anzeige im
Display), falls die Übertragung von Text unterstützt wird. Danach wird die
Ausführung bei der nächsten Priorität fortgesetzt. Mit der Option
`j` wird, wenn der Channel keine Textübertragung unterstützt, zur
Priorität n+101 gesprungen.

Der Text sollte bisher bei den meisten Kanälen 7-Bit-ASCII
sein.

Liefert 0 zurück, wenn der Text fehlerfrei übertragen wurde oder
der Channel eine Textübertragung nicht unterstützt, sonst -1. Setzt die
Channel-Variable `SENDTEXTSTATUS` auf `SUCCESS`
(Erfolg), `FAILURE` (Sendefehler) oder `UNSUPPORTED`
(nicht unterstützt).

[source]
----
exten => 123,1,SendText(Willkommen zu Asterisk)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SendText' =-

[Synopsis]
Send a Text Message

[Description]
SendText(text[|options]): Sends text to current channel (callee).
Result of transmission will be stored in the SENDTEXTSTATUS
channel variable:
SUCCESS Transmission succeeded
FAILURE Transmission failed
UNSUPPORTED Text transmission not supported by channel

At this moment, text is supposed to be 7 bit ASCII in most channels.
The option string many contain the following character:
'j' -- jump to n+101 priority if the channel doesn't support
text transport

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Send a Text Message

[Description]
- SendText(text[|options]): Sends text to current channel (callee).
+ SendText(text): Sends text to current channel (callee).
Result of transmission will be stored in the SENDTEXTSTATUS
channel variable:
SUCCESS Transmission succeeded
@@ -12,6 +12,3 @@
UNSUPPORTED Text transmission not supported by channel

At this moment, text is supposed to be 7 bit ASCII in most channels.
- The option string many contain the following character:
- 'j' -- jump to n+101 priority if the channel doesn't support
- text transport

.Siehe auch
xref:applications-sendimage.adoc[Abschnitt C.146, „`SendImage()`“], xref:applications-sendurl.adoc[Abschnitt C.148, „`SendURL()`“]
