[[applications-meetmeadmin]]
= `MeetMeAdmin()`

Administration von MeetMe-Konferenzen

[source]
----
MeetMeAdmin(KonferenzNr,Befehl[,TeilnehmerNr])
----

Führt den angegebenen MeetMe-Administrationsbefehl in der angegebenen
Konferenz aus. Der Befehl kann einer der folgenden sein (die
`TeilnehmerNr` wird nur für den Befehl `k` benötigt):

`K`:: Wirft alle Teilnehmer aus der Konferenz.
`k`:: Wirft den Teilnehmer mit der angegebenen `TeilnehmerNr` aus der Konferenz.
`e`:: Wirft den letzten Teilnehmer, der sich zu der Konferenz verbunden hat, raus.
`L`:: Sperrt die Konferenz (d.h. keine neuen Teilnehmer).
`l`:: Entsperrt die Konferenz.
`M`:: Schaltet die Konferenz für einen User stumm.
`m`:: Hebt die Stummschaltung (durch `M`) auf.
`N`:: Schaltet alle Teilnehmer außer dem Administrator stumm.
`n`:: Hebt die Stummschaltung (durch `N`) auf.

[source]
----
; Konferenz 333 fuer den User 3 stummschalten:
exten => 123,1,MeetMeAdmin(333,M,3)

; Teilnehmer 3 aus der Konferenz 333 kicken:
exten => 123,1,MeetMeAdmin(333,k,3)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'MeetMeAdmin' =-

[Synopsis]
MeetMe conference Administration

[Description]
MeetMeAdmin(confno,command[,user]): Run admin command for conference
'e' -- Eject last user that joined
'k' -- Kick one user out of conference
'K' -- Kick all users out of conference
'l' -- Unlock conference
'L' -- Lock conference
'm' -- Unmute one user
'M' -- Mute one user
'n' -- Unmute all users in the conference
'N' -- Mute all non-admin users in the conference
'r' -- Reset one user's volume settings
'R' -- Reset all users volume settings
's' -- Lower entire conference speaking volume
'S' -- Raise entire conference speaking volume
't' -- Lower one user's talk volume
'T' -- Raise one user's talk volume
'u' -- Lower one user's listen volume
'U' -- Raise one user's listen volume
'v' -- Lower entire conference listening volume
'V' -- Raise entire conference listening volume

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -10,7 +10,17 @@
'K' -- Kick all users out of conference
'l' -- Unlock conference
'L' -- Lock conference
- 'm' -- Unmute conference
- 'M' -- Mute conference
- 'n' -- Unmute entire conference (except admin)
- 'N' -- Mute entire conference (except admin)
+ 'm' -- Unmute one user
+ 'M' -- Mute one user
+ 'n' -- Unmute all users in the conference
+ 'N' -- Mute all non-admin users in the conference
+ 'r' -- Reset one user's volume settings
+ 'R' -- Reset all users volume settings
+ 's' -- Lower entire conference speaking volume
+ 'S' -- Raise entire conference speaking volume
+ 't' -- Lower one user's talk volume
+ 'T' -- Raise one user's talk volume
+ 'u' -- Lower one user's listen volume
+ 'U' -- Raise one user's listen volume
+ 'v' -- Lower entire conference listening volume
+ 'V' -- Raise entire conference listening volume

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-meetme.adoc[Abschnitt C.89, „`MeetMe()`“], xref:applications-meetmecount.adoc[Abschnitt C.92, „`MeetMeCount()`“], xref:applications-meetmechanneladmin.adoc[Abschnitt C.91, „`MeetMeChannelAdmin()`“]
