[[applications-jabberstatus]]
= `JabberStatus()`

Gibt den Status eines Jabber-Benutzers zurück.

[source]
----
JabberStatus(jabber,benutzer,variable)
----

Ermittelt den Status des Jabber-Benutzers
_`benutzer`_ und setzt die
_`variable`_ entsprechend. Zum Verbinden wird die
Definition _`jabber`_ aus
`jabber.conf` verwendet.

Für weitere Informationen siehe xref:functions-jabber_status.adoc[Abschnitt D.54, „`JABBER_STATUS()`“].

[source]
----
exten => 123,1,JabberStatus(asterisk,philipp@example.com,jabberstatus)
exten => 123,n,Verbose(1,### Der Jabber-Status von philipp ist ${jabberstatus})
----

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'JabberStatus' =-

[Synopsis]
JabberStatus(Jabber,ScreenName,Variable)

[Description]
JabberStatus(Jabber,ScreenName,Variable)
Jabber - Client or transport Asterisk uses to connect to Jabber
ScreenName - User Name to retrieve status from.
Variable - Variable to store presence in will be 1-6.
In order, Online, Chatty, Away, XAway, DND, Offline
If not in roster variable will = 7

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -8,5 +8,7 @@
Jabber - Client or transport Asterisk uses to connect to Jabber
ScreenName - User Name to retrieve status from.
Variable - Variable to store presence in will be 1-6.
- In order, Online, Chatty, Away, XAway, DND, Offline
- If not in roster variable will = 7
+ In order, 1=Online, 2=Chatty, 3=Away, 4=XAway, 5=DND, 6=Offline
+ If not in roster variable will be set to 7
+
+ Note: This application is deprecated. Please use the JABBER_STATUS() function instead.

.Siehe auch
xref:applications-jabbersend.adoc[Abschnitt C.75, „`JabberSend()`“], xref:functions-jabber_status.adoc[Abschnitt D.54, „`JABBER_STATUS()`“],
`jabber.conf`
