[[applications-sipgetheader]]
= `SIPGetHeader()`

Gibt einen Header aus dem SIP-Protokoll zurück.

[source]
----
SIPGetHeader(Variable=Headername|Optionen)
----

[IMPORTANT]
====
`SIPGetHeader()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `SIP_HEADER()`
(xref:functions-sip_header.adoc[Abschnitt D.89, „`SIP_HEADER()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'SIPGetHeader' =-

[Synopsis]
Get a SIP header from an incoming call

[Description]
SIPGetHeader(var=headername[|options]):
Sets a channel variable to the content of a SIP header
Options:
j - Jump to priority n+101 if the requested header isn't found.
This application sets the following channel variable upon completion:
SIPGETSTATUS - This variable will contain the status of the attempt
FOUND | NOTFOUND
This application has been deprecated in favor of the SIP_HEADER function.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-sip_header.adoc[Abschnitt D.89, „`SIP_HEADER()`“]
