[[applications-setgroup]]
= `SetGroup()`

Setzt die Gruppe des Kanals.

[source]
----
SetGroup(Gruppenname)
----

[IMPORTANT]
====
`SetGroup()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `GROUP()` (xref:functions-group.adoc[Abschnitt D.39, „`GROUP()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'SetGroup' =-

[Synopsis]
Set the channel's group

[Description]
Usage: SetGroup(groupname[@category])
Sets the channel group to the specified value. Equivalent to
Set(GROUP=group). Always returns 0.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-checkgroup.adoc[Abschnitt C.21, „`CheckGroup()`“], xref:applications-getgroupcount.adoc[Abschnitt C.61, „`GetGroupCount()`“], xref:applications-getgroupmatchcount.adoc[Abschnitt C.62, „`GetGroupMatchCount()`“], xref:functions-group.adoc[Abschnitt D.39, „`GROUP()`“]
