[[applications-random]]
= `Random()`

Springt zu einer zufälligen Priorität.

[source]
----
Random([Wahrscheinlichkeit]:[[Context,]Extension,]Priorität)
----

Springt bedingt zu der spezifizierten Priorität (und optional
Extension und Context), basierend auf der angegebenen Wahrscheinlichkeit,
die eine ganze Zahl zwischen 1 und 100 sein muss. Die Anwendung springt in
`Wahrscheinlichkeit` Prozent der Fälle zu dem angegebenen
Ziel.

[source]
----
; Glücksspiel mit 20 % Gewinnchance bei jedem Durchgang:
exten => 123,1,Random(20:gewonnen,1)
exten => 123,n,Goto(verloren,1)

exten => gewonnen,1,Playback(gewonnen)
exten => gewonnen,n,Goto(123,1)

exten => verloren,1,Playback(verloren)
exten => verloren,n,Goto(123,1)
----

[IMPORTANT]
====
Die Applikation `Random()` ist seit Version 1.4
„deprecated“ und wird durch die Funktion `RAND()`
ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Random' =-

[Synopsis]
Conditionally branches, based upon a probability

[Description]
Random([probability]:[[context|]extension|]priority)
probability := INTEGER in the range 1 to 100
DEPRECATED: Use GotoIf($[${RAND(1,100)} > <number>]?<label>)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -6,3 +6,4 @@
[Description]
Random([probability]:[[context|]extension|]priority)
probability := INTEGER in the range 1 to 100
+ DEPRECATED: Use GotoIf($[${RAND(1,100)} > <number>]?<label>)

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:functions-rand.adoc[Abschnitt D.80, „`RAND()`“]
