[[applications-morsecode]]
= `Morsecode()`

Gibt einen angegebenen String als Morsezeichen aus.

[source]
----
Morsecode(String)
----

Übermittelt den angegebenen String als Morsezeichen.

[source]
----
exten => 123,1,Answer()
exten => 123,n,Morsecode("Das Pferd frisst den Hafer nicht.")
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Morsecode' =-

[Synopsis]
Plays morse code

[Description]
Usage: Morsecode(<string>)
Plays the Morse code equivalent of the passed string. If the variable
MORSEDITLEN is set, it will use that value for the length (in ms) of the dit
(defaults to 80). Additionally, if MORSETONE is set, it will use that tone
(in Hz). The tone default is 800.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Plays morse code

[Description]
- Usage: Morsecode(<string>)
+ Morsecode(<string>):
Plays the Morse code equivalent of the passed string. If the variable
MORSEDITLEN is set, it will use that value for the length (in ms) of the dit
(defaults to 80). Additionally, if MORSETONE is set, it will use that tone
