[[applications-playback]]
= `Playback()`

Spielt dem Anrufer eine Audiodatei vor.

[source]
----
Playback(Dateiname[,Optionen])
----

Spielt dem Anrufer die Audiodatei `Dateiname` (aus dem
Verzeichnis `/var/lib/asterisk/sounds/`) vor. Der
Dateiname enthält keine Dateiendung, damit Asterisk automatisch die
Audiodatei mit dem niedrigsten Konvertierungsaufwand auswählen kann.
Keine, eine oder mehr Optionen können hinzugefügt werden.

Die Option `skip` bewirkt, dass die Wiedergabe der
Nachricht übersprungen wird, wenn sich der Channel nicht im Up-Status
befindet.

Normalerweise wird der Channel beantwortet, bevor die Audiodatei
wiedergegeben wird, es sei denn, `noanswer` ist angegeben.
(Nicht alle Kanäle unterstützen die Wiedergabe von Nachrichten, wenn sie
noch aufgelegt sind.)

Liefert -1 zurück, wenn der Channel aufgelegt wurde. Wenn die
Datei nicht existiert, wird zur Priorität n+101 übergegangen, falls diese
existiert.

[source]
----
exten => 123,1,Answer()
exten => 123,n,Playback(tt-weasels)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Playback' =-

[Synopsis]
Play a file

[Description]
Playback(filename[&filename2...][|option]): Plays back given filenames (do not put
extension). Options may also be included following a pipe symbol. The 'skip'
option causes the playback of the message to be skipped if the channel
is not in the 'up' state (i.e. it hasn't been answered yet). If 'skip' is
specified, the application will return immediately should the channel not be
off hook. Otherwise, unless 'noanswer' is specified, the channel will
be answered before the sound is played. Not all channels support playing
messages while still on hook. If 'j' is specified, the application
will jump to priority n+101 if present when a file specified to be played
does not exist.
This application sets the following channel variable upon completion:
PLAYBACKSTATUS The status of the playback attempt as a text string, one of
SUCCESS | FAILED
See Also: Background (application) -- for playing soundfiles that are interruptible
WaitExten (application) -- wait for digits from caller, optionally play music on hold

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -17,3 +17,5 @@
This application sets the following channel variable upon completion:
PLAYBACKSTATUS The status of the playback attempt as a text string, one of
SUCCESS | FAILED
+ See Also: Background (application) -- for playing soundfiles that are interruptible
+ WaitExten (application) -- wait for digits from caller, optionally play music on hold

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,16 +4,14 @@
Play a file

[Description]
- Playback(filename[&filename2...][|option]): Plays back given filenames (do not put
- extension). Options may also be included following a pipe symbol. The 'skip'
- option causes the playback of the message to be skipped if the channel
+ Playback(filename[&filename2...][,option]): Plays back given filenames (do not put
+ extension). Options may also be included following a comma.
+ The 'skip' option causes the playback of the message to be skipped if the channel
is not in the 'up' state (i.e. it hasn't been answered yet). If 'skip' is
specified, the application will return immediately should the channel not be
off hook. Otherwise, unless 'noanswer' is specified, the channel will
be answered before the sound is played. Not all channels support playing
- messages while still on hook. If 'j' is specified, the application
- will jump to priority n+101 if present when a file specified to be played
- does not exist.
+ messages while still on hook.
This application sets the following channel variable upon completion:
PLAYBACKSTATUS The status of the playback attempt as a text string, one of
SUCCESS | FAILED

.Siehe auch
xref:applications-background.adoc[Abschnitt C.13, „`Background()`“]
