[[applications-answer]]
= `Answer()`

Antwortet auf einen klingelnden Channel.

[source]
----
Answer([Verzögerung])
----

Veranlasst Asterisk zum Beantworten eines Channels, wenn er gerade
klingelt. Falls der aktuelle Channel nicht klingelt, tut diese Anwendung
nichts.

Es ist generell empfehlenswert, `Answer()` vor dem
Aufrufen irgendwelcher anderen Anwendungen auf dem Channel aufzurufen, außer
es besteht ein guter Grund, das nicht zu tun. Die meisten Anwendungen
verlangen, dass der Channel beantwortet wird, bevor sie aufgerufen werden,
und werden andernfalls eventuell nicht in der Lage sein, ihre Arbeit korrekt
zu verrichten.

Die optionale `Verzögerung` weist Asterisk an, so viele
Millisekunden vor dem Antworten zu warten.

Gibt bei Erfolg 0 zurück.

[source]
----
exten => 123,1,Answer()
exten => 123,n,Wait(1)
exten => 123,n,Playback(hallo)
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Answer' =-

[Synopsis]
Answer a channel if ringing

[Description]
Answer([delay]): If the call has not been answered, this application will
answer it. Otherwise, it has no effect on the call. If a delay is specified,
Asterisk will wait this number of milliseconds before returning to
the dialplan after answering the call.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-hangup.adoc[Abschnitt C.68, „`Hangup()`“]
