[[applications-verbose]]
= `Verbose()`

Sendet beliebigen Text zum „verbose output“ (Ausgabe
im CLI).

[source]
----
Verbose([Level,]Nachricht)
----

Sendet die angegebene Nachricht an das CLI. Die Stufe
`Level` kann als ganzzahliger Wert angegeben werden, um die
Nachricht nur bei mindestens diesem Verbosity-Level anzuzeigen.footnote:[Zum Beispiel `asterisk -vvvr` für Level 3 - oder `set verbose 3` im CLI] Ist `Level` nicht angegeben, wird 0
angenommen.

Liefert stets 0 zurück.

[source]
----
exten => 123,1,Verbose(1,Jemand ruft Extension 123 an.)
exten => 123,n,Playback(extension)
exten => 123,n,SayDigits(${EXTEN})
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Verbose' =-

[Synopsis]
Send arbitrary text to verbose output

[Description]
Verbose([<level>|]<message>)
level must be an integer value. If not specified, defaults to 0.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,5 +4,5 @@
Send arbitrary text to verbose output

[Description]
- Verbose([<level>|]<message>)
+ Verbose([<level>,]<message>)
level must be an integer value. If not specified, defaults to 0.

.Siehe auch
xref:applications-noop.adoc[Abschnitt C.107, „`NoOp()`“], xref:applications-log.adoc[Abschnitt C.78, „`Log()`“], xref:applications-dumpchan.adoc[Abschnitt C.43, „`DumpChan()`“]
