[[applications-getgroupcount]]
= `GetGroupCount()`

Gibt die Anzahl der Kanäle in einer Gruppe von Kanälen
zurück.

[source]
----
GetGroupCount(Gruppe[@Kategorie])
----

[IMPORTANT]
====
`GetGroupCount()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `GROUP_COUNT()`
(xref:functions-group_count.adoc[Abschnitt D.40, „`GROUP_COUNT()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'GetGroupCount' =-

[Synopsis]
Get the channel count of a group

[Description]
Usage: GetGroupCount([groupname][@category])
Calculates the group count for the specified group, or uses
the current channel's group if not specifed (and non-empty).
Stores result in GROUPCOUNT.
Note: This application has been deprecated, please use the function
GROUP_COUNT.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-setgroup.adoc[Abschnitt C.158, „`SetGroup()`“], xref:applications-checkgroup.adoc[Abschnitt C.21, „`CheckGroup()`“], xref:applications-getgroupmatchcount.adoc[Abschnitt C.62, „`GetGroupMatchCount()`“], xref:functions-group_count.adoc[Abschnitt D.40, „`GROUP_COUNT()`“]
