[[applications-agentmonitoroutgoing]]
= `AgentMonitorOutgoing()`

Speichert die ausgehenden Anrufe eines Agenten.

[source]
----
AgentMonitorOutgoing([Optionen])
----

Zeichnet alle ausgehenden Anrufe eines Agenten auf.

Diese Anwendung versucht, die ID eines Agenten, der einen
ausgehenden Anruf tätigt, herauszufinden, indem er die ID des Anrufers
(Caller-ID) des gegenwärtigen Interfaces mit einer von der
`AgentCallbackLogin()`-Anwendung gesetzten globalen Variablen
vergleicht. Daher wird dringend empfohlen, diese Anwendung nur in Verbindung
mit der `AgentCallbackLogin()`-Anwendung (und zwar nach dieser!)
zu verwenden. Um die Anrufe aufzuzeichnen, werden anstelle der Anwendung
`Monitor()` die Überwachungsfunktionen des
`chan_agent`-Moduls benutzt. Deshalb muss das Aufzeichnen der
Anrufe in der `agents.conf`-Datei korrekt konfiguriert
sein.

Standardmäßig werden aufgezeichnete Anrufe im Verzeichnis
`/var/spool/asterisk/monitor/` abgelegt. Diese
Einstellung kann durch Anpassung des Parameters `savecallsin` in
der Datei `agents.conf` überschrieben werden. Bitte
denken Sie daran, dass die Speicherung von Telefonaten dem Datenschutz und
der Wahrung von Persönlichkeitsrechten unterliegt. Sie sollten sich genau
darüber informieren, wann und wie Sie Telefonate aufzeichnen dürfen. Als
allgemeine Regel gilt, dass Sie ohne Wissen und Einverständnis der
Teilnehmer kein Telefonat aufzeichnen dürfen.

Können die ID des Anrufers (Caller-ID) und/oder die ID des Agenten
(Agent-ID) nicht ermittelt werden, wird diese Anwendung zur Priorität n+101
springen, falls diese existiert.

Falls keine der folgenden Optionen anderes bewirkt, liefert die
Anwendung 0 zurück.

Der `Optionen`-Parameter kann aus einer oder mehreren
der folgenden Optionen zusammengesetzt sein.

`d`:: Zwingt die Anwendung zur Rückgabe von -1, falls ein Fehler vorliegt und keine Priorität n+101 existiert.
`c`:: Ändert den Call Detail Record dahingehend, dass +_`Agent`_/_`AgentenNr`_+ als Channel gespeichert wird, von dem der Anruf ausgeht, damit festgestellt werden kann, von welchem Agenten der Anruf ausging.
`n`:: Unterdrückt Warnmeldungen in dem Fall, dass Caller-ID bzw. Agent-ID unbekannt sind. Diese Option ist hilfreich, wenn ein gemeinsamer Context für Agenten- und Nicht-Agenten-Anrufe erwünscht ist.

[source]
----
; ausgehende Anrufe dieses Agenten aufzeichnen, und den CDR
; entsprechend anpassen:
exten => 123,1,AgentMonitorOutgoing(c)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'AgentMonitorOutgoing' =-

[Synopsis]
Record agent's outgoing call

[Description]
AgentMonitorOutgoing([options]):
Tries to figure out the id of the agent who is placing outgoing call based on
comparison of the callerid of the current interface and the global variable
placed by the AgentCallbackLogin application. That's why it should be used only
with the AgentCallbackLogin app. Uses the monitoring functions in chan_agent
instead of Monitor application. That have to be configured in the agents.conf file.

Return value:
Normally the app returns 0 unless the options are passed. Also if the callerid or
the agentid are not specified it'll look for n+101 priority.

Options:
'd' - make the app return -1 if there is an error condition and there is
no extension n+101
'c' - change the CDR so that the source of the call is 'Agent/agent_id'
'n' - don't generate the warnings when there is no callerid or the
agentid is not known.
It's handy if you want to have one context for agent and non-agent calls.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -9,15 +9,13 @@
comparison of the callerid of the current interface and the global variable
placed by the AgentCallbackLogin application. That's why it should be used only
with the AgentCallbackLogin app. Uses the monitoring functions in chan_agent
- instead of Monitor application. That have to be configured in the agents.conf file.
+ instead of Monitor application. That has to be configured in the agents.conf file.

Return value:
- Normally the app returns 0 unless the options are passed. Also if the callerid or
- the agentid are not specified it'll look for n+101 priority.
+ Normally the app returns 0 unless the options are passed.

Options:
- 'd' - make the app return -1 if there is an error condition and there is
- no extension n+101
+ 'd' - make the app return -1 if there is an error condition
'c' - change the CDR so that the source of the call is 'Agent/agent_id'
'n' - don't generate the warnings when there is no callerid or the
agentid is not known.

.Siehe auch
xref:applications-agentcallbacklogin.adoc[Abschnitt C.4, „`AgentCallbackLogin()`“],
`agents.conf`, xref:applications-monitor.adoc[Abschnitt C.100, „`Monitor()`“],
xref:applications-chanspy.adoc[Abschnitt C.20, „`ChanSpy()`“]
