[[applications-parkandannounce]]
= `ParkAndAnnounce()`

Parkt den aktuellen Anruf und macht ihn über den spezifizierten
Channel bekannt.

[source]
----
ParkAndAnnounce(Template,Timeout,Channel[,Return-Context])
----

Parkt den aktuellen Anruf in dem dafür vorgesehenen Bereich (auf
dem Parkplatz) und meldet ihn über den spezifizierten Channel.
`Template` bezeichnet eine Liste von durch Kommas voneinander
getrennten Dateien, die anzukündigen sind; das Wort `PARKED`
wird durch die Parkplatznummer des Anrufs ersetzt. Der Parameter
`Timeout` bestimmt die Zeit in Sekunden, nach deren Ablauf der
Anruf zum `Return-Context` zurückkehrt. `Channel`
bezeichnet den Channel, der anzurufen ist, um die Ankündigung zu machen
(`Console/dsp` ruft die Konsole auf).
`Return-Context` ist ein Label im `GoTo()`-Stil, um
den Anruf nach der Beendigung zurückzubringen. Standardeinstellung hierfür
ist n+1 im Context `Return-Context`.

[source]
----
include => parkedcalls
exten => 123,1,Answer()
exten => 123,n,ParkAndAnnounce(vm-youhave:a:pbx-transfer:at:vm-extension:PARKED,120,Console/dsp)
exten => 123,n,Playback(vm-nobodyavail)
exten => 123,n,Playback(vm-goodbye)
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ParkAndAnnounce' =-

[Synopsis]
Park and Announce

[Description]
ParkAndAnnounce(announce:template|timeout|dial|[return_context]):
Park a call into the parkinglot and announce the call to another channel.

announce template: Colon-separated list of files to announce. The word PARKED
will be replaced by a say_digits of the extension in which
the call is parked.
timeout: Time in seconds before the call returns into the return
context.
dial: The app_dial style resource to call to make the
announcement. Console/dsp calls the console.
return_context: The goto-style label to jump the call back into after
timeout. Default <priority+1>.

The variable ${PARKEDAT} will contain the parking extension into which the
call was placed. Use with the Local channel to allow the dialplan to make
use of this information.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -5,9 +5,18 @@

[Description]
ParkAndAnnounce(announce:template|timeout|dial|[return_context]):
- Park a call into the parkinglot and announce the call over the console.
- announce template: colon separated list of files to announce, the word PARKED
- will be replaced by a say_digits of the ext the call is parked in
- timeout: time in seconds before the call returns into the return context.
- dial: The app_dial style resource to call to make the announcement. Console/dsp calls the console.
- return_context: the goto style label to jump the call back into after timeout. default=prio+1
+ Park a call into the parkinglot and announce the call to another channel.
+
+ announce template: Colon-separated list of files to announce. The word PARKED
+ will be replaced by a say_digits of the extension in which
+ the call is parked.
+ timeout: Time in seconds before the call returns into the return
+ context.
+ dial: The app_dial style resource to call to make the
+ announcement. Console/dsp calls the console.
+ return_context: The goto-style label to jump the call back into after
+ timeout. Default <priority+1>.
+
+ The variable ${PARKEDAT} will contain the parking extension into which the
+ call was placed. Use with the Local channel to allow the dialplan to make
+ use of this information.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Park and Announce

[Description]
- ParkAndAnnounce(announce:template|timeout|dial|[return_context]):
+ ParkAndAnnounce(announce:template,timeout,dial[,return_context]):
Park a call into the parkinglot and announce the call to another channel.

announce template: Colon-separated list of files to announce. The word PARKED

.Siehe auch
xref:applications-park.adoc[Abschnitt C.110, „`Park()`“], xref:applications-parkedcall.adoc[Abschnitt C.112, „`ParkedCall()`“]
