[[applications-sayalpha]]
= `SayAlpha()`

Spricht eine Zeichenkette.

[source]
----
SayAlpha(String)
----

Buchstabiert den übergebenen String unter Verwendung der
aktuellen Spracheinstellung für den Channel. Die Sprache kann mit der
Funktion `LANGUAGE()` geändert werden.

[source]
----
exten => 123,1,SayAlpha(ABC123)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SayAlpha' =-

[Synopsis]
Say Alpha

[Description]
SayAlpha(string): This application will play the sounds that correspond to
the letters of the given string.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-saydigits.adoc[Abschnitt C.140, „`SayDigits()`“], xref:applications-saynumber.adoc[Abschnitt C.141, „`SayNumber()`“], xref:applications-sayphonetic.adoc[Abschnitt C.142, „`SayPhonetic()`“]
