[[applications-directory]]
= `Directory()`

Stellt ein Verzeichnis anwählbarer (Voicemail-)Extensions bereit
(internes Telefonbuch, Dial-by-name, siehe xref:voicemail-telefonbuch.adoc[Abschnitt 13.5, „Telefonbuch
(Dial-by-Name)“]).

[source]
----
Directory(VM-Context[,Wähl-Context[,Optionen]])
----

Liefert Benutzern ein Verzeichnis mit Extensionen, aus dem anhand
des Namens ausgewählt werden kann. Die Liste von Namen und Extensionen
findet sich in `voicemail.conf`. Der
`VM-Context` muss angegeben werden. Er bestimmt, welcher Context
aus `voicemail.conf` benutzt wird.

Der `Wähl-Context` bestimmt den Content, der zum Anrufen
der Benutzer verwendet werden soll. Falls er nicht angegeben ist, wird
`VM-Context` angenommen. Momentan ist die einzige mögliche
Option, die im `Optionen`-Parameter Verwendung finden kann,
`f` (wie _first name_), die das Verzeichnis
veranlasst, die Eingabe anhand des Vornamens statt des Nachnamens
abzugleichen.

Gibt der Benutzer `0` (Null) ein und existiert eine
Extension o (kleiner Buchstabe o) im aktuellen Context, geht die Steuerung
des Anrufs an diese Extension über. Durch Drücken der Taste * wird analog
dazu zur `a`-Extension übergegangen. Diese Verhalten ähnelt dem
von `Voicemail()`.

Gibt 0 zurück, es sei denn, der Teilnehmer legt auf.

[source]
----
exten => *,1,Directory(default,incoming)
exten => #,1,Directory(default,incoming,f)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Directory' =-

[Synopsis]
Provide directory of voicemail extensions

[Description]
Directory(vm-context[|dial-context[|options]]): This application will present
the calling channel with a directory of extensions from which they can search
by name. The list of names and corresponding extensions is retrieved from the
voicemail configuration file, voicemail.conf.
This application will immediately exit if one of the following DTMF digits are
received and the extension to jump to exists:
0 - Jump to the 'o' extension, if it exists.
* - Jump to the 'a' extension, if it exists.

Parameters:
vm-context - This is the context within voicemail.conf to use for the
Directory.
dial-context - This is the dialplan context to use when looking for an
extension that the user has selected, or when jumping to the
'o' or 'a' extension.

Options:
e - In addition to the name, also read the extension number to the
caller before presenting dialing options.
f - Allow the caller to enter the first name of a user in the directory
instead of using the last name.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -21,5 +21,7 @@
'o' or 'a' extension.

Options:
+ e - In addition to the name, also read the extension number to the
+ caller before presenting dialing options.
f - Allow the caller to enter the first name of a user in the directory
instead of using the last name.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Provide directory of voicemail extensions

[Description]
- Directory(vm-context[|dial-context[|options]]): This application will present
+ Directory(vm-context[,dial-context[,options]]): This application will present
the calling channel with a directory of extensions from which they can search
by name. The list of names and corresponding extensions is retrieved from the
voicemail configuration file, voicemail.conf.
@@ -21,7 +21,26 @@
'o' or 'a' extension.

Options:
- e - In addition to the name, also read the extension number to the
- caller before presenting dialing options.
- f - Allow the caller to enter the first name of a user in the directory
- instead of using the last name.
+ e In addition to the name, also read the extension number to the
+ caller before presenting dialing options.
+ f[(<n>)] Allow the caller to enter the first name of a user in the
+ directory instead of using the last name. If specified, the
+ optional number argument will be used for the number of
+ characters the user should enter.
+ l[(<n>)] Allow the caller to enter the last name of a user in the
+ directory. This is the default. If specified, the
+ optional number argument will be used for the number of
+ characters the user should enter.
+ b[(<n>)] Allow the caller to enter either the first or the last name
+ of a user in the directory. If specified, the optional number
+ argument will be used for the number of characters the user
+ should enter.
+ m Instead of reading each name sequentially and asking for
+ confirmation, create a menu of up to 8 names.
+ p(<n>) Pause for n milliseconds after the digits are typed. This is
+ helpful for people with cellphones, who are not holding the
+ receiver to their ear while entering DTMF.
+
+ Only one of the f, l, or b options may be specified. If more than one is
+ specified, then Directory will act as if 'b' was specified. The number
+ of characters for the user to type defaults to 3.

.Siehe auch
`voicemail.conf`
