[[applications-dahdisendkeypadfacility]]
= `DAHDISendKeypadFacility()`

Sendet Ziffern „out-of-band“ auf einer
PRI-ISDN-Verbindung.

[source]
----
DAHDISendKeypadFacility(Ziffern)
----

[NOTE]
====
Diese Applikation ist durch die Umbenennung von Zaptel in
DAHDIfootnote:[xref:glossar.adoc#glossar-dahdi[DAHDI\]] entstanden. Für eine Beschreibung siehe xref:applications-zapsendkeypadfacility.adoc[Abschnitt C.200, „`ZapSendKeypadFacility()`“].
====

.Asterisk-Versionen:
| | | *1.4**|————————| *1.6* |————————
(* anderer Name)

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'DAHDISendKeypadFacility' =-

[Synopsis]
Send digits out of band over a PRI

[Description]
DAHDISendKeypadFacility(): This application will send the given string of digits in a Keypad Facility
IE over the current channel.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 (xref:applications-zapsendkeypadfacility.adoc[Abschnitt C.200, „`ZapSendKeypadFacility()`“]) zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,8 +1,8 @@
- -= Info about application 'ZapSendKeypadFacility' =-
+ -= Info about application 'DAHDISendKeypadFacility' =-

[Synopsis]
Send digits out of band over a PRI

[Description]
- ZapSendKeypadFacility(): This application will send the given string of digits in a Keypad Facility
+ DAHDISendKeypadFacility(): This application will send the given string of digits in a Keypad Facility
IE over the current channel.

.Siehe auch
xref:applications-zapsendkeypadfacility.adoc[Abschnitt C.200, „`ZapSendKeypadFacility()`“]
