[[applications-getcpeid]]
= `GetCPEID()`

Holt die CPE-ID eines ADSI-fähigen Telefons.

[source]
----
GetCPEID()
----

Holt die CPE-ID und weitere Informationen und zeigt sie auf der
Asterisk-Konsole an. Diese Informationen werden häufig benötigt, um die
Datei `zapata.conf` für Operationen bei ADSI-fähigen
Telefonen einzurichten.

Liefert beim Auflegen -1 zurück.

[source]
----
exten => 123,1,GetCPEID()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'GetCPEID' =-

[Synopsis]
Get ADSI CPE ID

[Description]
GetCPEID: Obtains and displays ADSI CPE ID and other information in order
to properly setup zapata.conf for on-hook operations.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,5 +4,5 @@
Get ADSI CPE ID

[Description]
- GetCPEID: Obtains and displays ADSI CPE ID and other information in order
- to properly setup zapata.conf for on-hook operations.
+ GetCPEID(): Obtains and displays ADSI CPE ID and other information in order
+ to properly setup dahdi.conf for on-hook operations.

.Siehe auch
xref:applications-adsiprog.adoc[Abschnitt C.3, „`ADSIProg()`“],
`adsi.conf`, `zapata.conf`
