[[applications-zapsendkeypadfacility]]
= `ZapSendKeypadFacility()`

Sendet Ziffern „out-of-band“ auf einer
PRI-ISDN-Verbindung.

[source]
----
ZapSendKeypadFacility(Ziffern)
----

Sendet die angegebenen Ziffern
(`0`--`9`, `*`,
`#`) „out-of-band“ in einem Q.931
„Keypad Facility“ „Information Element“ (IE) auf
einer PRI-Verbindung.

[source]
----
exten => 123,1,ZapSendKeypadFacility(*456)
----

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6**|————————
(* anderer Name)

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ZapSendKeypadFacility' =-

[Synopsis]
Send digits out of band over a PRI

[Description]
ZapSendKeypadFacility(): This application will send the given string of digits in a Keypad Facility
IE over the current channel.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6 (xref:applications-dahdisendkeypadfacility.adoc[Abschnitt C.31, „`DAHDISendKeypadFacility()`“]):
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,8 +1,8 @@
- -= Info about application 'ZapSendKeypadFacility' =-
+ -= Info about application 'DAHDISendKeypadFacility' =-

[Synopsis]
Send digits out of band over a PRI

[Description]
- ZapSendKeypadFacility(): This application will send the given string of digits in a Keypad Facility
+ DAHDISendKeypadFacility(): This application will send the given string of digits in a Keypad Facility
IE over the current channel.

.Siehe auch
xref:applications-dahdisendkeypadfacility.adoc[Abschnitt C.31, „`DAHDISendKeypadFacility()`“]
