[[applications-zapscan]]
= `ZapScan()`

Durchsucht Zap-Kanäle, um Anrufe zu überwachen.

[source]
----
ZapScan([Gruppe])
----

Erlaubt einem Call-Center-Manager, Zap-Kanäle auf bequeme Art zu
überwachen. Benutzen Sie `#`, um den nächsten Channel
auszuwählen, oder `*` zum Beenden. Sie können die Abfrage auf
eine bestimmte Channel-Gruppe begrenzen, indem Sie den Parameter
`Gruppe` verwenden.

[source]
----
exten => 123,1,ZapScan()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6**|————————
(* anderer Name)

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ZapScan' =-

[Synopsis]
Scan Zap channels to monitor calls

[Description]
ZapScan([group]) allows a call center manager to monitor Zap channels in
a convenient way. Use '#' to select the next channel and use '*' to exit
Limit scanning to a channel GROUP by setting the option group argument.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6 (xref:applications-dahdiscan.adoc[Abschnitt C.30, „`DAHDIScan()`“]):
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,9 +1,9 @@
- -= Info about application 'ZapScan' =-
+ -= Info about application 'DAHDIScan' =-

[Synopsis]
- Scan Zap channels to monitor calls
+ Scan DAHDI channels to monitor calls

[Description]
- ZapScan([group]) allows a call center manager to monitor Zap channels in
+ DAHDIScan([group]) allows a call center manager to monitor DAHDI channels in
a convenient way. Use '#' to select the next channel and use '*' to exit
Limit scanning to a channel GROUP by setting the option group argument.

.Siehe auch
xref:applications-dahdiscan.adoc[Abschnitt C.30, „`DAHDIScan()`“], xref:applications-zapbarge.adoc[Abschnitt C.197, „`ZapBarge()`“], xref:applications-chanspy.adoc[Abschnitt C.20, „`ChanSpy()`“], xref:functions-group.adoc[Abschnitt D.39, „`GROUP()`“]
