[[applications-removequeuemember]]
= `RemoveQueueMember()`

Entfernt dynamisch Warteschlangenmitglieder.

[source]
----
RemoveQueueMember(Warteschlange[,Interface])
----

Enfernt das spezifizierte Interface dynamisch aus der
Warteschlange. Ist `Interface` nicht angegeben, entfernt die
Anwendung das momentan in Verwendung befindliche Interface aus der
Warteschlange.

Ist das Interface nicht in der Warteschlange enthalten und
existiert eine Priorität n+101, wird die Anwendung zu dieser Priorität
übergehen. Andernfalls wird sie einen Fehler zurückliefern.

Liefert -1, wenn ein Fehler auftritt, sonst 0.

[source]
----
; SIP/3000 aus der "supportschlange" entfernen:
exten => 123,1,RemoveQueueMember(supportschlange,SIP/3000)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'RemoveQueueMember' =-

[Synopsis]
Dynamically removes queue members

[Description]
RemoveQueueMember(queuename[|interface[|options]]):
Dynamically removes interface to an existing queue
If the interface is NOT in the queue and there exists an n+101 priority
then it will then jump to this priority. Otherwise it will return an error
The option string may contain zero or more of the following characters:
'j' -- jump to +101 priority when appropriate.
This application sets the following channel variable upon completion:
RQMSTATUS The status of the attempt to remove a queue member as a
text string, one of
REMOVED | NOTINQUEUE | NOSUCHQUEUE
Example: RemoveQueueMember(techsupport|SIP/3000)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,14 +4,11 @@
Dynamically removes queue members

[Description]
- RemoveQueueMember(queuename[|interface[|options]]):
+ RemoveQueueMember(queuename[,interface[,options]]):
Dynamically removes interface to an existing queue
- If the interface is NOT in the queue and there exists an n+101 priority
- then it will then jump to this priority. Otherwise it will return an error
- The option string may contain zero or more of the following characters:
- 'j' -- jump to +101 priority when appropriate.
+ If the interface is NOT in the queue it will return an error.
This application sets the following channel variable upon completion:
RQMSTATUS The status of the attempt to remove a queue member as a
text string, one of
REMOVED | NOTINQUEUE | NOSUCHQUEUE
- Example: RemoveQueueMember(techsupport|SIP/3000)
+ Example: RemoveQueueMember(techsupport,SIP/3000)

.Siehe auch
xref:applications-addqueuemember.adoc[Abschnitt C.2, „`AddQueueMember()`“], xref:applications-queue.adoc[Abschnitt C.122, „`Queue()`“], `queues.conf`
