[[applications-vmauthenticate]]
= `VMAuthenticate()`

Authentifiziert den Anrufer über ein Voicemail-Passwort.

[source]
----
VMAuthenticate([Mailbox][@Context][,Optionen])
----

Verhält sich wie die `Authenticate()`-Anwendung, mit dem
Unterschied, dass die Passwörter aus `voicemail.conf` (im
optionalen VM-Context `Context`) gelesen werden.

Ist eine Mailbox angegeben, wird nur das Passwort dieser Mailbox
als gültig betrachtet. Ohne Angabe kann sich der Anrufer mit jedem (!)
VM-Passwort authentifizieren; die Channel-Variable
`${AUTH_MAILBOX}` wird dann mit der authentifizierten Mailbox
belegt.

Mit der Option `s` wird die Ansage der Aufforderung
unterdrückt.

[source]
----
; als Mailbox die Extension annehmen und authentifizieren:
exten => 123,1,VMAuthenticate(${EXTEN}@verkauf)
exten => 123,n,SayDigits(${AUTH_MAILBOX})
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'VMAuthenticate' =-

[Synopsis]
Authenticate with Voicemail passwords

[Description]
VMAuthenticate([mailbox][@context][|options]): This application behaves the
same way as the Authenticate application, but the passwords are taken from
voicemail.conf.
If the mailbox is specified, only that mailbox's password will be considered
valid. If the mailbox is not specified, the channel variable AUTH_MAILBOX will
be set with the authenticated mailbox.

Options:
s - Skip playing the initial prompts.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Authenticate with Voicemail passwords

[Description]
- VMAuthenticate([mailbox][@context][|options]): This application behaves the
+ VMAuthenticate([mailbox][@context][,options]): This application behaves the
same way as the Authenticate application, but the passwords are taken from
voicemail.conf.
If the mailbox is specified, only that mailbox's password will be considered

.Siehe auch
xref:applications-authenticate.adoc[Abschnitt C.12, „`Authenticate()`“],
`voicemail.conf`
