[[applications-congestion]]
= `Congestion()`

Zeigt einen Stau (Überlastung) auf dem Channel an.

[source]
----
Congestion([Timeout])
----

Zeigt auf dem Channel einen Stau an und wartet dann, bis der
Teilnehmer auflegt, oder bis die optional spezifizierbare Frist
(`Timeout`, in Sekunden) abgelaufen ist.

Diese Anwendung signalisiert lediglich einen Stau, sie spielt aber
dem Teilnehmer keinen Stau-Ton vor. Um einem Anrufer einen Stau-Ton
vorzuspielen, kann `Playtones(congestion)` verwendet
werden.

Liefert stets -1 zurück.

[source]
----
; bei Caller ID is 0123-123456 immer Stau-Signal spielen:
exten => 123,1,GotoIf($[${CALLERID(num)} = 0123123456]?10)
exten => 123,n,Playtones(congestion)
exten => 123,n,Congestion(5)
exten => 123,n,Hangup()
exten => 123,10,Dial(Zap/1)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Congestion' =-

[Synopsis]
Indicate the Congestion condition

[Description]
Congestion([timeout]): This application will indicate the congestion
condition to the calling channel. If the optional timeout is specified, the
calling channel will be hung up after the specified number of seconds.
Otherwise, this application will wait until the calling channel hangs up.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -4,7 +4,7 @@
Indicate the Congestion condition

[Description]
- Congestion([timeout]): This application will indicate the congenstion
+ Congestion([timeout]): This application will indicate the congestion
condition to the calling channel. If the optional timeout is specified, the
calling channel will be hung up after the specified number of seconds.
Otherwise, this application will wait until the calling channel hangs up.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-busy.adoc[Abschnitt C.16, „`Busy()`“], xref:applications-progress.adoc[Abschnitt C.121, „`Progress()`“], xref:applications-playtones.adoc[Abschnitt C.118, „`Playtones()`“]
