[[applications-sipaddheader]]
= `SIPAddHeader()`

Fügt dem ausgehenden SIP-Anruf einen Header hinzu.

[source]
----
SIPAddHeader(Header: Wert)
----

Fügt einem mit der `Dial()`-Anwendung initiierten
SIP-Anruf einen Header hinzu. Ein nicht standardisierter SIP-Header sollte
mit einem `X-` beginnen, wie etwa
`X-Asterisk-Accountcode:`. Verwenden Sie diese Anwendung mit
Vorsicht, denn das Hinzufügen eines falschen Headers kann Probleme
verursachen. Mit dieser Applikation können keine SIP-Header verändert
werden.

Liefert stets 0 zurück.

[source]
----
exten => 123,1,SIPAddHeader(X-Asterisk-Account: ${CDR(accountcode)})
exten => 123,n,Dial(SIP/123)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SIPAddHeader' =-

[Synopsis]
Add a SIP header to the outbound call

[Description]
SIPAddHeader(Header: Content)
Adds a header to a SIP call placed with DIAL.
Remember to user the X-header if you are adding non-standard SIP
headers, like "X-Asterisk-Accountcode:". Use this with care.
Adding the wrong headers may jeopardize the SIP dialog.
Always returns 0

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Add a SIP header to the outbound call

[Description]
- SIPAddHeader(Header: Content)
+ SIPAddHeader(Header: Content):
Adds a header to a SIP call placed with DIAL.
Remember to user the X-header if you are adding non-standard SIP
headers, like "X-Asterisk-Accountcode:". Use this with care.

.Siehe auch
xref:functions-sip_header.adoc[Abschnitt D.89, „`SIP_HEADER()`“]
