[[applications-responsetimeout]]
= `ResponseTimeout()`

Setzt einen Timeout auf einem Kanal.

[source]
----
ResponseTimeout(Sekunden)
----

[IMPORTANT]
====
`ResponseTimeout()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `TIMEOUT()` (xref:functions-timeout.adoc[Abschnitt D.101, „`TIMEOUT()`“]) ersetzt:

[source]
----
Set(TIMEOUT(response)=Sekunden)
----
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'ResponseTimeout' =-

[Synopsis]
Set maximum timeout awaiting response

[Description]
ResponseTimeout(seconds): This will set the maximum amount of time permitted
to wait for an extension to dialed (see the WaitExten application), before the
timeout occurs. If this timeout is reached, dialplan execution will continue at
the 't' extension, if it exists.
ResponseTimeout has been deprecated in favor of Set(TIMEOUT(response)=timeout)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-absolutetimeout.adoc[Abschnitt C.1, „`AbsoluteTimeout()`“], xref:applications-digittimeout.adoc[Abschnitt C.40, „`DigitTimeout()`“], xref:functions-timeout.adoc[Abschnitt D.101, „`TIMEOUT()`“]
