[[applications-minivmgreet]]
= `MinivmGreet()`

Ansage für Mini-VoiceMail abspielen.

[source]
----
MinivmGreet(benutzer@domain[,optionen])
----

Spielt die Standard- oder die benutzerspezifische Ansage (siehe
xref:applications-minivmaccmess.adoc[Abschnitt C.94, „`MinivmAccMess()`“]) aus dem Mini-VoiceMail-System
(xref:minivm.adoc[Abschnitt 13.7, „Mini-VoiceMail (MiniVM)“]).

Mögliche _`optionen`_ sind:

`b`:: Ansage für "besetzt" (_busy_)
`u`:: Ansage für "nicht erreichbar" (_unavailable_)
`s`:: das Abspielen der Anleitung zum Hinterlassen einer Nachricht überspringen (_skip_)

(Kombinationen sind möglich, aber `b` und
`u` zusammen anzugeben ist natürlich sinnlos.) Falls der
Benutzer eine temporäre Ansage gesetzt hat, wird diese abgespielt, also
`b` oder `u` ignoriert.

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'MinivmGreet' =-

[Synopsis]
Play Mini-Voicemail prompts

[Description]
MinivmGreet(username@domain[,options]):
This application is part of the Mini-Voicemail system, configured in minivm.conf.
MinivmGreet() plays default prompts or user specific prompts for an account.
Busy and unavailable messages can be choosen, but will be overridden if a temporary
message exists for the account.

Result is given in channel variable MINIVM_GREET_STATUS
The possible values are: SUCCESS | USEREXIT | FAILED

Options:
b - Play the 'busy' greeting to the calling party.
s - Skip the playback of instructions for leaving a message to the
calling party.
u - Play the 'unavailable greeting.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-minivmaccmess.adoc[Abschnitt C.94, „`MinivmAccMess()`“], xref:applications-minivmdelete.adoc[Abschnitt C.95, „`MinivmDelete()`“], xref:applications-minivmnotify.adoc[Abschnitt C.97, „`MinivmNotify()`“], xref:applications-minivmrecord.adoc[Abschnitt C.98, „`MinivmRecord()`“], xref:functions-minivmaccount.adoc[Abschnitt D.64, „`MINIVMACCOUNT()`“], xref:functions-minivmcounter.adoc[Abschnitt D.65, „`MINIVMCOUNTER()`“]
