[[applications-transfer]]
= `Transfer()`

Übermittelt den Anruf zu einer anderen Extension.

[source]
----
Transfer([Technologie/]Ziel[,Optionen])
----

Verlangt die Übermittlung des Anrufers zu einer gegebenen
Extension. Wird `Technologie` (`SIP`,
`IAX2` etc.) angegeben, werden nur Anrufe der gleichen
Technologie transferiert. Bei SIP-Kanälen, die noch nicht beantwortet
wurden, geschieht das mittels einer 302-`REDIRECT`-Nachricht an
den Anrufer, bei beantworteten SIP-Kanälen mit `REFER`. Das Ziel
kann auch z. B. `123456@sip.provider.tld` sein.

Mit der Option `j` wird zur Priorität n+101 gesprungen,
falls der Transfer-Versuch fehlschlägt.

Setzt die Channel-Variable `TRANSFERSTATUS` auf
`SUCCESS` (Transfer erfolgreich), `FAILURE` (Transfer
fehlgeschlagen) oder `UNSUPPORTED` (vom Channel nicht
unterstützt).

[source]
----
; Anrufe an Extension 123 zur Extension 130 umleiten:
exten => 123,1,Transfer(130)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Transfer' =-

[Synopsis]
Transfer caller to remote extension

[Description]
Transfer([Tech/]dest[|options]): Requests the remote caller be transferred
to a given destination. If TECH (SIP, IAX2, LOCAL etc) is used, only
an incoming call with the same channel technology will be transfered.
Note that for SIP, if you transfer before call is setup, a 302 redirect
SIP message will be returned to the caller.

The result of the application will be reported in the TRANSFERSTATUS
channel variable:
SUCCESS Transfer succeeded
FAILURE Transfer failed
UNSUPPORTED Transfer unsupported by channel driver
The option string many contain the following character:
'j' -- jump to n+101 priority if the channel transfer attempt
fails

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Transfer caller to remote extension

[Description]
- Transfer([Tech/]dest[|options]): Requests the remote caller be transferred
+ Transfer([Tech/]dest): Requests the remote caller be transferred
to a given destination. If TECH (SIP, IAX2, LOCAL etc) is used, only
an incoming call with the same channel technology will be transfered.
Note that for SIP, if you transfer before call is setup, a 302 redirect
@@ -15,6 +15,3 @@
SUCCESS Transfer succeeded
FAILURE Transfer failed
UNSUPPORTED Transfer unsupported by channel driver
- The option string many contain the following character:
- 'j' -- jump to n+101 priority if the channel transfer attempt
- fails
