[[applications-gosub]]
= `Gosub()`

Springt zu einer bestimmten Priorität, Extension und einem
bestimmten Context (mit der Möglichkeit der Rückkehr).

[source]
----
Gosub([[Context,]Extension,]Priorität)
----

[source]
----
Gosub(benannte_Priorität)
----

Springt wie `Goto()` im Dialplan, erlaubt es dem
Unterprogramm aber, mit `Return()` zurückzukehren.

Gibt 0 zurück oder -1, wenn das Sprungziel ungültig ist.

[source]
----
exten => 123,1,Gosub(cid-setzen)
exten => 123,n,Dial(SIP/${EXTEN})

exten => 123,10(cid-setzen),Set(CALLERID(all)=Apfelmus GmbH <012345678>)
exten => 123,n,Return()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'Gosub' =-

[Synopsis]
Jump to label, saving return address

[Description]
Gosub([[context|]exten|]priority)
Jumps to the label specified, saving the return address.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,5 +4,5 @@
Jump to label, saving return address

[Description]
- Gosub([[context|]exten|]priority)
- Jumps to the label specified, saving the return address.
+ Gosub([[context,]exten,]priority[(arg1[,...][,argN])]):
+ Jumps to the label specified, saving the return address.

.Siehe auch
xref:applications-gosubif.adoc[Abschnitt C.64, „`GosubIf()`“], xref:applications-goto.adoc[Abschnitt C.65, „`Goto()`“], xref:applications-gotoif.adoc[Abschnitt C.66, „`GotoIf()`“],
xref:applications-return.adoc[Abschnitt C.137, „`Return()`“], xref:applications-macro.adoc[Abschnitt C.81, „`Macro()`“], xref:applications-stackpop.adoc[Abschnitt C.170, „`StackPop()`“],
xref:extensions.ael.adoc#ael-macros[„Makros (_macros_)“]
