[[applications-sendimage]]
= `SendImage()`

Sendet eine Bilddatei.

[source]
----
SendImage(Dateiname[,Optionen])
----

Sendet eine Bilddatei auf einem Channel. Falls die Übermittlung von
Bildern unterstützt wird und die Übertragung fehlschlägt, wird aufgelegt.
Ansonsten wird bei der nächsten Priorität fortgefahren. Mit der Option
`j` wird, wenn der Channel keine Bildübertragung unterstützt, zur
Priorität n+101 gesprungen.

Liefert 0 zurück, wenn das Bild fehlerfrei übertragen wurde oder
der Channel eine Bildübertragung nicht unterstützt, sonst -1. Setzt die
Channel-Variable `SENDIMAGESTATUS` entweder auf `OK`
(Erfolg) oder auf `NOSUPPORT` (nicht unterstützt).

[source]
----
exten => 123,1,SendImage(logo.jpg)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SendImage' =-

[Synopsis]
Send an image file

[Description]
SendImage(filename): Sends an image on a channel.
If the channel supports image transport but the image send
fails, the channel will be hung up. Otherwise, the dialplan
continues execution.
The option string may contain the following character:
'j' -- jump to priority n+101 if the channel doesn't support image transport
This application sets the following channel variable upon completion:
SENDIMAGESTATUS The status is the result of the attempt as a text string, one of
OK | NOSUPPORT

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -5,11 +5,8 @@

[Description]
SendImage(filename): Sends an image on a channel.
- If the channel supports image transport but the image send
- fails, the channel will be hung up. Otherwise, the dialplan
- continues execution.
- The option string may contain the following character:
- 'j' -- jump to priority n+101 if the channel doesn't support image transport
- This application sets the following channel variable upon completion:
- SENDIMAGESTATUS The status is the result of the attempt as a text string, one of
- OK | NOSUPPORT
+ Result of transmission will be stored in SENDIMAGESTATUS
+ channel variable:
+ SUCCESS Transmission succeeded
+ FAILURE Transmission failed
+ UNSUPPORTED Image transmission not supported by channel

.Siehe auch
xref:applications-sendtext.adoc[Abschnitt C.147, „`SendText()`“], xref:applications-sendurl.adoc[Abschnitt C.148, „`SendURL()`“]
