[[applications-cut]]
= `Cut()`

Zerteilt den String in einer Variablen anhand eines
Trennzeichens.

[source]
----
Cut(neueVariable=Variable,Trennzeichen,Feld)
----

[IMPORTANT]
====
`Cut()` ist ab Asterisk 1.4 nicht mehr vorhanden
und wurde durch die Funktion `CUT()` (xref:functions-cut.adoc[Abschnitt D.16, „`CUT()`“]) ersetzt.
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'Cut' =-

[Synopsis]
Splits a variable's contents using the specified delimiter

[Description]
Cut(newvar=varname,delimiter,fieldspec): This application will split the
contents of a variable based on the given delimeter and store the result in
a new variable.
Parameters:
newvar - new variable created from result string
varname - variable you want cut
delimiter - defaults to '-'
fieldspec - number of the field you want (1-based offset)
may also be specified as a range (with -)
or group of ranges and fields (with &)
This application has been deprecated in favor of the CUT function.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-cut.adoc[Abschnitt D.16, „`CUT()`“]
