[[applications-minivmdelete]]
= `MinivmDelete()`

Nachricht in Mini-VoiceMail löschen.

[source]
----
MinivmDelete(Dateiname)
----

Löscht die angegebene Datei _`Dateiname`_ im
Mini-VoiceMail-System (xref:minivm.adoc[Abschnitt 13.7, „Mini-VoiceMail (MiniVM)“]).

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'MinivmDelete' =-

[Synopsis]
Delete Mini-Voicemail voicemail messages

[Description]
MinivmDelete(filename):
This application is part of the Mini-Voicemail system, configured in minivm.conf.
It deletes voicemail file set in MVM_FILENAME or given filename.

Result is given in channel variable MINIVM_DELETE_STATUS
The possible values are: SUCCESS | FAILED
FAILED is set if the file does not exist or can't be deleted.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-minivmaccmess.adoc[Abschnitt C.94, „`MinivmAccMess()`“], xref:applications-minivmgreet.adoc[Abschnitt C.96, „`MinivmGreet()`“], xref:applications-minivmnotify.adoc[Abschnitt C.97, „`MinivmNotify()`“], xref:applications-minivmrecord.adoc[Abschnitt C.98, „`MinivmRecord()`“], xref:functions-minivmaccount.adoc[Abschnitt D.64, „`MINIVMACCOUNT()`“], xref:functions-minivmcounter.adoc[Abschnitt D.65, „`MINIVMCOUNTER()`“]
