[[applications-controlplayback]]
= `ControlPlayback()`

Spielt eine Datei ab und kann diese auch schnell vor- und
zurückspulen.

[source]
----
ControlPlayback(Datei[,skipms[,ffchar[,rewchar[,stopchar[,pausechar]]]]])
----

Spielt die angegebene Datei ab und ermöglicht es dem Anrufer, sich
durch Betätigen der Tasten `ffchar` und `rewchar` in
dieser Datei vorwärts und rückwärts zu bewegen. Als Standardeinstellung
können die Tasten `#` und * zum Vor- und Zurückspulen der Datei
verwendet werden. Ist `stopchar` spezifiziert, hält die Anwendung
die Wiedergabe an, wenn die `stopchar`-Taste gedrückt wird.
Existiert die Datei nicht, geht die Anwendung zu Priorität n+101 über, falls
diese vorhanden ist.

Die `skipms`-Option gibt an, wie weit mit jedem Drücken
von `ffchar` oder `rewchar` in der Datei vor- bzw.
zurückgesprungen wird.

Die `pausechar-Option` kann ebenfalls spezifiziert
werden. Sie erlaubt es, die Wiedergabe der Datei vorübergehend anzuhalten
(Pause). Erneutes Drücken von `pausechar` setzt die Wiedergabe
der Datei dann fort.

Gibt -1 zurück, falls der Channel während der Wiedergabe aufgelegt
wurde.

[source]
----
; dem Anrufer "sinfonie" vorspielen mit Steuerungsmöglichkeit:
exten => 123,1,ControlPlayback(sinfonie,5000,#,*,5,0)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'ControlPlayback' =-

[Synopsis]
Play a file with fast forward and rewind

[Description]
ControlPlayback(file[|skipms[|ff[|rew[|stop[|pause[|restart|options]]]]]]]):
This application will play back the given filename. By default, the '*' key
can be used to rewind, and the '#' key can be used to fast-forward.
Parameters:
skipms - This is number of milliseconds to skip when rewinding or
fast-forwarding.
ff - Fast-forward when this DTMF digit is received.
rew - Rewind when this DTMF digit is received.
stop - Stop playback when this DTMF digit is received.
pause - Pause playback when this DTMF digit is received.
restart - Restart playback when this DTMF digit is received.
Options:
j - Jump to priority n+101 if the requested file is not found.
This application sets the following channel variable upon completion:
CPLAYBACKSTATUS - This variable contains the status of the attempt as a text
string, one of: SUCCESS | USERSTOPPED | ERROR

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Play a file with fast forward and rewind

[Description]
- ControlPlayback(file[|skipms[|ff[|rew[|stop[|pause[|restart|options]]]]]]]):
+ ControlPlayback(file[,skipms[,ff[,rew[,stop[,pause[,restart,options]]]]]]]):
This application will play back the given filename. By default, the '*' key
can be used to rewind, and the '#' key can be used to fast-forward.
Parameters:
@@ -16,7 +16,11 @@
pause - Pause playback when this DTMF digit is received.
restart - Restart playback when this DTMF digit is received.
Options:
- j - Jump to priority n+101 if the requested file is not found.
- This application sets the following channel variable upon completion:
+ o(#) - Start at # ms from the beginning of the file.
+ This application sets the following channel variables upon completion:
CPLAYBACKSTATUS - This variable contains the status of the attempt as a text
string, one of: SUCCESS | USERSTOPPED | ERROR
+ CPLAYBACKOFFSET - This contains the offset in ms into the file where
+ playback was at when it stopped. -1 is end of file.
+ CPLAYBACKSTOPKEY - If the playback is stopped by the user this variable contains
+ the key that was pressed.

.Siehe auch
xref:applications-playback.adoc[Abschnitt C.117, „`Playback()`“], xref:applications-background.adoc[Abschnitt C.13, „`Background()`“]
