[[applications-nbscat]]
= `NBScat()`

Wiedergabe eines lokalen NBS-Streams.

[source]
----
NBScat()
----

Verwendet das `nbscat8k`-Programm, um den lokalen NBS
(Network Broadcast Sound)-Stream zu hören. (Schauen Sie sich das
`nbs`-Modul in Digiums CVS-Server an, um weitere
Informationen zu erhalten.) Der Anrufer kann durch Drücken einer beliebigen
Taste aussteigen.

Die Anwendung liefert -1, falls aufgelegt wird, ansonsten wird sie
endlos ausgeführt.

[source]
----
exten => 123,1,Answer()
exten => 123,n,NBScat()
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'NBScat' =-

[Synopsis]
Play an NBS local stream

[Description]
NBScat: Executes nbscat to listen to the local NBS stream.
User can exit by pressing any key
.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,6 +4,5 @@
Play an NBS local stream

[Description]
- NBScat: Executes nbscat to listen to the local NBS stream.
- User can exit by pressing any key
- .
+ NBScat(): Executes nbscat to listen to the local NBS stream.
+ User can exit by pressing any key.
