[[applications-macroif]]
= `MacroIf()`

Startet verschiedene Makros in Abhängigkeit von einer
Expression.

[source]
----
MacroIf(Ausdruck?MacronameA[,argA1][:MacronameB[,argB1]])
----

Ruft bedingt ein Makro auf, wobei ein Ausdruck im Stil von
`GotoIf()` ausschlaggebend ist.

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'MacroIf' =-

[Synopsis]
Conditional Macro Implementation

[Description]
MacroIf(<expr>?macroname_a[|arg1][:macroname_b[|arg1]])
Executes macro defined in <macroname_a> if <expr> is true
(otherwise <macroname_b> if provided)
Arguments and return values as in application macro()

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -4,7 +4,7 @@
Conditional Macro Implementation

[Description]
- MacroIf(<expr>?macroname_a[|arg1][:macroname_b[|arg1]])
+ MacroIf(<expr>?macroname_a[,arg1][:macroname_b[,arg1]])
Executes macro defined in <macroname_a> if <expr> is true
(otherwise <macroname_b> if provided)
- Arguments and return values as in application macro()
+ Arguments and return values as in application Macro()

.Siehe auch
xref:applications-macro.adoc[Abschnitt C.81, „`Macro()`“], xref:applications-gotoif.adoc[Abschnitt C.66, „`GotoIf()`“], xref:applications-gosubif.adoc[Abschnitt C.64, „`GosubIf()`“]
