[[applications-saydigits]]
= `SayDigits()`

Spricht die übergebenen Ziffern.

[source]
----
SayDigits(Ziffern)
----

Spricht die übergebenen Ziffern unter Verwendung der aktuellen
Spracheinstellung für den Channel. Die Sprache kann mit der Funktion
`LANGUAGE()` geändert werden.

[source]
----
exten => 123,1,SayDigits(1234)
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.4:
-= Info about application 'SayDigits' =-

[Synopsis]
Say Digits

[Description]
SayDigits(digits): This application will play the sounds that correspond
to the digits of the given number. This will use the language that is currently
set for the channel. See the LANGUAGE function for more information on setting
the language for the channel.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-sayalpha.adoc[Abschnitt C.139, „`SayAlpha()`“], xref:applications-saynumber.adoc[Abschnitt C.141, „`SayNumber()`“], xref:applications-sayphonetic.adoc[Abschnitt C.142, „`SayPhonetic()`“]
