[[applications-meetmechanneladmin]]
= `MeetMeChannelAdmin()`

Administration von MeetMe-Konferenzen (kanalspezifisch)

[source]
----
MeetMeChannelAdmin(channel,command)
----

Führt den angegebenen MeetMe-Administrationsbefehl für den
angegebenen _`channel`_ aus. Arbeitet wie
`MeetMeAdmin()`, erwartet aber die Angabe eines Kanals
statt einer Konferenznummer.

Der Befehl _`command`_ kann einer der folgenden
sein:

`k`:: Wirft den durch den Kanal angegebenen Teilnehmer aus der Konferenz.
`M`:: Schaltet den durch den Kanal angegebenen Teilnehmer stumm.
`m`:: Hebt die Stummschaltung (durch `M`) auf.

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Applikation in Asterisk 1.6:
-= Info about application 'MeetMeChannelAdmin' =-

[Synopsis]
MeetMe conference Administration (channel specific)

[Description]
MeetMeChannelAdmin(channel,command): Run admin command for a specific
channel in any coference.
'k' -- Kick the specified user out of the conference he is in
'm' -- Unmute the specified user
'M' -- Mute the specified user

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-meetme.adoc[Abschnitt C.89, „`MeetMe()`“], xref:applications-meetmeadmin.adoc[Abschnitt C.90, „`MeetMeAdmin()`“]
