[[applications-setcidname]]
= `SetCIDName()`

Setzt den Caller-ID-Namen.

[source]
----
SetCIDName(Name)
----

[IMPORTANT]
====
`SetCIDName()` ist ab Asterisk 1.4 nicht mehr
vorhanden und wurde durch die Funktion `CALLERID()`
(xref:functions-callerid.adoc[Abschnitt D.8, „`CALLERID()`“]) ersetzt:

[source]
----
Set(CALLERID(name)=Name)
----
====

.Asterisk-Versionen:
————————| *1.2* | | | | |

.Interner Hilfetext zu dieser Applikation in Asterisk 1.2:
-= Info about application 'SetCIDName' =-

[Synopsis]
Set CallerID Name

[Description]
SetCIDName(cname[|a]): Set Caller*ID Name on a call to a new
value, while preserving the original Caller*ID number. This is
useful for providing additional information to the called
party.
SetCIDName has been deprecated in favor of the function
CALLERID(name)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-setcidnum.adoc[Abschnitt C.156, „`SetCIDNum()`“], xref:functions-callerid.adoc[Abschnitt D.8, „`CALLERID()`“]
