[[blf-hints]]
= BLF, Hints, Pickup
:description: BLF, Hints und Pickup in Asterisk: Besetztlampen und Anruf-Heranholen.

In diesem Kapitel:

* xref:blf-leds.adoc[Ansteuerung der LEDs]
** xref:blf-leds.adoc#blf-pjsip.conf[pjsip.conf]
** xref:blf-leds.adoc#blf-hints[Hints]
* xref:blf-subscriptions.adoc[Verfahren für SIP-_Subscriptions_]
* xref:blf-telefon-konfiguration.adoc[Konfiguration der Telefone für BLF]
* xref:blf-test.adoc[Test der Hints]
* xref:blf-pickup.adoc[Heranholen eines Anrufs („Pickup“)]
** xref:blf-pickup.adoc#blf-pickup-extensions.conf[extensions.conf für Pickup]
** xref:blf-pickup.adoc#blf-pickup-telefon[Konfiguration des Telefons für Pickup]
** xref:blf-pickup.adoc#blf-group-pickup[Heranholen von einer Gruppe]
* xref:blf-device-state.adoc[Gezielte Ansteuerung der LEDs]

.Beschreibung des Leistungsmerkmals BLF
Besetztlampenfelder (_Busy Lamp
Field_, BLF) sind ein weit verbreitetes Feature
traditioneller Telefonanlagen. Dabei handelt es sich um LEDs oder
LCD-Anzeigen und zugehörige Tasten am Telefon, mit denen die Nebenstellen
von einzelnen Kollegen oder ganzen Gruppen überwacht (im Sinne von
„beobachtet“) werden. Klingelt ein überwachtes Telefon, dann
blinkt am eigenen Apparat die entsprechende LED.footnote:[Bei einigen Anlagen sieht man sogar die Rufnummer des Anrufers. Dies ist jedoch -- so viel sei vorab gesagt – bei Asterisk nicht möglich bzw. nur mit einem Patch möglich (siehe u. a. http://bugs.digium.com/view.php?id=5014[_Asterisk Bug 5014_\]).] Ist der überwachte Teilnehmer im Gespräch, so leuchtet die
LED am überwachenden Gerät dauerhaft. Ansonsten ist die LED aus.footnote:[Daneben gibt es je nach Anlage noch weitere "Blink-Kadenzen", z. B. ein langsameres Blinken, wenn der andere Teilnehmer sein Gespräch auf "Halten" gestellt hat.]Was das Drücken der Taste bewirkt, hängt vom Status des
anderen Teilnehmers ab. Ist der Kollege frei, so wird ein normaler Anruf
aufgebaut. Wenn aber sein Telefon klingelt (eigene LED blinkt), so kann
man durch Drücken der Tastefootnote:[Je nach Telefonanlage geht das nicht durch Tastendruck, sondern durch die (umständliche) Eingabe eines Feature-Codes (`*`_`sonstwas`_).] das eingehende Gespräch zum eigenen Apparat
heranholen.

Wir wollen uns im Folgenden damit beschäftigen, wie man diese
Funktionen mit Asterisk für SIP-Telefone nachbauen kann.
