[[callingcard]]
= Anwendungsbeispiel Calling-Card
:description: Calling-Card-System mit Asterisk und AstDB als Guthabenverwaltung.

In der Apfelmus GmbH sollen private Gespräche über eine Calling-Card
abgerechnet werden. Diese wird vom Hausmeister über sein Telefon virtuell
aufgeladen (durch Anwahl der internen Servicenummer 88, gefolgt von der
3-stelligen Durchwahl und vom gewünschten Geldbetrag in Euro).footnote:[Um das Beispiel möglichst einfach zu halten, wird nicht der Fall besprochen, dass auf ein bereits bestehendes Calling-Card-Konto ein weiterer Betrag eingezahlt wird (also eine Addition vollzogen werden muss). Ebenfalls nicht behandelt wird die Möglichkeit, dass ein Mitarbeiter von einem anderen Telefon ein privates Gespräch führen könnte.] Die Gespräche werden zu einem Pauschalpreis von 1 Euro pro
Gespräch abgerechnet. Diese privaten Gespräche werden über die interne
Servicenummer 99, gefolgt von der Zielrufnummer, geführt. Dabei ist zu
beachten, dass bei einem Besetzt (_busy_) kein
Geldbetrag vom Konto abgebucht wird. Die interne Rufnummer 98 kann dazu
benutzt werden, den aktuellen Betrag auf dem Calling-Card-Konto
abzurufen.

[source]
----
[from-hausmeister]
; Aufladen der virtuellen Calling-Card
;
exten => _88XXX.,1,Answer()
 same => n,Set(DB(CallingCard/${EXTEN:2:3})=${EXTEN:5})
 same => n,SayNumber(${EXTEN:5})
 same => n,NoOp(CallingCard fuer ${EXTEN:2:3} mit ${EXTEN:5} aufgeladen.)
 same => n,Hangup()

[from-intern]
; private Gespräche
;
exten => _99.,1,GotoIf($[${DB(CallingCard/${CALLERID(num)})} > 0]?dial:leer)
 same => n(dial),Set(DB(CallingCard/${CALLERID(num)})=$[${DB(CallingCard/${CALLERID(num)})} - 1])
 same => n,Dial(Local/${EXTEN:2}@from-intern)
 same => n,GotoIf($["${DIALSTATUS}" = "ANSWER"]?ende:refund)
 same => n(refund),Set(DB(CallingCard/${CALLERID(num)})=$[${DB(CallingCard/${CALLERID(num)})} + 1])
 same => n,Goto(ende)

 same => n(leer),NoOp(CallingCard Konto ${CALLERID(num)} ist leer.)
 same => n,Answer()
 same => n,SayNumber(0)

 same => n(ende),Hangup()

; Mit der 98 kann der aktuelle Kontostand abgefragt werden.
;
exten => 98,1,Answer()
 same => n,SayNumber(${DB(CallingCard/${CALLERID(num)})})
 same => n,Hangup()
----
