[[call-transfer]]
= Transfer von Gesprächen
:description: Blind-Transfer und Attended-Transfer in Asterisk: Gespräche an andere Nebenstellen übergeben.

Wenn Sie die Applikation `Dial()` ohne weitere
Optionen (bzw. Flags) benutzen, können Sie bestehende Gespräche nicht zu
einem anderen Telefon transferieren. Dieses Feature muss explizit bei der
`Dial()`-Applikation mit der Option `t`,
`T` oder `tT` aktiviert werden. Die vollständige Liste aller `Dial()`-Optionen steht in der
offiziellen Dokumentation. Wenn Sie sowohl dem Anrufer wie auch dem
Angerufenen das Transferieren von Gesprächen erlauben wollen, müssen
Sie die Optionen `tT` benutzen.

Beispiel:

[source]
----
exten => _2XXX,1,Dial(PJSIP/${EXTEN},30,tT)
----

[[blind-transfer]]
== Blind Transfer

Der Begriff „Blind Transfer" wird für Transfers benutzt, die von
einem Teilnehmer ohne Rückfrage zu einem anderen Teilnehmer gemacht
werden. Der Default-Trigger ist die Raute-Taste (`#`), gefolgt von
der Zielrufnummer. Um ein Gespräch also zum Telefon `2323`
weiterzuleiten, drücken Sie `#2323`.

In der Datei `/etc/asterisk/features.conf` lässt sich diese
Ziffernkombination im Context `[featuremap]` anpassen — hier z. B. auf
die längere Variante `#1`:

[source]
----
[featuremap]
blindxfer => #1         ; Blind transfer (Default: #)
----

[[attended-transfer]]
== Attended Transfer

Im Gegensatz zum „Blind Transfer“ kann der eine
Teilnehmer beim „Attended Transfer“ mit der Gegenstelle vor
dem Transfer erst noch sprechen, und erst nach dem Auflegen wird das
Gespräch weitergeleitet. Ein Attended Transfer wird per Default durch
die Eingabe von `*2` eingeleitet, gefolgt von der
gewünschten Zielrufnummer.

In der Datei `/etc/asterisk/features.conf` kann
man im Context `[featuremap]` die Ziffernkombination für das
Einleiten eines Attended Transfers anpassen:

[source]
----
[featuremap]
atxfer => *2                    ; Attended transfer
----

Sollten Sie für Ihre Geräte Call-Limits verwenden (Anzahl
gleichzeitig erlaubter Gespräche), müssen Sie beachten, dass ein
Attended Transfer vorübergehend 2 Leitungen benötigt.
