[[danksagungen-von-stefan-wintermeyer]]
= Danksagungen von Stefan Wintermeyer

Am meisten möchte ich mich bei meinem Lektor Boris Karnikowski
bedanken. Ohne seine Geduld wäre schon das erste Buch nicht möglich
gewesen, und auch beim zweiten Buch wurde der Veröffentlichungstermin
Schritt für Schritt um „geringfügige“ 12 Monate nach hinten
geschoben. Weiterhin bin ich glücklich darüber, dass dieses Buch unter
einer sehr offenen Lizenz (der GNU FDL) veröffentlicht wurde und schon vor
der Veröffentlichung im Web online zu lesen war. Es gibt nicht viele
Verlage und Lektoren, die dafür den Mut aufbringen. Danke, Boris!

Weiterhin möchte ich mich bei meinen AMOOMA-Kollegen Peter Kozak und
Sören Sprenger bedanken. Und ganz besonders natürlich bei Philipp Kempgen.
Ohne Euch wäre das Buch in dieser Tiefe und Breite überhaupt nicht
möglich.

Friederike Daenecke hat bei der Lektorierung des Buches ein kleines
Wunder vollbracht. Sie hat das ganze Buch in weniger als drei Wochen
komplett durchgearbeitet. Nur dadurch konnten wir den
Veröffentlichungstermin Mai 2009 überhaupt einhalten.

Kevin Fleming von Digium hat uns oft bei Fragen und Problemen
unkompliziert und schnell geholfen.

Das Gleiche gilt für das Sangoma-Team. Besonders bedanken möchte ich
mich dort bei Konrad Hammel und Doug Vilim.

Und natürlich geht ein besonders liebes Danke an meine Frau, ohne
deren Unterstützung ich diese vielen Projekte gar nicht bewältigen
könnte.
