[[definition-channel]]
= Channels

Ein Channel ist die Verbindung zwischen zwei Punkten (in unserem
Fall sind das meistens menschliche Gesprächsteilnehmer). Es gibt folgende
Channel-Arten:

* Agent
+
Ein ACD-Agent-Channel
* CAPI
+
Ein ISDN-Channel
* Console
+
Ein Linux-Konsolen-Client-Treiber für Soundkarten, die mit OSS
oder ALSA angesprochen werden können
* H.323
+
Ein VoIP-Protokoll
* IAX
+
Ein VoIP-Protokoll
+
[NOTE]
====
Prinzipiell gibt es zwei Versionen von IAX (1 und 2). Wer
heute von IAX spricht, meint eigentlich immer IAX2 (also die
Version 2).
====
* Local
+
Ein Loopback in einen anderen Context
* MGCP
+
Ein VoIP-Protokoll
* mISDN
+
Ein ISDN-Channel
* NBS
+
Network Broadcast Sound
* phone
+
Linux Telephony Channel
* SIP
+
Ein VoIP-Protokoll
* Skinny
+
Ein VoIP-Protokoll
* vISDN
+
Ein ISDN-Channel
* VOFR
+
Voice over frame relay Adtran style
* VPB
+
Verbindung von normalen Telefonanschlüssen mit
Voicetronix-Karten
* Zap
+
Verbindung von normalen Telefonanschlüssen mit Digium-Karten.
Wird aber auch häufig für Karten anderer Hersteller benutzt.

In den meisten Beispielen in diesem Buch wird immer von
SIP-Verbindungen ausgegangen. Der Grund dafür ist einfach: Zurzeit gibt es
sehr viel mehr SIP- als z. B. IAX-fähige VoIP-Telefone. In diesem Kapitel
werden diese zwei wichtigen Protokolle im Einzelnen beschrieben. Wer will,
kann dieses Kapitel aber überspringen und bei konkreten Fragen zu
bestimmten Parametern hier nachschlagen.
