[[deutsche-sprachbausteine]]
= Deutsche Sprachbausteine

Bei einer Standardinstallation werden im Verzeichnis
`/var/lib/asterisk/sounds/` nur die
Original-Sprachbausteine auf Englisch abgelegt. Zum Redaktionsschluss
dieses Buches gab es von Digium alternativ noch französische und spanische
Prompts (_Prompt_ ist der Asterisk-Begriff für
_Sprachbaustein_). Allerdings werden von Digium keine
deutschen Sprachprompts angeboten. Diese müssen Sie von Drittanbietern in
Deutschland herunterladen.

[[deutsche-sprachbausteine-download]]
== Download und Installation deutscher Sprachprompts

Verfügbare deutsche Sprachbausteine:

[[sprachprompts-amooma]]
=== Sprachbausteine der AMOOMA GmbH

Die AMOOMA GmbH stellt unter der URL http://www.amooma.de/asterisk/sprachbausteine/
deutsche Sprachbausteine für die Asterisk-Versionen 1.4 und 1.6 zum
Download zur Verfügung. Diese sind in mehreren Formaten abrufbar und
stehen unter der GPL. Bitte entpacken Sie die Sprachprompts, und
kopieren Sie diese in das Verzeichnis
`/var/lib/asterisk/sounds/de`.

Als Besonderheit kann man sich auch eigene Sprachbausteine
online generieren lassen (siehe http://www.amooma.de/tts/
).

[[sprachprompts-pforzheim]]
=== Sprachbausteine der Stadt Pforzheim

Die Stadt Pforzheim hatte unter http://www.pforzheim.de/asterisk/vprompts.html
deutsche Sprachbausteine für die alte Asterisk-Version 1.2 zum
Download zur Verfügung gestellt.

[IMPORTANT]
====
Diese Sprachbausteine sind nicht mehr verfügbar.
====

[[deutsche-sprachbausteine-konfiguration]]
== Konfiguration der deutschen Prompts

Die deutschen Sprachbausteine können in der Konfigurationsdatei
der benutzten Technologie (z. B. `sip.conf` für SIP)
mit dem Parameter _`language=de`_ aktiviert werden.
Dies funktioniert entweder global oder nur für einzelne Telefone.

Beispiel `sip.conf`:

[source]
----
[general]
; fuer alle im System
language = de

[2000]
type = friend
secret = 1234
host = dynamic
context = from-sip
; nur fuer die 2000
language = de
----

[[verzeichnisstruktur-sprachbausteine]]
== Verzeichnisstruktur der Sprachbausteine

Per Default liegen alle Sprachbausteine im Verzeichnis
`/var/lib/asterisk/sounds/`. Darin gibt es
Unterverzeichnisse für spezielle Sprachprompts wie
`digits/` für Zahlen, Uhrzeiten und Wochentage.
Dieses Verzeichnis sieht dann wie folgt aus:

[source,shell]
----
big-island:~# ls /var/lib/asterisk/sounds/digits/
0.gsm   60.gsm       h-13.gsm     mon-1.gsm
1.gsm   7.gsm        h-14.gsm     mon-10.gsm
10.gsm  70.gsm       h-15.gsm     mon-11.gsm
11.gsm  8.gsm        h-16.gsm     mon-2.gsm
12.gsm  80.gsm       h-17.gsm     mon-3.gsm
13.gsm  9.gsm        h-18.gsm     mon-4.gsm
14.gsm  90.gsm       h-19.gsm     mon-5.gsm
15.gsm  a-m.gsm      h-2.gsm      mon-6.gsm
16.gsm  at.gsm       h-20.gsm     mon-7.gsm
17.gsm  day-0.gsm    h-3.gsm      mon-8.gsm
18.gsm  day-1.gsm    h-30.gsm     mon-9.gsm
19.gsm  day-2.gsm    h-4.gsm      oclock.gsm
2.gsm   day-3.gsm    h-5.gsm      oh.gsm
20.gsm  day-4.gsm    h-6.gsm      p-m.gsm
3.gsm   day-5.gsm    h-7.gsm      pound.gsm
30.gsm  day-6.gsm    h-8.gsm      star.gsm
4.gsm   dollars.gsm  h-9.gsm      thousand.gsm
40.gsm  h-1.gsm      hundred.gsm  today.gsm
5.gsm   h-10.gsm     million.gsm  tomorrow.gsm
50.gsm  h-11.gsm     minus.gsm    yesterday.gsm
6.gsm   h-12.gsm     mon-0.gsm
----

Sprachprompts anderer Sprachen (also nicht-englische
Sprachprompts) werden als Unterverzeichnisse mit den jeweiligen
Sprachkürzeln (`de` für Deutsch) abgespeichert. Deshalb gibt
es im Fall von Asterisk 1.2 sowohl ein Verzeichnis
`/var/lib/asterisk/sounds/de/` als auch ein
Verzeichnis
`/var/lib/asterisk/sounds/digits/de/`.

[[verzeichnisstruktur-sprachbausteine-1.4]]
=== Asterisk 1.4 und 1.6

Zum Glück verhalten sich Asterisk 1.4 und 1.6 nicht mehr so wie
1.2. Standardmäßig ist nun die Einstellung
`languageprefix=yes` in der Konfigurationsdatei
`/etc/asterisk/asterisk.conf` aktiviert. Mit dieser
Einstellung folgt die Verzeichnisstruktur der Idee, dass zuerst nach
der Sprache gruppiert wird, also alle Bausteine einer Sprache in einem
Verzeichnis liegen:

[source,shell]
----
/var/lib/asterisk/sounds/de/ 
/var/lib/asterisk/sounds/de/digits 
/var/lib/asterisk/sounds/de/wx
----

Dadurch lässt sich leicht ein
Verzeichnis für eine neue Sprache reinkopieren, während die Bausteine
sonst über mehrere Unterverzeichnisse verteilt wären.

[NOTE]
====
Wer +`make menuselect`+
zum Installieren von Sprachbausteinen benutzt, muss die Option
_`languageprefix=yes`_ in der
Konfigurationsdatei
`/etc/asterisk/asterisk.conf` setzen.
====
