[[dialplan-grundlagen]]
= Dialplan – die Grundlagen

In diesem Kapitel:

* xref:der-context.adoc[Context]
** xref:der-context.adoc#context-syntax[Syntax]
* xref:die-extension.adoc[Extension]
** xref:die-extension.adoc#extension-syntax[Syntax]
** xref:die-extension.adoc#grundlegende-applikationen[Grundlegende Applikationen]
** xref:die-extension.adoc#die-prioritaet[Priorität]
* xref:einleitung-regex.adoc[Pattern Matching]
** xref:einleitung-regex.adoc#regular-expression-syntax[Syntax]
** xref:einleitung-regex.adoc#dialplan-show[Testen mit `dialplan show`]
** xref:einleitung-regex.adoc#wann-matcht-welches-pattern[Wann matcht welches Pattern?]
* xref:includes-im-dialplan.adoc[Includes im Dialplan]
** xref:includes-im-dialplan.adoc#include-syntax[Syntax]
** xref:includes-im-dialplan.adoc#include-beispiel[Beispiel]
** xref:includes-im-dialplan.adoc#reihenfolge-beim-include[Die Reihenfolge beim Include]
** xref:includes-im-dialplan.adoc#include-zeitgesteuert[Includes zeitgesteuert]
* xref:apfelmus-exten-var.adoc[Die Variable ${EXTEN} und die Funktion ${CALLERID(num)}]
** xref:apfelmus-exten-var.adoc#systemvariable-exten[${EXTEN}]
** xref:apfelmus-exten-var.adoc#funktion-callerid-num[${CALLERID(num)}]

In diesem Kapitel beschäftigen wir uns mit den Grundlagen des
Dialplans. Wir benutzen das englische Wort _Dialplan_ und
nicht das deutsche Wort _Wählplan_, weil es auch
Asterisk-intern immer wieder benutzt wird.footnote:[Zur Definition des Begriffes _Dialplan_ gibt es in der Telefoniewelt immer wieder beinahe religiös anmutende Diskussionen. In diesem Buch wird das Wort _Dialplan_ in der im Asterisk-Umfeld üblichen Bedeutung verwendet.]

Im Verzeichnis `/etc/asterisk` gibt es zwei für den
Dialplan wichtige Dateien: zum einen die
`extensions.conf`, die den Dialplan noch in dem für die
Asterisk-Versionen 1.2, 1.4 und 1.6 von xref:glossar.adoc#glossar-digium[Digium] empfohlenen Prioritäten-Modell
abbildet, und zum anderen die `extensions.ael`, die einen neuen Weg
zur Beschreibung des Dialplans geht. AEL wird in einem gesonderten Kapitel in
diesem Buch besprochen (siehe xref:ael.adoc[Kapitel 7, _AEL_]). Wir beschäftigen uns
hier mit dem traditionellen Prioritäten-Modell, weil auch in der Version 1.4
und 1.6 bei jedem Starten von Asterisk die
`extensions.ael` automatisch (intern) in die alte Schreibweise
konvertiert wird.

[NOTE]
====
Auf die Frage „Soll ich lieber die
`.conf` oder die `.ael`
benutzen?“ gibt es aktuell von Digium die Antwort: „.conf
ist der Default-Weg.“
====
