[[die-wichtigsten-codecs]]
= Die wichtigsten Codecs

Mit dem Befehl `core show translation` bekommen Sie
eine Auflistung der in Ihrem System verfügbaren Codecs (das sind alle mit
einer Zahl). Die in Asterisk-Installationen gebräuchlichsten Codecs werden
in der folgenden Liste kurz besprochen:

* GSM
+
GSM ist ein Asterisk-Klassiker und uns allen von Handygesprächen
bekannt. Die Bandbreite beträgt 13,3 Kbit/s, und die Qualität ist in
Ordnung, wenn auch nicht überragend.
* iLBC
+
iLBC ist eine Art Geheimwaffe bei schmalen Bandbreiten. Die
Sprachqualität ist vergleichsweise gut, und die Bandbreite beschränkt
sich auf 13,3 bis 15 Kbps (je nach Framegröße). Skype benutzt eine
Abwandlung dieses Codecs. Das Problem mit iLBC ist aber seine
Rechenintensität. Deshalb wird er auch kaum von VoIP-Telefonen
unterstützt.
* G.711
+
G.711 ist ein weiterer Klassiker. G.711 (auch als al/alaw oder
ul/ulaw bezeichnet) ist allen deutschen Lesern von ISDN bekannt. Der
Codec bietet eine sehr gute Sprachqualität und benötigt 64 Kbps. Er
ist der Standard für alle Gespräche im Intranet und wird von den
meisten Firmen auch im Internet benutzt.
* G.722
+
Vielleicht löst G.722 irgendwann einmal G.711 ab. In seiner
höchsten Auflösung bietet er eine viel bessere Sprachqualität als
G.711 (also noch mal besser als ISDN) und benötigt dafür auch nur 64
Kbps. Leider wird er zurzeit noch nicht von vielen Telefonen
unterstützt.
* G.726
+
Bietet die gleiche Sprachqualität wie G.711, benötigt aber nur
die halbe Bandbreite (32 Kbps). Im Gegensatz zu G.711 wird nicht immer
die aktuelle Information, sondern nur die Differenz zum vorherigen
Sprachpaket übertragen. So kann mit halber Bandbreite die gleiche
Sprachqualität erreicht werden. G.726 ist nicht allzu rechenintensiv,
aber natürlich benötigt er etwas mehr Rechenleistung als G.711.
* G.729a
+
G.729a ist ein lizenzpflichtiger Codec, der mit 8 Kbps auskommt
und eine ähnlich gute Sprachqualität wie GSM bietet. Lizenzen für
Asterisk können bei http://www.digium.com[_Digium_]
gekauft werden. Er sticht weder durch Sprachqualität noch durch
Performance hervor.
+
G.729a ist in vielen VoIP-Telefonen verbaut und bietet damit
eine gute Möglichkeit, Bandbreite zu sparen. Ob dies heutzutage
sinnvoll ist, müssen Sie selbst entscheiden.
