[[digium-tdm400p-analog]]
= Installation der Digium TDM400p Analog-Karte

Dieses Kapitel beschreibt die Installation und Inbetriebnahme der
analogen Karte TDM400p von Digium.

[[digium-tdm400p-analog-installation]]
== Installation

Diese Installationsanleitung setzt ein frisch installiertes Debian
GNU/Linux 5.0 („Lenny“) voraus.

Wir empfehlen zur Installation das Netzwerkinstallations-CD-Image,
das ungefähr 150 MByte groß ist und unter http://www.debian.org/releases/lenny/debian-installer/
heruntergeladen werden kann. Eine Debian GNU/Linux-Installationsanleitung
finden Sie unter http://www.debian.org/releases/lenny/i386/
und ein allgemeines Anwenderhandbuch unter http://debiananwenderhandbuch.de/.

_Nach erfolgreicher Installation des Debian-Linux-Systems
melden Sie sich als Benutzer `root` am System an und führen Sie
die hier nachfolgend angegebenen Befehle aus. Bitte achten Sie darauf,
keinen Schritt auszulassen und die Schritte als Benutzer `root`
durchzuführen._

Als Erstes stellen Sie sicher, dass `aptitude` alle
aktuellen Paketlisten zur Verfügung hat:

[source,shell]
----
debian:~# aptitude update
OK   http://ftp.de.debian.org stable/main Packages
OK   http://ftp.de.debian.org stable/main Release
OK   http://security.debian.org stable/updates/main Packages
[...]
Paketlisten werden gelesen... Fertig
debian:~# 
----

Um sicherzugehen, dass alle Pakete auf dem neuesten Stand sind,
führen Sie noch ein Upgrade aus:

[source,shell]
----
debian:~# aptitude -y upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
----

Für den Fall, dass beim Upgrade der Pakete auch ein neuer Kernel
installiert wurde, müssen Sie jetzt das System mit
+`shutdown -r now`+ (oder mit
+`reboot`+) neu starten:

[source,shell]
----
debian:~# shutdown -r now

Broadcast message from root@debian (pts/0) (Mon Mar 23 17:42:04 2009):

The system is going down for reboot NOW!
----

Nach dem Booten loggen Sie sich bitte wieder als
`root` ein.

Jetzt müssen Sie noch ein paar Pakete nachinstallieren, damit das
spätere Kompilieren von Asterisk erfolgreich durchgeführt werden
kann:

[source,shell]
----
debian:~# aptitude -y install build-essential make openssl zlibc libkrb5-dev \
    libncurses5-dev libssl-dev zlib1g-dev
[...]
Die folgenden NEUEN Pakete werden installiert:
  comerr-dev libkadm55 libkrb5-dev libncurses5-dev 
  libssl-dev openssl zlib1g-dev zlibc
[...]
debian:~# 
----

Zum Kompilieren benötigen Sie jetzt noch die zum Kernel passenden
Header-Dateien. Diese können wie folgt nachinstalliert werden:

[source,shell]
----
debian:~# aptitude -y install linux-headers-`uname -r`
[...]
Die folgenden NEUEN Pakete werden installiert:
  linux-headers-2.6.26-1-common linux-headers-2.6.26-1-686 
  kernel-kbuild-2.6-26 linux-libc-dev
[...]
debian:~# 
----

Auf der Asterisk-Homepage http://www.asterisk.org/ finden Sie
die notwendigen Quellen, um Asterisk zu kompilieren. Nehmen Sie bitte eine
*stabile* und keine Entwickler-Version, und
laden Sie diese in das Verzeichnis `/usr/src/`
herunter:

[source,shell]
----
debian:~# cd /usr/src/
debian:/usr/src# wget http://downloads.digium.com/pub/asterisk/asterisk-1.4-current.tar.gz
[...]
11:09:07 (9.02 MB/s) - »asterisk-1.4-current.tar.gz« gespeichert [11613305/11613305]
----

Als Nächstes laden Sie den dazugehörigen DAHDI-Treiber:

[source,shell]
----
debian:/usr/src# wget http://downloads.digium.com/pub/telephony/dahdi-linux/dahdi-linux-current.tar.gz
[...]
11:10:50 (10.51 MB/s) - »dahdi-linux-current.tar.gz« gespeichert [1251822/1251822]
----

Zu dem DAHDI-Treiber gehören noch die passenden DAHDI-Tools. Bitte
laden Sie diese also auch noch herunter:

[source,shell]
----
debian:/usr/src# wget http://downloads.digium.com/pub/telephony/dahdi-tools/dahdi-tools-current.tar.gz
[...]
15:43:09 (9.87 MB/s) - »dahdi-tools-current.tar.gz« gespeichert [413598/413598]
----

Da der DAHDI-Treiber immer vor Asterisk kompiliert werden muss,
entpacken Sie diesen, wechseln dann in das Verzeichnis, kompilieren und
installieren ihn:

[source,shell]
----
debian:/usr/src# tar xvzf dahdi-linux-current.tar.gz 
dahdi-linux-2.1.0.4/
dahdi-linux-2.1.0.4/include/
[...]
debian:/usr/src# cd dahdi-linux-2.1.0.4 
debian:/usr/src/dahdi-linux-2.1.0.4# make && make install
[...]
debian:/usr/src/dahdi-linux-2.1.0.4# 
----

Wechseln Sie jetzt wieder ins Verzeichnis
`/usr/src`, und entpacken Sie die DAHDI-Tools:

[source,shell]
----
debian:~# cd /usr/src
debian:/usr/src# tar xvzf dahdi-tools-current.tar.gz 
dahdi-tools-2.1.0.2/
dahdi-tools-2.1.0.2/hdlctest.c
dahdi-tools-2.1.0.2/bootstrap.sh
[...]
debian:/usr/src# 
----

Vor dem Kompilieren müssen Sie noch `./configure`
aufrufen:

[source,shell]
----
debian:/usr/src# cd dahdi-tools-2.1.0.2
debian:/usr/src/dahdi-linux-2.1.0.4# ./configure
debian:/usr/src/dahdi-linux-2.1.0.4# make && make install
[...]
debian:/usr/src/dahdi-linux-2.1.0.4# 
----

Dannach müssen Sie noch die Start-Skripte für DAHDI installieren.
Auch dies erledigt das Makefile:

[source,shell]
----
debian:/usr/src/dahdi-linux-2.1.0.4## make config
I think that the DAHDI hardware you have on your system is:
pci:0000:04:00.0     wctdm24xxp+  d161:8005 Wildcard TDM410
debian:/usr/src/dahdi-linux-2.1.0.4# 
----

Durch diese Aktion werden auch gleich die Konfigurationsdateien
installiert und konfiguriert. Die Treiber können nun durch

[source,shell]
----
debian:/usr/src/dahdi-linux-2.1.0.4## /etc/init.d/dahdi start
----

geladen
werden.

Jetzt wechseln Sie wiederum in das Verzeichnis
`/usr/src` und entpacken den Asterisk-Tarball:

[source,shell]
----
debian:~# cd /usr/src
debian:/usr/src# tar xvzf asterisk-1.4-current.tar.gz 
asterisk-1.4.24.1/
asterisk-1.4.24.1/build_tools/
[...]
debian:/usr/src# 
----

Die entpackten Dateien müssen jetzt kompiliert werden. Dies
geschieht mit den Befehlen `./configure` und
`make` im gerade entpackten Verzeichnis.

[WARNING]
====
Bitte achten Sie darauf, dass die hier in der Dokumentation
benutzte Version 1.4.24.1 vielleicht zum Zeitpunkt Ihrer Installation
nicht mehr aktuell ist. Entsprechend werden sich die Verzeichnisnamen
ändern.
====

Übrigens ist dies jetzt ein guter Moment, sich einen Kaffee
oder Tee zu kochen. Der Kompiliervorgang kann je nach Rechenleistung des
PCs wenige Minuten oder bis zu einer Stunde dauern.

[source,shell]
----
debian:/usr/src# cd asterisk-1.4.24.1 
debian:/usr/src/asterisk-1.4.24.1# ./configure
[...]
configure: Package configured for:
configure: OS type  : linux-gnu
configure: Host CPU : i686
debian:/usr/src/asterisk-1.4.24.1# make
[...]
make[1]: Leaving directory `/usr/src/asterisk-1.4.24.1/main'
 +--------- Asterisk Build Complete ---------+
 + Asterisk has successfully been built, and +
 + can be installed by running:              +
 +                                           +
 +               make install                +
 +-------------------------------------------+
----

Die Software ist jetzt kompiliert und muss nur noch mit
`make install` installiert (sprich, an die vorgesehenen
Stellen im Dateisystem kopiert) werden:

[source,shell]
----
debian:/usr/src/asterisk-1.4.24.1# make install
[...]
 +---- Asterisk Installation Complete -------+
 +                                           +
 +    YOU MUST READ THE SECURITY DOCUMENT    +
 +                                           +
 + Asterisk has successfully been installed. +
 + If you would like to install the sample   +
 + configuration files (overwriting any      +
 + existing config files), run:              +
 +                                           +
 +               make samples                +
 +                                           +
 +-----------------  or ---------------------+
 +                                           +
 + You can go ahead and install the asterisk +
 + program documentation now or later run:   +
 +                                           +
 +              make progdocs                +
 +                                           +
 + **Note** This requires that you have      +
 + doxygen installed on your local system    +
 +-------------------------------------------+
debian:/usr/src/asterisk-1.4.24.1# 
----

Geschafft! Die soeben kompilierten Programmdateien sind jetzt auf
dem System installiert. Allerdings finden Sie im
Asterisk-Konfigurationsverzeichnis `/etc/asterisk/`
noch gähnende Leere vor. In diesem Verzeichnis liegen die
Konfigurationsdateien von Asterisk, und da Sie gewiss nicht bei null
beginnen möchten, lassen Sie sich die Standarddateien erstellen:

[source,shell]
----
debian:/usr/src/asterisk-1.4.24.1# make samples
[...]
done
debian:/usr/src/asterisk-1.4.24.1# 
----

Fertig! Asterisk ist auf Ihrem System inklusive aller benötigten
Treiber installiert. Mit dem Befehl `asterisk -V` können
Sie die installierte Version herausfinden (bitte achten Sie auf das
großgeschriebene V):

[source,shell]
----
debian:/usr/src/asterisk-1.4.24.1# asterisk -V
Asterisk 1.4.24.1
debian:/usr/src/asterisk-1.4.24.1# 
----

[[digium-tdm400p-analog-fxo]]
== Beispiel-Dialplan

Nun noch ein Beispiel-Dialplan mit einer
`s`-_Extension_ (siehe auch xref:besondere-extensions.adoc#s-extension[„Die s-Extension“]) für ein eingehendes Gespräch von der
Analog-Karte:

[source]
----
[default]
exten => s,1,Wait(1)
exten => s,n,Answer()
exten => s,n,Dial(Dahdi/12)
exten => s,n,Hangup()
----
