[[functions-odbc_antigf]]
= `ODBC_ANTIGF()`

[source]
----
ODBC_ANTIGF(arg1[,arg2[,...]])
----

[IMPORTANT]
====
Diese Funktion wird vom Anwender in der Datei
`func_odbc.conf` definiert. Sie ist hier angeführt, da
sie in der Beispielkonfiguration von Asterisk enthalten ist. Für weitere
Informationen siehe xref:functions-odbc_function.adoc[Abschnitt D.69, „+ODBC__`funktionsname`_()+“].
====

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'ODBC_ANTIGF' =-

[Syntax]
ODBC_ANTIGF(<arg1>[...[,<argN>]])

[Synopsis]
Runs the referenced query with the specified arguments

[Description]
Runs the following query, as defined in func_odbc.conf, performing
substitution of the arguments into the query as specified by ${ARG1},
${ARG2}, ... ${ARGn}. This function may only be read, not set.

SQL:
SELECT COUNT(*) FROM exgirlfriends WHERE callerid='${SQL_ESC(${ARG1})}'

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:functions-odbc_function.adoc[Abschnitt D.69, „+ODBC__`funktionsname`_()+“], xref:functions-sql_esc.adoc[Abschnitt D.96, „`SQL_ESC()`“]
