[[functions-txtcidname]]
= `TXTCIDNAME()`

[source]
----
TXTCIDNAME(Nummer[,Zonen-Suffix])
----

Schlägt den Namen des Anrufers zu einer Nummer mittels DNS (im
TXT-Record) nach.

[source]
----
exten => 123,1,Set(callername=${TXTCIDNAME(012345678)})
----

Der Parameter `Zonen-Suffix` wurde in Asterisk 1.6
hinzugefügt. Ohne Angabe gilt das Zonen-Suffix
`e164.arpa`.

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'TXTCIDNAME' =-

[Syntax]
TXTCIDNAME(<number>)

[Synopsis]
TXTCIDNAME looks up a caller name via DNS

[Description]
This function looks up the given phone number in DNS to retrieve
the caller id name. The result will either be blank or be the value
found in the TXT record in DNS.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,7 +1,7 @@
-= Info about function 'TXTCIDNAME' =-

[Syntax]
- TXTCIDNAME(<number>)
+ TXTCIDNAME(<number>[,zone-suffix])

[Synopsis]
TXTCIDNAME looks up a caller name via DNS
@@ -9,4 +9,4 @@
[Description]
This function looks up the given phone number in DNS to retrieve
the caller id name. The result will either be blank or be the value
- found in the TXT record in DNS.
+ found in the TXT record in DNS. The default zone-suffix is e164.arpa.
