[[functions-callerpres]]
= `CALLERPRES()`

[source]
----
CALLERPRES()
----

Setzt die Caller-ID-Anzeige.

[source]
----
exten => 123,1,Set(CALLERPRES()=prohib_not_screened)
exten => 123,n,Dial(Zap/4/1234567)
----

[NOTE]
====
Damit der eingestellte Wert beim Rauswählen über ISDN beachtet wird,
muss `usecallingpres=yes` in der
`zapata.conf` gesetzt sein.
====

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'CALLERPRES' =-

[Syntax]
CALLERPRES()

[Synopsis]
Gets or sets Caller*ID presentation on the channel.

[Description]
Gets or sets Caller*ID presentation on the channel. The following values
are valid:
allowed_not_screened : Presentation Allowed, Not Screened
allowed_passed_screen : Presentation Allowed, Passed Screen
allowed_failed_screen : Presentation Allowed, Failed Screen
allowed : Presentation Allowed, Network Number
prohib_not_screened : Presentation Prohibited, Not Screened
prohib_passed_screen : Presentation Prohibited, Passed Screen
prohib_failed_screen : Presentation Prohibited, Failed Screen
prohib : Presentation Prohibited, Network Number
unavailable : Number Unavailable

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-setcallerpres.adoc[Abschnitt C.153, „`SetCallerPres()`“]
