[[functions-realtime_destroy]]
= `REALTIME_DESTROY()`

[source]
----
REALTIME_DESTROY(family,fieldmatch[,value[,delim1[,delim2]]])
----

Die Funktion funktioniert auf die gleiche Weise wie
`REALTIME()` (lesend), nur dass sie den einmal gelesenen Wert aus
der Realtime-Engine löscht.

[source]
----
; Lies und loesche einen Wert mit REALTIME_DESTROY()
exten => 123,1,Answer()
exten => 123,n,Set(data=${REALTIME_DESTROY(sipusers,ext,5678)})
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'REALTIME_DESTROY' =-

[Syntax]
REALTIME_DESTROY(family,fieldmatch[,value[,delim1[,delim2]]])

[Synopsis]
RealTime Destroy Function

[Description]
This function acts in the same way as REALTIME(....) does, except that
it destroys matched record in RT engine.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-realtime.adoc[Abschnitt D.81, „`REALTIME()`“], xref:functions-realtime_store.adoc[Abschnitt D.83, „`REALTIME_STORE()`“], xref:functions-odbc_function.adoc[Abschnitt D.69, „+ODBC__`funktionsname`_()+“], xref:applications-realtime.adoc[Abschnitt C.129, „`RealTime()`“]
