[[functions-ast_config]]
= `AST_CONFIG()`

[source]
----
AST_CONFIG(Datei,Kategorie,Variablenname,[index])
----

Diese Funktion liest einen bestimmten Wert aus einer
Konfigurationsdatei und gibt diesen zurück. Der Wert ist der tatsächliche
Wert, der zum Zeitpunkt des Funktionsaufrufs in der Datei steht, egal, ob,
z. B. nach einer Konfigurationsänderung, ein Reload von Asterisk
durchgeführt wurde oder nicht. Das bedeutet, dass die Werte, die von dieser
Funktion zurückgegeben werden, nicht unbedingt mit den
Konfigurationseinstellungen übereinstimmen müssen, die Asterisk im Moment
verwendet. Der optionale `index`-Parameter wird benutzt, wenn
mehr als ein Vorkommen dieser Variable in der Kategorie existiert. Der
Indexzähler fängt mit 0 an. Das heißt, dass die erste gefundene Variable mit
0 ausgelesen werden muss. Des Weiteren kann mit `index` die
Anzahl der vorhandenen Variablen mit herausgefunden werden. Dazu muss nur
als `index` der Wert `count` übergeben
werden.

[source]
----
; Gibt den type des Sip-Accounts anhand der Callerid auf der CLI aus
exten => 123,1,Answer()
exten => 123,n,Verbose(1,${AST_CONFIG(sip.conf,${CALLERID(num)},type)})
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'AST_CONFIG' =-

[Syntax]
AST_CONFIG(config_file,category,variable_name)

[Synopsis]
Retrieve a variable from a configuration file

[Description]
This function reads a variable from an Asterisk configuration file.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —
