[[functions-channels]]
= `CHANNELS()`

[source]
----
CHANNELS(String)
----

Die Funktion gibt eine durch Leerzeichen separierte Liste der im
Moment offenen Channels zurück. Sie können die Auswahl mit einem regulären
Ausdruck beschränken, den Sie der Funktion als Parameter
übergeben.

[source]
----
; Gibt die im Moment offenen Channels auf dem CLI aus.
exten => 123,n,Verbose(1, Im Moment existierende Channels: ${CHANNELS()})
    
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'CHANNELS' =-

[Syntax]
CHANNEL([regular expression])

[Synopsis]
Gets the list of channels, optionally filtering by a regular expression.

[Description]
Gets the list of channels, optionally filtering by a regular expression. If
no argument is provided, all known channels are returned. The regular
expression must correspond to the POSIX.2 specification, as shown in
regex(7). The list returned will be space-delimited.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-channel.adoc[Abschnitt D.11, „`CHANNEL()`“]
