[[functions-unlock]]
= `UNLOCK()`

[source]
----
UNLOCK(String)
----

Gibt einen Mutex wieder frei, der vorher mit
`LOCK()` gesperrt wurde. Als Parameter muss der Name des
Mutexes übergeben werden, der vorher auch `LOCK()`
übergeben wurde. Wenn ein `Hangup()` ausgeführt wird,
wird der Mutex automatisch freigegeben.

[source]
----
; Entsperre einen Mutex
exten => 123,n,UNLOCK(lock1))
    
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'UNLOCK' =-

[Syntax]
UNLOCK(<lockname>)

[Synopsis]
Unlocks a named mutex

[Description]
Unlocks a previously locked mutex. Note that it is generally unnecessary to
unlock in a hangup routine, as any locks held are automatically freed when the
channel is destroyed. Returns 1 if the channel had a lock or 0 otherwise.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-lock.adoc[Abschnitt D.59, „`LOCK()`“], xref:functions-trylock.adoc[Abschnitt D.104, „`TRYLOCK()`“]
