[[functions-smdi_msg]]
= `SMDI_MSG()`

[source]
----
SMDI_MSG(messageID,feld)
----

Liest Details aus einer mit `SMDI_MSG_RETRIEVE()` (xref:functions-smdi_msg_retrieve.adoc[Abschnitt D.93, „`SMDI_MSG_RETRIEVE()`“]) empfangenen SMDIfootnote:[Simplified Message Desk Interface, http://en.wikipedia.org/wiki/Simplified_Message_Desk_Interface. Sie finden es z. B. bei älteren Cisco-Telefonanlagen.]-Nachricht aus und gibt den Wert zurück. Die SMDI-Konfiguration
für Asterisk befindet sich in der `smdi.conf`, für
Beispiele siehe `doc/smdi.txt` im
Asterisk-Source-Verzeichnis.

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'SMDI_MSG' =-

[Syntax]
SMDI_MSG(<message_id>,<component>)

[Synopsis]
Retrieve details about an SMDI message.

[Description]
This function is used to access details of an SMDI message that was
pulled from the incoming SMDI message queue using the SMDI_MSG_RETRIEVE()
function.
Valid message components are:
number - The message desk number
terminal - The message desk terminal
station - The forwarding station
callerid - The callerID of the calling party that was forwarded
type - The call type. The value here is the exact character
that came in on the SMDI link. Typically, example values
are: D - Direct Calls, A - Forward All Calls,
B - Forward Busy Calls, N - Forward No Answer Calls

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:functions-smdi_msg_retrieve.adoc[Abschnitt D.93, „`SMDI_MSG_RETRIEVE()`“]
