[[functions-exception]]
= `EXCEPTION()`

[source]
----
EXCEPTION(Feld)
----

Dient zum Abfragen der Details einer „Exception“
(Ausnahme). Das Feld `reason` ist einer der folgenden
Werte: `INVALID`, `ERROR`,
`RESPONSETIMEOUT`, `ABSOLUTETIMEOUT` oder
ein eigener mit `RaiseException()` gesetzter
Wert.

[source]
----
exten => e,1,Verbose(1,### Eine Exception ist aufgetreten)
exten => e,n,Verbose(1,###     Grund: ${EXCEPTION(reason)})
exten => e,n,Verbose(1,###   Context: ${EXCEPTION(context)})
exten => e,n,Verbose(1,### Extension: ${EXCEPTION(exten)})
exten => e,n,Verbose(1,###  Priority: ${EXCEPTION(priority)})
exten => e,n,Hangup()
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'EXCEPTION' =-

[Syntax]
EXCEPTION(<field>)

[Synopsis]
Retrieve the details of the current dialplan exception

[Description]
The following fields are available for retrieval:
reason INVALID, ERROR, RESPONSETIMEOUT, ABSOLUTETIMEOUT, or custom
value set by the RaiseException() application
context The context executing when the exception occurred
exten The extension executing when the exception occurred
priority The numeric priority executing when the exception occurred

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-raiseexception.adoc[Abschnitt C.124, „`RaiseException()`“]
