[[functions-enumquery]]
= `ENUMQUERY()`

[source]
----
ENUMQUERY(Nummer[,Dienst[,Zonen-Suffix]])
----

Schlägt eine Nummer mit ENUM (xref:glossar.adoc#glossar-enum[ENUM])
nach. Anders als bei `ENUMLOOKUP()` (xref:functions-enumlookup.adoc[Abschnitt D.27, „`ENUMLOOKUP()`“]) wird hier nicht direkt ein Treffer
zurückgegeben, sondern eine numerische ID der Ergebnismenge, aus der sich
die Treffer dann mit `ENUMRESULT()` (xref:functions-enumresult.adoc[Abschnitt D.29, „`ENUMRESULT()`“]) abfragen lassen.
+_`Dienst`_+ kann unter anderem
`sip` (Default), `iax2`, `h323`,
`tel` oder `ALL` sein. Das
+_`Zonen-Suffix`_+ (Default:
`e164.arpa`) ist die ENUM-Zone. Eine ausführliche Beschreibung
und Beispiele finden Sie in `doc/README.enum` (1.2) bzw.
`doc/enum.txt` (1.4).

[source]
----
; die Nummer 456 nachschlagen:
123 => {
    Set(resultid=${ENUMQUERY(456,sip)});
    Set(count=${ENUMRESULT(resultid|getnum)});
    Verbose(1,Anzahl der ENUM-Ergebnisse: ${count});
    for (i=1; i<=${count}; i=${i}+1) {
        Set(device=${ENUMRESULT(resultid|${i})});
        Verbose(1,ENUM-Ergebnis ${i}: ${device});
        Dial(${device});
    }
}
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'ENUMQUERY' =-

[Syntax]
ENUMQUERY(number[,Method-type[,zone-suffix]])

[Synopsis]
Initiate an ENUM query

[Description]
This will do a ENUM lookup of the given phone number.
If no method-tpye is given, the default will be sip. If no
zone-suffix is given, the default will be "e164.arpa".
The result of this function will be a numeric ID that can
be used to retrieve the results using the ENUMRESULT function.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-enumresult.adoc[Abschnitt D.29, „`ENUMRESULT()`“], xref:functions-enumlookup.adoc[Abschnitt D.27, „`ENUMLOOKUP()`“], `enum.conf`, xref:functions-dundiquery.adoc[Abschnitt D.25, „`DUNDIQUERY()`“]
