[[functions-queueagentcount]]
= `QUEUEAGENTCOUNT()`

[source]
----
QUEUEAGENTCOUNT(warteschlange)
----

Gibt die Anzahl der Agenten (im Gegensatz zu den Anrufern) auf der
Warteschlange zurück.

[source]
----
; Anzahl der Agenten in der Warteschlange "support":
exten => 123,1,Set(foo=${QUEUEAGENTCOUNT(support)})
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* | | |

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'QUEUEAGENTCOUNT' =-

[Syntax]
QUEUEAGENTCOUNT(<queuename>)

[Synopsis]
Count number of agents answering a queue

[Description]
Returns the number of members currently associated with the specified queue.
This function is deprecated. You should use QUEUE_MEMBER_COUNT() instead.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -7,4 +7,5 @@
Count number of agents answering a queue

[Description]
- Not available
+ Returns the number of members currently associated with the specified queue.
+ This function is deprecated. You should use QUEUE_MEMBER_COUNT() instead.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.6 nicht vorhanden —

.Siehe auch
xref:functions-queue_member_count.adoc[Abschnitt D.73, „`QUEUE_MEMBER_COUNT()`“]
