[[functions-sysinfo]]
= `SYSINFO()`

[source]
----
SYSINFO(Parameter)
----

Die Funktion liefert Systeminformationen zurück. Welche man
abfragen möchte, muss man als Parameter übergeben.

`loadavg`:: Die durchschnittliche Systemlast der letzen Minute
`numcalls`:: Die Anzahl der momentan laufenden Gespräche
`uptime`:: Die Betriebszeit des Systems in Stunden
`totalram`:: Die Größe des RAMs in Kilobyte (kiB)
`freeram`:: Die Größe des freien RAMs in Kilobyte (kiB)
`bufferram`:: Die Größe des RAMs, der für Puffer verwendet wird, in Kilobyte (kiB)
`totalswap`:: Die Größe des Auslagerungsspeichers (Swap) in Kilobyte (kiB)
`freeswap`:: Die Größe des freien Auslagerungsspreichers (Swap) in Kilobyte (kiB)
`numprocs`:: Die Anzahl der im Moment laufenden Prozesse

[source]
----
; Gib die Anzahl der im Moment laufenden Prozesse auf der CLI aus.
    exten => 123,n,Verbose(1, ${SYSINFO(numprocs)}
    
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'SYSINFO' =-

[Syntax]
SYSINFO(<parameter>)

[Synopsis]
Returns system information specified by parameter.

[Description]
Returns information from a given parameter
Options:
loadavg - system load average from past minute
numcalls - number of active calls currently in progress
uptime - system uptime in hours
totalram - total usable main memory size in KiB
freeram - available memory size in KiB
bufferram - memory used by buffers in KiB
totalswap - total swap space size in KiB
freeswap - free swap space still available in KiB
numprocs - number of current processes

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —
