[[functions]]
= Funktionen im Dialplan

Seit Asterisk 1.2 gibt es im Dialplan nicht nur Applikationen,
sondern auch sogenannte Funktionen. Anders als Applikationen können
Funktionen nicht direkt aufgerufen werden. Stattdessen geben sie einen Wert
zurück, oder man kann – was dem klassischen Verständnis einer Funktion
widerspricht – auch (oder nur) in Verbindung mit der Applikation
`Set()` (siehe xref:applications-set.adoc[Abschnitt C.149, „`Set()`“]) schreibend
auf sie zugreifen. Funktionsnamen werden immer ganz in Großbuchstaben
geschrieben. Funktionen werden erstaunlicherweise wie Variablen durchweg in
`${}` eingeklammert, was notwendig ist, da Strings nicht immer in
Hochkommata stehen müssen.

======

Würde man die in Asterisk nicht unbedingt intuitive Trennung
zwischen Applikationen, Funktionen und sogar Variablen kritisieren, hätte
man damit wahrscheinlich nicht ganz unrecht. Auch die Benennung ist nicht
einheitlich: `SIP_HEADER()`, aber `SIPCHANINFO()` –
ein Problem vieler Programmiersprachen, das letztlich nichts aussagt, aber
die Einprägsamkeit erschwert. Die Idee, in Funktionen zu
_schreiben_, ist recht ungewöhnlich und weicht vom
üblichen Verständnis einer Funktion ab. Eine „Funktion“ in
Asterisk kann man sich eher vorstellen wie ein assoziatives Arrayfootnote:[http://de.wikipedia.org/wiki/Assoziatives_Array] (auch Hash-Tabelle genannt) in anderen Programmiersprachen.
Beispiel:

[source]
----
Set(CHANNEL(language)=de);
NoOp(Sprache: ${CHANNEL(language)});
----

Dies würde in PHP so
aussehen:

[source]
----
$channel["language"] = "de";
echo "Sprache: ", $channel["language"];
----

Bei vielen Funktionen kann der Schlüssel in dem (gedachten)
assoziativen Array allerdings auch leer sein. Beispiel:

[source]
----
Set(GROUP()=ausgehend);
----

Insgesamt wirkt die Dialplan-Programmierung – trotz der Neuerungen
in Version 1.4 – im Vergleich zu „richtigen“
Programmiersprachen sehr starr und wenig erweiterungsfähig. Wenn das Sie
stört, sollten Sie sich vielleicht mit AEL (Asterisk Extension Language)
befassen, die die gleichen Funktionen und Applikationen verwendet, aber
eine etwas robustere Struktur bietet und oft übersichtlicher ist.

Im Asterisk-CLIfootnote:[Command Line Interface, kann durch `asterisk -r` aufgerufen werden] können Sie mit *`core show functions`* und
*+core show function
_`Funktionsname`_+* herausfinden, welche
Funktionen in Ihrer Installation verfügbar sind. Dabei ist die komplette
Großschreibung des Funktionsnamens wichtig.
