[[functions-stat]]
= `STAT()`

[source]
----
STAT(Flag,Dateiname)
----

Gibt Status-Informationen über eine Datei zurück (vgl. die
Shell-Befehle `test` und `stat`). Mit
`Dateiname` ist ein Datei-Knoten („inode“) gemeint.
`Dateiname` kann also auch ein Verzeichnis oder eine
besondere Datei sein. `Flag` ist eines der
folgenden:

`d`:: Prüft, ob die Datei ein Verzeichnis ist.
`e`:: Prüft, ob die Datei existiert.
`f`:: Prüft, ob die Datei eine reguläre Datei ist (im Gegensatz zu besonderen Dateien: _block special file, character special file, symbolic link, named pipe, socket_).
`m`:: Gibt den Datei-Modus zurück (oktal), also die Rechte, z. B. 0754.
`s`:: Gibt die Datei-Größe in Bytes zurück.
`A`:: Gibt die Unix-Zeit des letzten Zugriffs zurück (_access_).
`C`:: Gibt die Unix-Zeit zurück, wann sich der Knoten (_inode_) zuletzt geändert hat (_change_).
`M`:: Gibt die Unix-Zeit der letzten Veränderung zurück (_modification_).

[source]
----
; letzte Veränderung der Datei /etc/crontab abfragen:
exten => 123,1,Set(foo=${STAT(M,/etc/crontab)})
----

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'STAT' =-

[Syntax]
STAT(<flag>,<filename>)

[Synopsis]
Does a check on the specified file

[Description]
flag may be one of the following:
d - Checks if the file is a directory
e - Checks if the file exists
f - Checks if the file is a regular file
m - Returns the file mode (in octal)
s - Returns the size (in bytes) of the file
A - Returns the epoch at which the file was last accessed
C - Returns the epoch at which the inode was last changed
M - Returns the epoch at which the file was last modified

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —
