[[functions-strftime]]
= `STRFTIME()`

[source]
----
STRFTIME([Unixtime][,[Zeitzone][,Format]])
----

Formatiert eine Unix-Zeit (Epoch), umgerechnet in die angegebene
Zeitzone, in einem bestimmten Format. Wenn `Unixtime` nicht
angegeben wird, gilt die aktuelle Zeit. Der Default der
`Zeitzone` ist die Zeitzone des Rechners. Mögliche Zeitzonen
finden Sie in `/usr/share/zoneinfo/`. Die
Formatierungsplatzhalter sind dieselben wie in der C-Funktion
`strftime()` (siehe `man strftime`), der Default
ist `%c`, also die locale-abhängige Darstellung von Datum und
Zeit.

[source]
----
; Datum/Zeit im Format "JJJJ-MM-TT, HH:MM:SS"
exten => 123,1,Set(zeit=${STRFTIME(${EPOCH},Europe/Berlin,%Y-%m-%d\, %H:%M:%S)})
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'STRFTIME' =-

[Syntax]
STRFTIME([<epoch>][|[timezone][|format]])

[Synopsis]
Returns the current date/time in a specified format.

[Description]
Not available

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -1,7 +1,7 @@
-= Info about function 'STRFTIME' =-

[Syntax]
- STRFTIME([<epoch>][,[timezone][,format]])
+ STRFTIME([<epoch>][|[timezone][|format]])

[Synopsis]
Returns the current date/time in a specified format.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,10 +1,16 @@
-= Info about function 'STRFTIME' =-

[Syntax]
- STRFTIME([<epoch>][|[timezone][|format]])
+ STRFTIME([<epoch>][,[timezone][,format]])

[Synopsis]
Returns the current date/time in a specified format.

[Description]
- Not available
+ STRFTIME sports all of the same formats as the underlying C function
+ strftime(3) - see the man page for details. It also supports the
+ following format:
+ %%%%[n]q - fractions of a second, with leading zeroes. For example, %%%%3q will
+ give milliseconds and %%%%1q will give tenths of a second. The default
+ is to output milliseconds (n=3). The common case is to use it in
+ combination with %%%%S, as in "%%%%S.%%%%3q".
