[[functions-agent]]
= `AGENT()`

[source]
----
AGENT(AgentenNr[:Feld])
----

Gibt Informationen über einen Agenten zurück, der durch die
`AgentenNr` identifiziert wird. Die folgenden Felder können
abgefragt werden:

`status`:: (default) Der Einlog-Status des Agenten, entweder `LOGGEDIN` oder `LOGGEDOUT`
`password`:: Das Passwort des Agenten
`name`:: Der Name des Agenten
`mohclass`:: Die Wartemusik-Klasse (_Music on hold class_)
`exten`:: Die Rückruf-Extension des Agenten. Sie wird von der Applikation `AgentCallbackLogin()` verwendet.
`channel`:: Der Name des aktiven Kanals des Agenten (`AgentLogin()`)

[source]
----
; die Variable foo auf den Namen des Agenten Nr. 42 setzen:
exten => 123,1,Set(foo=${AGENT(42:name)})
----

.Asterisk-Versionen:
| | | *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'AGENT' =-

[Syntax]
AGENT(<agentid>[:item])

[Synopsis]
Gets information about an Agent

[Description]
The valid items to retrieve are:
- status (default) The status of the agent
LOGGEDIN | LOGGEDOUT
- password The password of the agent
- name The name of the agent
- mohclass MusicOnHold class
- exten The callback extension for the Agent (AgentCallbackLogin)
- channel The name of the active channel for the Agent (AgentLogin)

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— in Asterisk 1.2 nicht vorhanden —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —
