[[functions-sip_header]]
= `SIP_HEADER()`

[source]
----
SIP_HEADER(Headername[,Nummer])
----

Gibt einen Header aus dem SIP-Protokoll zurück (aus dem
`INVITE` des eingehenden Kanals). Diese Funktion werden Sie
nur benötigen, wenn Sie genaue Kenntnis des SIP-Protokolls haben. Da manche
Header (wie `Via`) mehrfach vorkommen können, kann man mit
`Nummer` (1-basiert) angeben, welche Zeile man haben
will.

[source]
----
; den TO-Header abfragen:
exten => 123,1,Set(DN=${SIP_HEADER(TO):5})
exten => 123,2,Set(DN=${CUT(DN,@,1)})
----

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.4:
-= Info about function 'SIP_HEADER' =-

[Syntax]
SIP_HEADER(<name>[,<number>])

[Synopsis]
Gets the specified SIP header

[Description]
Since there are several headers (such as Via) which can occur multiple
times, SIP_HEADER takes an optional second argument to specify which header with
that name to retrieve. Headers start at offset 1.

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
--- in Asterisk 1.2
+++ in Asterisk 1.4
@@ -1,10 +1,12 @@
-= Info about function 'SIP_HEADER' =-

[Syntax]
- SIP_HEADER(<name>)
+ SIP_HEADER(<name>[,<number>])

[Synopsis]
Gets the specified SIP header

[Description]
- Not available
+ Since there are several headers (such as Via) which can occur multiple
+ times, SIP_HEADER takes an optional second argument to specify which header with
+ that name to retrieve. Headers start at offset 1.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— keine —

.Siehe auch
xref:applications-sipaddheader.adoc[Abschnitt C.164, „`SIPAddHeader()`“]
