[[functions-realtime_store]]
= `REALTIME_STORE()`

[source]
----
REALTIME_STORE(familie,feld1[,...[,feld30]])=wert1[,...,[,wert30]]
----

Die Funktion dient zum Anlegen eines neuen Datensatzes in der
Realtime-Konfiguration. Bis zu 30 Feldnamen und Werte werden von der
Funktion unterstützt. Wenn die Realtime-Engine IDs unterstützt (z. B. MySQL)
erzeugt die Funktion die Channel-Variable `RTSTOREID`, in der die
ID steht.

[source]
----
; Speichere Werte mit REALTIME_STORE()
exten => 123,1,Answer()
exten => 123,n,Set(REALTIME_STORE(sip_users,ext,secret)=1337,geheim)
exten => 123,n,Hangup()
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'REALTIME_STORE' =-

[Syntax]
REALTIME_STORE(family,field1,field2,...,field30) = value1,value2,...,value30

[Synopsis]
RealTime Store Function

[Description]
This function will insert a new set of values into the RealTime repository.
If RT engine provides an unique ID of the stored record, REALTIME_STORE(...)=..
creates channel variable named RTSTOREID, which contains value of unique ID.
Currently, a maximum of 30 field/value pairs is supported.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-realtime.adoc[Abschnitt D.81, „`REALTIME()`“], xref:functions-odbc_function.adoc[Abschnitt D.69, „+ODBC__`funktionsname`_()+“], xref:applications-realtime.adoc[Abschnitt C.129, „`RealTime()`“]
