[[functions-minivmaccount]]
= `MINIVMACCOUNT()`

[source]
----
MINIVMACCOUNT(benutzer@domain:eigenschaft)
----

Gibt Informationen über einen Benutzer-Account im
Mini-VoiceMail-System (xref:minivm.adoc[Abschnitt 13.7, „Mini-VoiceMail (MiniVM)“], xref:minivm.adoc#minivm.conf[„minivm.conf“]) zurück.

_`eigenschaft`_:

`path`:: Dateisystem-Pfad zum Mailbox-Verzeichnis des Benutzers
`hasaccount`:: Gibt an, ob der MiniVM-Benutzer-Account existiert (`1`) oder nicht (`0`).
`fullname`:: Der komplette Name des Benutzers
`email`:: Die E-Mail-Adresse des Benutzers
`etemplate`:: Das E-Mail-Template (Vorlage) für den Benutzer
`ptemplate`:: Das Pager-Template (Vorlage) für den Benutzer
`accountcode`:: „Konto-Nummer/Name“ des Benutzer-Accounts
`pincode`:: Die PIN-Nummer (Passwort) des Benutzers
`timezone`:: Die Zeitzone des Benutzerkontos
`language`:: Die Sprache des Benutzerkontos
+_`variable`_+:: Eine eigene in der `minivm.conf` (siehe xref:minivm.adoc#minivm.conf[„minivm.conf“]) mit `setvar` gesetzte Variable, also z. B. `x_firma`

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'MINIVMACCOUNT' =-

[Syntax]
MINIVMACCOUNT(<account>:item)

[Synopsis]
Gets MiniVoicemail account information

[Description]
Valid items are:
- path Path to account mailbox (if account exists, otherwise temporary mailbox)
- hasaccount 1 if static Minivm account exists, 0 otherwise
- fullname Full name of account owner
- email Email address used for account
- etemplate E-mail template for account (default template if none is configured)
- ptemplate Pager template for account (default template if none is configured)
- accountcode Account code for voicemail account
- pincode Pin code for voicemail account
- timezone Time zone for voicemail account
- language Language for voicemail account
- <channel variable name> Channel variable value (set in configuration for account)

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-minivmcounter.adoc[Abschnitt D.65, „`MINIVMCOUNTER()`“], xref:applications-minivmaccmess.adoc[Abschnitt C.94, „`MinivmAccMess()`“], xref:applications-minivmdelete.adoc[Abschnitt C.95, „`MinivmDelete()`“], xref:applications-minivmgreet.adoc[Abschnitt C.96, „`MinivmGreet()`“], xref:applications-minivmnotify.adoc[Abschnitt C.97, „`MinivmNotify()`“], xref:applications-minivmrecord.adoc[Abschnitt C.98, „`MinivmRecord()`“]
