[[functions-odbc_fetch]]
= `ODBC_FETCH()`

[source]
----
ODBC_FETCH(resultID)
----

Gibt eine Zeile aus einem mehrzeiligen Ergebnis einer ODBC-Abfrage
(xref:functions-odbc_function.adoc[Abschnitt D.69, „+ODBC__`funktionsname`_()+“]) zurück. ODBC-Funktionen, die
als `mode=multirow` definiert sind, geben statt direkt der ersten
Zeile eine Ergebnis-ID (_result ID_) zurück. Mit
`ODBC_FETCH()` kann man dann die einzelnen Zeilen
abfragen.

[source]
----
exten => 123,1,Set(resultid=${ODBC_HOLE_BEISPIEL_LISTE()})
exten => 123,n,Set(HASH(zeile)=${ODBC_FETCH(${resultid})})
exten => 123,n,Verbose(1,Schluessel in der Zeile: ${HASHKEYS(zeile)})
exten => 123,n,Set(HASH(zeile)=${ODBC_FETCH(${resultid})})
exten => 123,n,Verbose(1,Schluessel in der Zeile: ${HASHKEYS(zeile)})
exten => 123,n,ODBCFinish(resultid)
----

[IMPORTANT]
====
Mit `ODBCFinish()` (xref:applications-odbcfinish.adoc[Abschnitt C.108, „`ODBCFinish()`“]) wird die Ergebnismenge
(_result set_) sauber geschlossen.
====

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'ODBC_FETCH' =-

[Syntax]
ODBC_FETCH(<result-id>)

[Synopsis]
Fetch a row from a multirow query

[Description]
For queries which are marked as mode=multirow, the original query returns a
result-id from which results may be fetched. This function implements the
actual fetch of the results.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:functions-odbc_function.adoc[Abschnitt D.69, „+ODBC__`funktionsname`_()+“], xref:functions-odbc_sql.adoc[Abschnitt D.71, „`ODBC_SQL()`“], xref:applications-odbcfinish.adoc[Abschnitt C.108, „`ODBCFinish()`“], xref:functions-hash.adoc[Abschnitt D.43, „`HASH()`“]
