[[functions-jabber_status]]
= `JABBER_STATUS()`

[source]
----
JABBER_STATUS(jabber,buddy[/resource])
----

Gibt den Status des Jabber-Benutzers
_`buddy`_ zurück. Zum Verbinden wird die Definition
_`jabber`_ aus `jabber.conf`
verwendet. Die Jabber-ID _`buddy`_ kann optional
durch die Angabe _`resource`_ ergänzt
werden.footnote:[Zur Erklärung dieser Jabber-Begriffe siehe http://de.wikipedia.org/wiki/Jabber, http://de.wikipedia.org/wiki/Jabber_Identifier.]

Mögliche Rückgabewerte sind:

1:: Online, Angemeldet
2:: Chatty, Gesprächig
3:: Away, Abwesend
4:: XAway, Extended Away, Not available, Länger abwesend, Nicht verfügbar
5:: DND, Do not disturb, Nicht stören
6:: Offline, Abgemeldet
7:: Not in roster, Nicht im „Roster“ (Kontaktliste)

[source]
----
123 => {
    Set(status=${JABBER_STATUS(asterisk,philipp@example.com/home)});
    Verbose(1,### Der Jabber-Status von philipp ist: ${status});
    if ("${status}" = "1") {
        Verbose(1,### anwesend. per Jabber anrufen);
        Dial(Gtalk/asterisk-gmail/buddy@gmail.com);
    }
    else if ("${status}" = "5") {
        Verbose(1,### DND);
        VoiceMail(${EXTEN});
    }
    else {
        Verbose(1,### per SIP anrufen);
        Dial(SIP/philipp);
    }
}
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'JABBER_STATUS' =-

[Syntax]
JABBER_STATUS(<sender>,<buddy>[/<resource>])

[Synopsis]
Retrieve buddy status

[Description]
Retrieves the numeric status associated with the specified buddy (jid). If the
buddy does not exist in the buddylist, returns 7.
Status will be 1-7.
1=Online, 2=Chatty, 3=Away, 4=XAway, 5=DND, 6=Offline
If not in roster variable will be set to 7

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-jabberstatus.adoc[Abschnitt C.76, „`JabberStatus()`“], xref:applications-jabbersend.adoc[Abschnitt C.75, „`JabberSend()`“],
`jabber.conf`
