[[functions-ifmodule]]
= `IFMODULE()`

[source]
----
IFMODULE(modulname)
----

Prüft, ob ein Asterisk-Modul geladen wurde und verfügbar ist.
Asterisk-Module sind „Shared-Object“-Dateien, daher muss man
den Modulnamen immer mit „`.so`“ am Ende
angeben. Gibt `1` zurück, wenn das Modul geladen wurde,
andernfalls `0`.

[source]
----
exten => 123,1,Verbose(1, app_queue.so geladen?: ${IFMODULE(app_queue.so)})
exten => 123,n,Verbose(1, res_agi.so   geladen?: ${IFMODULE(res_agi.so)})
exten => 123,n,Verbose(1, chan_sip.so  geladen?: ${IFMODULE(chan_sip.so)})
exten => 123,n,Verbose(1, beispiel.so  geladen?: ${IFMODULE(beispiel.so)})
----

[TIP]
====
Welche Asterisk-Module geladen werden sollen, wird in der Datei
`modules.conf` festgelegt. Eine Liste aller geladenen
Module kann man auf dem CLI mit dem Befehl +`module
show`+ anzeigen.
====

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'IFMODULE' =-

[Syntax]
IFMODULE(<modulename.so>)

[Synopsis]
Checks if an Asterisk module is loaded in memory

[Description]
Checks if a module is loaded. Use the full module name
as shown by the list in "module list".
Returns "1" if module exists in memory, otherwise "0".

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
