[[functions-dialgroup]]
= `DIALGROUP()`

[source]
----
DIALGROUP(gruppenname[,operation])
----

Implementiert eine extrem simple Queue. Zu einer
„Dialgroup“ kann man mit der
_`operation`_ `add` Mitglieder
hinzufügen, und mit `del` kann man diese entfernen. Ohne
Angabe einer _`operation`_ wird die gesamte Liste der
Mitglieder durch den neuen Wert ersetzt.

[source]
----
exten => 123,1,Set(DIALGROUP(beispiel,add)=SIP/108)
exten => 123,n,Set(DIALGROUP(beispiel)=SIP/109)
exten => 123,n,Set(DIALGROUP(beispiel,add)=Local/105)
exten => 123,n,Set(DIALGROUP(beispiel,add)=SIP/104)
exten => 123,n,Set(DIALGROUP(beispiel,del)=Local/105)
exten => 123,n,Set(DIALGROUP(beispiel,add)=Local/102)
exten => 123,n,Set(DIALGROUP(beispiel,add)=Local/101)
exten => 123,n,Verbose(1,Gruppe ist: ${DIALGROUP(beispiel)})
exten => 123,n,Dial(${DIALGROUP(beispiel)})
exten => 123,n,Hangup()
----

Effektiv entspricht das einem:

[source]
----
exten => 123,1,Dial(SIP/109&SIP/104&Local/102&Local/101)
----

.Asterisk-Versionen:
| | | | | *1.6* |————————

.Interner Hilfetext zu dieser Funktion in Asterisk 1.6:
-= Info about function 'DIALGROUP' =-

[Syntax]
DIALGROUP(<group>[,op])

[Synopsis]
Manages a group of users for dialing

[Description]
DIALGROUP presents an interface meant to be used in concert with the Dial
application, by presenting a list of channels which should be dialled when
referenced.
When DIALGROUP is read from, the argument is interpreted as the particular
group for which a dial should be attempted. When DIALGROUP is written to
with no arguments, the entire list is replaced with the argument specified.
Other operations are as follows:
add - add a channel name or interface (write-only)
del - remove a channel name or interface (write-only)

Functionality is similar to a queue, except that when no interfaces are
available, execution may continue in the dialplan. This is useful when
you want certain people to be the first to answer any calls, with immediate
fallback to a queue when the front line people are busy or unavailable, but
you still want front line people to log in and out of that group, just like
a queue.

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
— in Asterisk 1.4 nicht vorhanden —

.Siehe auch
xref:applications-queue.adoc[Abschnitt C.122, „`Queue()`“]
