[[installation-einleitung]]
= Einleitung

Ein nicht immer ganz zu Unrecht bestehendes Vorurteil gegenüber
Asterisk besagt, dass man mindestens 2 bis 3 Tage Webseiten und
Dokumentation studieren muss, um überhaupt auch nur irgendetwas
Lauffähiges zustande zu bringen. Diese Hürde ist für viele Interessierte
zu hoch, oder der Aufwand ist ihnen die Mühe und Zeit nicht wert. Wenn Sie
zu denen gehören, die sich nicht lange mit einem theoretischen Unterbau
beschäftigen möchten, sondern möglichst schnell ein Ergebnis sehen wollen,
ist dieses Kapitel genau richtig für Sie. Sie sollten es von Anfang bis
Ende durcharbeiten, auch wenn Sie den Rest des Buches wie ein
Nachschlagewerk nutzen können.

[IMPORTANT]
====
In diesem Buch geht es um Asterisk und nicht um Linux. Aus
diesem Grund wird beim Leser grundlegendes Linux-Know-how
vorausgesetzt. Es sollte also klar sein, wie ein Text-Editor bedient
wird und wie man eine einfache Netzwerkkonfiguration einstellt. Falls
nichts anders erwähnt wird, wird immer als _root_
gearbeitet.
====

[[Asterisk-1.4-oder-1.6]]
== Asterisk 1.4 oder 1.6?

Das ist für dieses Einsteiger-Kapitel absolut egal. Alle hier
beschriebenen Basics gelten für beide Versionen. Da bei Telefonanlagen
im Zweifelsfall immer die stabilere Version vorzuziehen ist, nehmen wir
die Asterisk-Version 1.4. Sollten Sie diese Dokumentation im Jahr 2010
oder noch später in die Hand bekommen, können Sie natürlich auch gern
ein Asterisk 1.6 installieren.
