[[ivr-mehrstufig]]
= Mehrstufige IVR-Systeme
:description: Mehrstufige IVR-Menüs in Asterisk mit verschachtelten Contexten.

Das Problem bei mehrstufigen IVRs ist, dass der Benutzer je nach
Menüstruktur mehrmals eine einstellige Zahl (eventuell sogar die gleiche)
drücken soll, aber jeweils ein anderes Ergebnis erhält oder eine andere
Aktion erfolgt. Da innerhalb eines Contextes eine Zahl aber nur einmal
vergeben werden kann, bliebe der Anrufer immer auf dieser Menüebene
hängen. Sollen mehrere Menüs hintereinander geschaltet werden und sollen
in jedem Menü gleiche Eingaben andere Ergebnisse bringen, so muss man
diese Untermenüs in andere Contexte (in unserem Beispiel
`[kantine]`) legen. Der Sprung zwischen den einzelnen
Positionen erfolgt dann mit `Goto()`. Nehmen wir an, Sie haben folgende
Soundfiles im Verzeichnis `/var/lib/asterisk/sounds/`
abgespeichert:

* `grundmenue.gsm`
+
Bitte drücken Sie die 1 für den Verkauf, die 2 für den
Hausmeister und die 3 für die Kantine.
* `kantine.gsm`
+
Drücken Sie die 1 für den Essensplan dieser Woche und die 2 für
den Essensplan der nächsten Woche.
* `essensplan-diese-woche.gsm`
+
Montag gibt es Nudeln mit Tomatensoße, Dienstag gibt es
Jägerschnitzel, ...
* `essensplan-naechste-woche.gsm`
+
Montag gibt es Eintopf, Dienstag gibt es Jägerschnitzel,
...

Wenn der Verkauf unter der Extension 100 und der Hausmeister unter
der Extension 150 erreichbar ist, sieht der Dialplan für diese IVR
folgendermaßen aus:

[source]
----
[beispiel-ivr]
; Das Menü wird ständig wiederholt.
exten => 30,1,Answer()
 same => n(loop),Background(grundmenue)
 same => n,Background(silence/3)
 same => n,Goto(loop)

exten => 1,1,Dial(PJSIP/100)

exten => 2,1,Dial(PJSIP/150)

; Goto() springt in einen anderen Context ([kantine])
exten => 3,1,Goto(kantine,100,1)

; Falscheingaben: zurück ins Menü
exten => i,1,Goto(30,loop)

[kantine]
exten => 100,1,Background(kantine)
 same => n(loop),Background(silence/3)
 same => n,Goto(loop)

exten => 1,1,Playback(essensplan-diese-woche)
 same => n,Wait(2)
 same => n,Goto(100,loop)

exten => 2,1,Playback(essensplan-naechste-woche)
 same => n,Wait(2)
 same => n,Goto(100,loop)

; Falscheingabe: zurück ins Hauptmenü
exten => i,1,Goto(beispiel-ivr,30,loop)
----

[[ivr-tiefe]]
== Tiefe der IVR

Auch wenn es technisch möglich ist, beliebig tiefe
Verschachtelungen zu realisieren, so ist es in der Praxis ratsam, nicht
mehr als drei Ebenen an Menüs hintereinanderzuschalten. Viele Anrufer
legen nach der dritten Eingabe-Ebene auf.
