[[konferenzraum-installation]]
= Installation und das Timing-Device

Eine Standard-Asterisk-Installation, wie Sie sie aus dem ersten
Kapitel des Buchs kennen, ist nicht in der Lage, Telefonkonferenzen zu
realisieren. Das Problem liegt am nicht vorhandenen Timing-Device. Um die
eingehenden Channels einer Telefonkonferenz richtig mischen zu können,
benötigt Asterisk einen klaren und für alle Channels gleichen Takt. Es
gibt hierfür prinzipiell zwei Möglichkeiten:

* Treiber einer Hardware-Karte
+
Wenn Sie die Zaptel-Treiber einer Digium-Karte, Sangoma-Karte
und -Treiber oder den Junghanns BRIstuff zusammen mit einer ISDN-Karte
installieren, bekommt Asterisk automatisch ein Timing-Device.
* ztdummy-Modul ohne Hardware
+
Wer keine entsprechende Hardware zur Verfügung hat oder einbauen
will, der kann auf das `ztdummy`-Modul in Kombination mit
einem 2.6er-Kernel zurückgreifen.footnote:[Es ist auch möglich, ein ztdummy-Modul mit einem 2.4er-Kernel zu kompilieren. Dies setzt aber eine spezielle USB-Hardware voraus und ist deshalb ein suboptimaler Weg.]

Um herauszufinden, ob Ihr Asterisk auch die Konferenzfunktionalität
anbietet, gehen Sie bitte ins CLI und geben `show application
MeetMe` ein. Sollte der Hilfetext angezeigt werden, können Sie
eine Konferenz einleiten.
