[[manager-mailboxcount]]
= `MailboxCount`

.Asterisk-Versionen:
————————| *1.2* |————————| *1.4* |————————| *1.6* |————————

.Interner Hilfetext zu diesem AMI-Befehl in Asterisk 1.4:
Action: MailboxCount
Synopsis: Check Mailbox Message Count
Privilege: call,all
Description: Checks a voicemail account for new messages.
Variables: (Names marked with * are required)
*Mailbox: Full mailbox ID <mailbox>@<vm-context>
ActionID: Optional ActionID for message matching.
Returns number of new and old messages.
Message: Mailbox Message Count
Mailbox: <mailboxid>
NewMessages: <count>
OldMessages: <count>

.Differenz des internen Hilfetexts von Asterisk 1.2 zu 1.4:
— keine —

.Differenz des internen Hilfetexts von Asterisk 1.4 zu 1.6:
--- in Asterisk 1.4
+++ in Asterisk 1.6
@@ -1,12 +1,13 @@
Action: MailboxCount
Synopsis: Check Mailbox Message Count
- Privilege: call,all
+ Privilege: call,reporting,all
Description: Checks a voicemail account for new messages.
Variables: (Names marked with * are required)
*Mailbox: Full mailbox ID <mailbox>@<vm-context>
ActionID: Optional ActionID for message matching.
- Returns number of new and old messages.
+ Returns number of urgent, new and old messages.
Message: Mailbox Message Count
Mailbox: <mailboxid>
+ UrgentMessages: <count>
NewMessages: <count>
OldMessages: <count>
