[[minimale-telefonanlage]]
= Eine Minimal-Telefonanlage mit zwei SIP-Telefonen

Wie sieht die einfachste mögliche Telefonanlage aus? Zwei Telefone
und ein Asterisk.

Wir haben schon alle Einzelteile in diesem Puzzle behandelt und
müssen sie jetzt nur noch richtig zusammenfügen. Als Erstes konfigurieren
wir die zwei SIP-Telefone in der
`/etc/asterisk/sip.conf`:

[source]
----
[general] 
port=5060 
bindaddr=0.0.0.0 

[2000] 
type=friend 
secret=1234 
host=dynamic

[2001] 
type=friend 
secret=1234 
host=dynamic
----

Als Nächstes müssen wir noch die
`/etc/asterisk/extensions.conf` anpassen. Das
Hello-World-Beispiel lassen wir zu Testzwecken im Dialplan. So können wir
die Funktion jedes einzelnen Telefons durch Anwahl der 1001 überprüfen.
Der Dialplan sieht wie folgt aus:

[source]
----
[default] 
exten => 1001,1,Answer()
exten => 1001,2,Playback(hello-world)
exten => 1001,3,Hangup()

exten => 2000,1,Dial(SIP/2000)
exten => 2001,1,Dial(SIP/2001)
----

Nach einem Neustart von Asterisk und der SIP-Telefone können Sie,
nachdem die Telefone sich registriert haben, von einem Telefon zum anderen
und zur 1001 anrufen.

[[min-anlage-ab]]
== ... und jetzt mit einem Anrufbeantworter

Asterisk beinhaltet bereits ein fertiges Voicemail-Modul. Wir
müssen es lediglich in der Datei
`/etc/asterisk/voicemail.conf` aktivieren. Als ersten
Schritt verschieben wir diese Default-Datei in unser Verzeichnis mit den
Sicherungskopien der Konfigurationsdateien:

[source,shell]
----
debian:/etc/asterisk# mv voicemail.conf /var/tmp/asterisk-etc-backup/
----

Daraufhin erstellen wir eine neue
`/etc/asterisk/voicemail.conf` und versehen diese mit
folgendem Inhalt:

[source]
----
[general]
format = wav

[default]
2000 => 4711,Hans Mustermann,hansi@company.de
2001 => 0815,Ute Beispiel,ute.beispiel@company.de
----

Damit sind die Voicemailboxen grundsätzlich eingerichtet (ja, so
einfach geht das!). Jetzt müssen wir aber noch in der
`/etc/asterisk/extensions.conf` einige weitere Zeilen
eintragen, um die Voicemail-Funktionalität unseren Telefonen zuzuweisen.
Bitte vergessen Sie dabei nicht den neuen Eintrag
_`",20"`_ bei der Dial-Applikation.

[source]
----
[default] 
exten => 1001,1,Answer()
exten => 1001,2,Playback(hello-world)
exten => 1001,3,Hangup()

exten => 2000,1,Dial(SIP/2000,20)
exten => 2000,2,VoiceMail(2000,u)

exten => 2001,1,Dial(SIP/2001)
exten => 2001,2,VoiceMail(2001,u)

exten => 2999,1,VoiceMailMain(${CALLERID(num)},s)
----

Fertig! Jetzt müssen Sie Asterisk nur noch mit `asterisk
-vvvvvc` neu starten

[TIP]
====
In einem laufenden Asterisk-System reicht auch ein
`reload` im CLI aus.
====

und mit einem Telefon das andere anrufen. Nachdem es 20 Sekunden
lang geklingelt hat (deshalb die _`20`_ am Ende des
Dial-Befehls), kommt man auf die Voicemailbox. Ist die Gegenstelle
besetzt, wird man direkt auf die Voicemailbox 2000 geleitet. Sie können
vom Telefon mit der Nummer 2000 die entsprechende Mailbox abhören, indem
Sie die Nummer 2999 anrufen. Dann bekommen Sie Ihre Voicemailbox als
Menü vorgespielt.

[NOTE]
====
Ist auf Ihrem System ein Mail Transfer Agent (MTA)
eingerichtet (z. B. sendmail oder postfix), so werden von Ihnen neu
aufgesprochene Nachrichten direkt an die in der
`voicemail.conf` angegebene E-Mail-Adresse
geschickt.
====

Wenn Sie das Ganze noch mit einer Passwortabfrage absichern wollen
oder eine Auflistung des Menüs suchen, finden Sie dazu in xref:kapitel-voicemail.adoc[Kapitel 13, _Voicemail-System_] die nötigen Informationen.
