[[priority-jumping]]
= Priority Jumping ist deprecated!

Lange Zeit wurde in Asterisk-Dialplänen hauptsächlich mit
_Priority Jumping_ gearbeitet. Dazu wurde von
bestimmten Applikationen (z. B. `Dial()`) die Priorität bei
bestimmten Ereignissen um 101 hochgesetzt. Diese Funktionalität ist aber
mittlerweile offiziell _deprecated_ (im Sinne von
„überholt“ und „nicht erwünscht“). Sie wird zwar
teilweise noch unterstützt, sollte jedoch nicht mehr benutzt werden. Die
Klassifizierung _deprecated_ bezeichnet zumeist
Funktionen und Funktionsaufrufe, für die mittlerweile entsprechende
Nachfolger oder Folgekonstrukte existieren und die künftig durch diese
neuen ersetzt werden sollen. Beim Suchen nach Lösungen und Anregungen im
Internet oder auch in anderen Asterisk-Büchern werden Sie ebenfalls immer
wieder auf Lösungsvorschläge stoßen, die dieses überholte Konstrukt mit
den Prioritäten verwenden. Auch wenn die Unterstützung für derart
erstellte Dialpläne sicher nicht morgen eingestellt wird, so werden sie
doch mittelfristig schlechter unterstützt werden, und man kann dann nicht
sicher sein, dass es eine Lösung in der alten Notation geben wird. Es hat
auch Vorteile, sich frühzeitig aktiv mit einer Umstellung zu beschäftigen,
da Sie so bei künftigen Updates der Asterisk-Software deutlich weniger
Gefahr laufen werden, dass Ihr Dialplan nicht mehr so funktioniert, wie
Sie das gewohnt sind.
