[[queues-conf]]
= `queues.conf`
:description: Die queues.conf in Asterisk: Warteschlangen-Definitionen und -Optionen.

In der `queues.conf` werden Warteschlangen
definiert und entsprechende Einstellungen vorgenommen. Die Datei ist
– wie Sie das schon kennen – in Abschnitte
unterteilt.

Unter `[general]` stellen wir nur
`persistentmembers = yes` ein, damit beim Neustart von Asterisk
die Agenten automatisch wieder in ihre Schlangen aufgenommen
werden.

Jede Warteschleife stellt einen eigenen Abschnitt dar. Wir legen
bespielsweise eine Warteschlange im Abschnitt `[support]` an.
Folgende Parameter stehen zur Verfügung:

[[queues.conf-musiconhold]]
== `musiconhold`

Legt die in `musiconhold.conf` definierte
Musikklasse der Warteschleife fest. Wir wählen die oben angelegte Klasse
`default`:

[source]
----
musiconhold = default
----

[[queues.conf-announce]]
== `announce`

Legt eine Audiodatei fest, die einem Agenten vor dem Beantworten
eines Anrufs vorgespielt wird. Dies dient dazu, dass ein Agent, der auf
mehreren Warteschlangen Anrufe entgegennimmt, weiß, um welche
Warteschlange es sich handelt, und z. B. den Anrufer entsprechend
begrüßen kann.

[source]
----
;announce = schlange-support
----

Wenn
Sie diese Einstellung verwenden, müssen Sie daran denken, auch eine
entsprechende Audiodatei im `sounds/`-Verzeichnis
anzulegen, also z. B. `schlange-support.gsm`.

[[queues.conf-strategy]]
== `strategy`

Legt fest, in welcher Weise und Reihenfolge die Agenten bei einem
Anruf angeklingelt werden sollen:

`ringall`:: Alle anklingeln, bis einer antwortet. (Default)
`roundrobin`:: Der Reihe nach alle anklingeln, bis einer antwortet.
`leastrecent`:: Das Interface anklingeln, bei dem der letzte Anruf am längsten zurückliegt.
`fewestcalls`:: Den anklingeln, der am wenigsten Anrufe in dieser Warteschlange abgearbeitet hat.
`random`:: Ein zufällig gewähltes Interface anklingeln.
`rrmemory`:: Round-Robin mit Gedächtnis. Beginnt die Reihe bei dem, der nach dem letzten Anruf an der Reihe ist.
`linear`:: Wie `roundrobin`, aber streng in der Reihenfolge der `member`-Einträge.
`wrandom`:: Zufällig, aber mit Berücksichtigung der Penalty der Agenten.

[NOTE]
====
Die Strategie `roundrobin` wurde ab Asterisk 12 entfernt. Benutzen
Sie stattdessen `rrmemory` (Round-Robin mit Gedächtnis) oder
`linear` (strikt nach Eintragsreihenfolge).
====

Beachten Sie, dass Agenten, für die ein niedrigerer Malus
(_penalty_) festgelegt wurde, immer Agenten mit
höherem Malus vorgezogen werden.

[source]
----
strategy = ringall
----

Die
Einstellung ist abhängig von Ihren Gegebenheiten: `ringall`
ist vielleicht lästig; die anderen Werte verursachen zusätzliche
Wartezeit für den Anrufer, falls Agenten nicht ans Telefon gehen.

[[queues.conf-servicelevel]]
== `servicelevel`

Legt die Zeit (in Sekunden) fest, in der Anrufe beantwortet sein
sollen. Nur für statistische Auswertungen interessant („Wie viele
Anrufe wurden innerhalb der Service-Zeit von x Sekunden
beantwortet?“).

[source]
----
servicelevel = 60
----

[[queues.conf-context]]
== `context`

Hier kann ein Context angegeben werden, in dem ein Anrufer, wenn
er eine Extension mit nur _einer_ Ziffer drückt, aus
der Warteschlange genommen und zu dieser Extension in diesem Context
weitergeleitet wird.

[source]
----
context = supportschlange-Context  ; so könnten wir es einstellen

; aber wir lassen das erst mal weg, also auskommentiert:
;context = supportschlange-Context
----

[[queues.conf-timeout]]
== `timeout`

Legt fest, wie lange (in Sekunden) ein Telefon klingeln soll, bis
wir es als nicht besetzt (also Timeout) betrachten.

[source]
----
timeout = 15
----

[[queues.conf-retry]]
== `retry`

Bestimmt, wie lange (in Sekunden) gewartet werden soll, bevor
erneut alle Agenten angeklingelt werden.

[source]
----
retry = 5
----

[[queues.conf-weight]]
== `weight`

Das Gewicht (Wichtigkeit) der Warteschlange, relativ zu anderen
Warteschlangen. Wenn ein Agent auf mehreren Warteschlangen ist, werden
ihm zuerst Anrufe von Warteschlangen mit höherem Gewicht durchgestellt.
So könnte z. B. einer Notfallschlange ein höheres Gewicht gegeben
werden.

[source]
----
weight = 0
----

[[queues.conf-wrapuptime]]
== `wrapuptime`

Die Wartezeit (in Sekunden), bevor ein Agent, der gerade einen
Anruf beendet hat, erneut einen Anruf erhält (Default:
0).

[source]
----
; wir lassen unseren Agenten eine kleine Verschnaufpause, um
; einen Schluck Wasser zu trinken:
wrapuptime = 10
----

[[queues.conf-maxlen]]
== `maxlen`

Maximale Anzahl der in der Warteschlange wartenden Anrufer
(Default: 0 für unbegrenzt).

[source]
----
maxlen = 0
----

[[queues.conf-announce-frequency]]
== `announce-frequency`

Bestimmt, in welchen Abständen (in Sekunden) den Anrufern ihre
Position in der Warteschlange und/oder die geschätzte Wartezeit angesagt
werden soll (0 für aus).

[source]
----
announce-frequency = 90
----

[[queues.conf-announce-holdtime]]
== `announce-holdtime`

Bestimmt, ob die geschätzte Wartezeit in den Ankündigungen nach
der Position genannt werden soll. Mögliche Werte sind `yes`
(ja), `no` (nein) oder `once` (nur
einmal).

[source]
----
announce-holdtime = yes
----

[[queues.conf-announce-round-seconds]]
== `announce-round-seconds`

Rundungsschritte der Sekunden. Mit der Einstellung 0 werden nur
die Minuten, nicht die Sekunden angesagt. Andere mögliche Werte sind: 0,
1, 5, 10, 15, 20 und 30.footnote:[In älteren Versionen wurden auch andere Werte akzeptiert, was zu verwirrenden Ergebnissen führte, siehe http://bugs.digium.com/view.php?id=9514[Bug 9514\].] (Mit 30 würde beispielsweise eine geschätzte Wartezeit von
2:34 auf 2:30 gerundet.)

[source]
----
announce-round-seconds = 0
----

[[queues.conf-sprachbausteine]]
== Sprachbausteine

Die folgenden Parameter stellen ein, welche Sprachbausteine für
die Ansagen der Position und Wartezeit verwendet werden. In der Regel
sind hier keine Veränderungen notwendig:

[source]
----
queue-youarenext = queue-youarenext     ; "You are now first in line."
queue-thereare = queue-thereare         ; "There are" ...
queue-callswaiting = queue-callswaiting ; ... "calls waiting."
queue-holdtime = queue-holdtime         ; "The current est. holdtime is" ...
queue-minutes = queue-minutes           ; ... "minutes"
queue-seconds = queue-seconds           ; ... "seconds"
queue-thankyou = queue-thankyou         ; "Thank you for your patience."
queue-lessthan = queue-less-than        ; ... "less than" ...
queue-reporthold = queue-reporthold     ; "Hold time" ...
periodic-announce = queue-periodic-announce  ; "All reps busy, wait for next"
----

Wenn
diese Parameter nicht angegeben werden (also auskommentiert sind),
gelten diese Default-Werte.

[[queues.conf-periodic-announce-frequency]]
== `periodic-announce-frequency`

Bestimmt, in welchen Abständen (in Sekunden) den Anrufern die
periodische Ankündigung (`periodic-announce`, s.o.,
„Zur Zeitfootnote:[sic! Es gibt wohl keine dümmere Erfindung der sogenannten neuen deutschen Rechtschreibung als das völlig überflüssige Adverb ‚zurzeit‘.] sind alle Mitarbeiter im Gespräch, bitte warten
Sie.“) angesagt werden soll.

[source]
----
periodic-announce-frequency = 60
----

[[queues.conf-monitor-format]]
== `monitor-format`

Die Angabe dieses Parameters schaltet die Aufzeichnung von
Gesprächen ein (wie mit der `Monitor()`-Applikation) und
bestimmt das Aufzeichnungsformat. (Bei auskommentiertem
`monitor-format` werden keine Mitschnitte gemacht.) Geben Sie
hier also `gsm`, `wav` (große Dateien!) oder
`wav49` an.

[source]
----
; wenn Sie Aufzeichnungen wollen, diese Zeile einkommentieren:
;monitor-format = gsm
----

Per Default werden die Dateien (eine `-in`
und eine `-out`) nach `$\{UNIQUEID}`
benannt. Sie können das bei Bedarf verändern, indem Sie im Dialplan vor
dem `Queue()`-Aufruf
+Set(MONITOR_FILENAME=_`dateiname`_)+
angeben. Wir nehmen aber im Beispiel keine Veränderung vor.

Weitere Informationen über Mitschnitte siehe Abschnitt C.100, „`Monitor()`“

[[queues.conf-monitor-join]]
== `monitor-join`

Kombiniert die beiden durch einen Gesprächsmitschnitt erzeugten
Dateien +_`...`_-in+ und
+_`...`_-out+ zu einer Datei.
Werte: `yes` oder `no`.

[source]
----
monitor-join = yes
----

Zu
weiteren Informationen über Mitschnitte siehe: Abschnitt C.100, „`Monitor()`“

[[queues.conf-joinempty]]
== `joinempty`

Legt fest, ob Anrufer in eine Warteschleife ohne Agenten
eingereiht werden.

`yes`:: Anrufer können in eine Schleife ohne Agenten oder von nur nicht-verfügbaren Agenten eingereiht werden.
`no`:: Anrufer können nicht in eine Schleife ohne Agenten eingereiht werden.
`strict`:: Anrufer können nicht in eine Schleife ohne Agenten eingereiht werden (aber in eine Warteschlange mit nur nicht-verfügbaren Agenten).
+
"Nicht-verfügbar" ist nicht zu verwechseln mit "im
Gespräch" (_busy_). Ein Agent ist nicht
verfügbar, wenn er zwar der Warteschlange zugewiesen, aber
tatsächlich nicht am System registriert ist (siehe auch xref:queues-conf.adoc#queues.conf-member[„`member`“]). Achtung: Statisch definierte
Mitglieder (siehe xref:queues-conf.adoc#queues.conf-member[„`member`“]) gelten
immer als verfügbar!

Sollte ein Anrufer nicht in eine Warteschlange
aufgenommen werden, ist die `Queue()`-Applikation beendet,
und der Dialplan wird fortgesetzt.

[source]
----
joinempty = no  ; wir wollen unsere Anrufer nicht unnötig warten lassen
----

[[queues.conf-leavewhenempty]]
== `leavewhenempty`

Legt fest, ob Anrufer aus einer Warteschlange entfernt werden,
sobald sich alle Agenten ausgeloggt haben. Zu den möglichen Werten siehe
`joinempty`. Nach dem Verlassen der Warteschlange wird der
Dialplan fortgesetzt.

[source]
----
leavewhenempty = strict  ; Anrufer nicht unnötig warten lassen
----

[[queues.conf-eventwhencalled]]
== `eventwhencalled`

Stellt ein (`yes`|`no`), ob unter anderem
die folgenden Events für das Manager-Interface erzeugt werden:
`AgentCalled`, `AgentDump`,
`AgentConnect`,
`AgentComplete`.

[source]
----
eventwhencalled = yes
----

[[queues.conf-eventmemberstatus]]
== `eventmemberstatus`

Stellt ein (`yes`|`no`), ob
QueueMemberStatus-Events im Manager-Interface erzeugt werden (das können
viele sein!).

[source]
----
eventmemberstatus = no
----

[[queues.conf-reportholdtime]]
== `reportholdtime`

Legt fest (`yes`|`no`), ob dem Agenten die
Wartezeit des Anrufers angesagt werden soll, bevor dieser zu ihm
durchgestellt wird. (Geschmacksfrage)

[source]
----
reportholdtime = no
----

[[queues.conf-memberdelay]]
== `memberdelay`

Stellt ein, wie lange (in Sekunden) der Anrufer Stille hört, bevor
er mit einem Agenten verbunden wird.

[source]
----
memberdelay = 1
----

[[queues.conf-timeoutrestart]]
== `timeoutrestart`

Bestimmt, ob der Antwort-Timeout eines Agenten bei einem Besetzt-
oder Leitung-überlastet-Signal zurückgesetzt wird. Das kann nützlich für
Agenten sein, die die Berechtigung haben, einen Anruf
abzuweisen.

[source]
----
timeoutrestart = yes
----

[[queues.conf-autopause]]
== `autopause`

Dieser Parameter legt fest, ob ein Agent, der einen Anruf nicht
beantwortet, automatisch pausiert werden soll.

[source]
----
autopause = no
----

[[queues.conf-ringinuse]]
== `ringinuse`

Legt fest, ob auch solche Agenten angeklingelt werden sollen, von
denen bekannt ist, dass sie gerade im Gespräch sind. Der bisher einzige
Channel-Driver, der diesen Status übermittelt, ist SIP.

[source]
----
ringinuse = no
----

[[queues.conf-member]]
== `member`

Es ist möglich, direkt in der `queues.conf`
Agenten *statisch* in der
Form

[source]
----
member => Technologie/Ressource[,Malus]
----

– also z. B. `member => Zap/2` – anzulegen
(darf mehrmals verwendet werden, siehe
`queues.conf`). Das kann jedoch zu Problemen mit
`joinempty` und `leavewhenempty` führen, da diese
Agenten _immer_ als verfügbar angesehen werden, auch
wenn sie in Wirklichkeit nicht an ihrem Apparat sind. Zudem hat es den
Nachteil, dass ein Agent immer fest einem Apparat zugeordnet ist und
sich nicht von einem anderen Apparat aus anmelden kann.

Wir verwenden daher lieber die *dynamische* Form und ordnen unserer Warteschlange
`support` in der Form

[source]
----
member => Agent/AgentenNr
----

zwei
Agenten `1001` und `1002` zu:

[source]
----
member => Agent/1001
member => Agent/1002
----

Diese Agenten müssen wir noch in der
`agents.conf` definieren (siehe unten).footnote:[Sonst wären es wirklich Geheimagenten ;-)] Die `AgentenNr` ist eine frei wählbare Nummer,
die jeden Agenten eindeutig identifiziert. Sie hat nichts mit den
Extensions zu tun, die die Agenten eventuell verwenden.
