[[sangoma-a500]]
= Installation der Sangoma A500 ISDN-Karte

====== Zusammenfassung

Installationsbeschreibung der Sangoma ISDN-Karte A500 auf einem
Asterisk-System. Mit einem Beispiel für den Anschluss an das öffentliche
ISDN-Netz.

Die von http://www.sangoma.com[Sangoma] für entwickelte
A500-ISDN-Kartefootnote:[Produktseite: http://sangoma.com/products_and_solutions/hardware/digital_voice_and_data_networking/a500.html,]ist eine erweiterbare ISDN-Karte mit 2 bis 24 Ports. Dabei
können 6 Ports (12 B-Kanäle) auf einer einzelnen Karte verwendet werden.
Wenn mehr als 6 Ports benötigt werden, kann man eine zweite Karte einbauen
und über eine Steckverbindung mit der ersten Karte verbinden. Somit haben
die Karten den gleichen Takt. Die Karte ist verfügbar für PCIfootnote:[http://de.wikipedia.org/wiki/Peripheral_Component_Interconnect]- und PCI-Expressfootnote:[abgekürzt: PCIe oder PCI-E (nicht PCI-X), http://de.wikipedia.org/wiki/PCI-Express]-Steckplätze („Slots“) mit 5 V oder 3,3 V. Sie
verwendet die hervorragende Hardware-Echounterdrückung (Echo Cancellation)
von http://www.octasic.com/[Octasic].

Die Karte ist sehr gut für mittelgroße und große Installationen
geeignet, wo z. B. zusätzlich zur VoIP-Anbindung – oder auch
ausschließlich – bis zu 48 B-Kanäle ins öffentliche ISDN-Netz
betrieben werden sollen.footnote:[Falls Sie wirklich 48 B-Kanäle betreiben wollen, sollten Sie allerdings über einen PRI- (auch S2M- oder Multiplex-)Anschluss nachdenken. Ein solcher Anschluss ist meistens günstiger und einfacher.] Es sind aber auch andere Szenarien denkbar: Die 6 ISDN-Ports
lassen sich paarweise auf TEfootnote:[Terminal Equipment, Endeinrichtung, d. h., unsere Seite agiert als Endgerät, also _extern._] oder NTfootnote:[Network Termination, Netzabschluss, die Seite, die einem Endgerät eine Teilnehmeranschlussleitung (TAL, engl.: _local loop_) bereitstellt, also _intern_] einstellen.

[[sangoma-a500-installation-hardware]]
== Einbau der A500-Karte

Geliefert wird die A500 in einer kleinen blauen Box, komplett mit
Port-Splitter-Kabeln. Die Y-Kabel werden benötigt, um aus den ISDN-Buchsen
jeweils 2 Leitungen mit „RJ-45“footnote:[8P8C]-Steckern herauszuführen. Außerdem liegt eine CD bei, mit
Handbüchern, Treibern, Firmware etc. und auch dem Hinweis zur
Registrierung bei Sangoma, wodurch man dann Gewährleistung erhält. Dass
Sie beim Auspacken der Karte darauf achten, geerdet zu sein, versteht sich
von selbst.

Ob die ISDN-Ports auf TE- oder NT-Modus eingestellt sind, wird
dadurch bestimmt, wie die 3 BRI-Module in die Karte eingesteckt sind. Das
linke Modul ist zuständig für Port 1 und 2, das mittlere für Port 3 und 4
und das rechte für Port 5 und 6. Gegebenenfalls steckt man die Module
andersherum ein. In dieser Anleitung stellen wir beide Module auf TE, da
wir die Karte an das öffentliche ISDN-Netz anschließen wollen. Wenn eines
der Module im NT-Modus betrieben werden soll, muss die Karte über den
Anschluss eines http://de.wikipedia.org/wiki/Molex[Molex-Steckers] am
hinteren Ende zusätzlich mit Strom versorgt werden. Für den TE-Modus
müssen alle Leitungswiderstände (_termination
resistors_) ausgeschaltet sein (für NT an), siehe http://wiki.sangoma.com/sangoma-wanpipe-smg-asterisk-bri-installation#HardwareInstallation.

Auf der Karte gibt es 12 kleine Schalter für die Wiederstände,
jeweils einen für ein Adernpaar, also 2 für einen ISDN-Port bzw. 4 für
eine Buchse an der Karte, da die Karte ja in einer Buchse 2 Ports
herausführt. Es müssen pro BRI-Modul also die jeweiligen
DIP-Doppelschalter Sw1 und Sw2 (bzw. Sw3 und Sw4, Sw5 und Sw6) alle gleich
eingestellt sein.

Gute Schema-Zeichnungen zum Einbau der A500 finden Sie in http://sangoma.com/data/docs/A500_InstallationManual.pdf.

[IMPORTANT]
====
Bei den BRI-Ports ist es wichtig, dass der Port 1 an das
öffentliche ISDN-Netz angeschlossen wird, da dieser den Zeittakt
übernimmt. Port 1 wird aus Buchse 1 herausgeführt; das ist die am
weitesten von der Schraublasche der PCI-Blende entfernte Buchse, oder
anders gesagt die Buchse mit dem geringsten Abstand vom PCI-Sockel auf
dem Mainboard.
====

Für diese Anleitung wird ein frisch installiertes Debian GNU/Linux 5
(„Lenny“) vorausgesetztfootnote:[Die Vorgängerversion 4 („Etch“) funktioniert ebenfalls.].

======

Ein ISO-Image für die Installation finden Sie unter http://www.debian.org/releases/etch/debian-installer/[http://www.debian.org/releases/lenny/debian-installer/].
Ich empfehle das etwa 150 MB große Netzinstallations-CD-Image. Eine
Debian-GNU/Linux-Installationsanleitung befindet sich unter http://www.debian.org/releases/etch/i386/[http://www.debian.org/releases/lenny/i386/].
Ein allgemeines Anwenderhandbuch steht unter http://debiananwenderhandbuch.de/[http://debiananwenderhandbuch.de].

_Bitte loggen Sie sich nach der Installation als Benutzer
`root` am System ein, und führen Sie alle hier
angegebenen Befehle mit diesem Benutzer aus._

Es versteht sich eigentlich von selbst, dass man auf einem frisch
installierten System die Paketlisten für `aptitude`
aktualisiert und wichtige Updates einspielt:

[source,shell]
----
debian:~# aptitude update
[...]
Paketlisten werden gelesen... Fertig
debian:~# aptitude upgrade
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
debian:~# 
----

Für den Fall, dass beim Upgrade der Pakete auch ein neuer Kernel
installiert wurde, müssen wir jetzt das System rebooten:

[source,shell]
----
debian:~# shutdown -r now
----

Loggen Sie sich nach dem Hochfahren des Rechners bitte wieder als
`root` ein, und kontrollieren Sie dann, dass die Karte
richtig erkannt wird:

[source,shell]
----
debian:~# lspci -nn -v -d 1923:
00:08.0 Network controller [0280]: Sangoma Technologies Corp. A200/Remora FXO/FXS Analog AFT card [1923:0040]
        Subsystem: Device [a500:3200]
        Flags: bus master, medium devsel, latency 255, IRQ 17
        Memory at fdfe0000 (32-bit, non-prefetchable) [size=64K]
----

Da
ist sie. Wundern Sie sich nicht: Die Karte kann als A200 angezeigt werden,
je nachdem, was in `/usr/share/misc/pci.ids`
eingetragen ist. Wichtig ist, was bei `Subsystem: Device
[a500:3200]` steht: "a500" sagt uns, dass es die richtige Karte ist.
(`1923` ist der PCI-Hersteller-Code von Sangoma).

Lassen Sie sich übrigens nicht von den Farben der LEDs in den
Buchsen verwirren. Die Buchsen leuchten rot für TE (grün für NT).

[[sangoma-a500-build-environment]]
== Build-Umgebung

In den weiteren Abschnitten benötigen wir eine Build-Umgebung, also
Compiler usw.:

[source,shell]
----
debian:~# aptitude install build-essential
debian:~# aptitude install libncurses5-dev flex bison
debian:~# aptitude install bzip2
----

Und auch die Linux-Kernel-Header:

[source,shell]
----
debian:~# aptitude install linux-headers-`uname -r`
----

[[sangoma-a500-asterisk]]
== Quellen von Asterisk

Asteriskfootnote:[Falls vorher bereits eine ältere Version von Asterisk installiert war, müssen Sie zuerst die alten Module entfernen:debian:~# *`rm -rf /usr/lib/asterisk/modules`*]:

[source,shell]
----
debian:~# aptitude install libssl-dev libncurses5-dev libcurl3-dev
debian:~# cd /usr/src/
debian:/usr/src# wget http://downloads.digium.com/pub/asterisk/releases/asterisk-1.4.21.tar.gz
debian:/usr/src# tar xzf asterisk-1.4.21.tar.gz 
debian:/usr/src# rm asterisk-1.4.21.tar.gz 
debian:/usr/src# cd asterisk-1.4.21/
debian:/usr/src/asterisk-1.4.21# ./configure 
debian:/usr/src/asterisk-1.4.21# make
debian:/usr/src/asterisk-1.4.21# make install
debian:/usr/src/asterisk-1.4.21# make samples
debian:/usr/src/asterisk-1.4.21# make config
debian:/usr/src/asterisk-1.4.21# update-rc.d -f asterisk remove
debian:/usr/src/asterisk-1.4.21# update-rc.d asterisk defaults 50 15
----

[[sangoma-a500-wanpipe-installation]]
== Installation von Wanpipe

Eine Build-Umgebung haben wir bereitsfootnote:[Hätten wir sie noch nicht, müssten wir sie so installieren:debian:~# *`aptitude install build-essential flex bison libncurses5-dev`* debian:~# *+aptitude install linux-headers-`uname -r`+*]. Außerdem brauchen wir noch `udev` und
`lksctp`:

[source,shell]
----
debian:~# aptitude install udev lksctp-tools libsctp-dev
----

Auch `logrotate` sollte vorher vorhanden sein, damit das
Skript automatisch eine entsprechende `logrotate`-Definition
erstellen kann:

[source,shell]
----
debian:~# aptitude install logrotate
----

Als Nächstes installieren wir die aktuelle Version von
Wanpipe:

[source,shell]
----
debian:~# cd /usr/src/
debian:/usr/src# wget -O wanpipe-current-stable.tgz \
  ftp://ftp.sangoma.com/linux/current_wanpipe/current-stable.tgz
----

[source,shell]
----
debian:/usr/src# tar xzf wanpipe-*.tgz 
debian:/usr/src# rm wanpipe-*.tgz 
debian:/usr/src# cd wanpipe-*
----

Das Skript `Setup` kümmert sich um die
Kompilierung und würde es melden, falls wir notwendige Software nicht
installiert hätten. Es gibt zwei verschiedene Modi, die wir beide
verstellen. Wir empfehlen für normale Installationen den einfacheren
_Silent_-Modus (xref:sangoma-a500.adoc#installation-a500-silent-modus[„Silent-Modus-Installation“]).

[[installation-a500-silent-modus]]
== Silent-Modus-Installation

Im Silent-Modus wird vom Skript so wenig wie möglich gefragt. Wenn
Sie mehr Kontrolle über den Installationsvorgang wünschen, dann finden Sie
in xref:sangoma-a500.adoc#installation-a500-interaktiver-modus[„Interaktiver-Modus-Installation“] eine
detaillierte Anleitung zum interaktiven Modus.

[source,shell]
----
debian:/usr/src/wanpipe-3.6.0# ./Setup install --silent --protocol=BRI
        ----------------------------------------------------------
                  WANPIPE v3.6.0 Installation Script
            Copyright (c) 1995-2008, Sangoma Technologies Inc.
        ----------------------------------------------------------
[...]
----

Das Skript wird nun alle Aufgaben erledigen, die für den
Installationsprozess benötigt werden. Dies kann eine Weile dauern. Am Ende
sollte dann folgende Meldung kommen:

[source,shell]
----

        ----------------------------------------------------------
                  WANPIPE v3.6.0 Installation Script
            Copyright (c) 1995-2008, Sangoma Technologies Inc.
        ----------------------------------------------------------

WANPIPE INSTALLATON: COMPLETE

WANPIPE installation is now complete. WANPIPE kernel drivers
and configuration/debug utilities have been compiled and installed.

        1) Proceed to configure the WANPIPE drivers:
                Asterisk/Zaptel: /usr/sbin/wancfg_zaptel
                Asterisk/Dahdi : /usr/sbin/wancfg_dahdi
                TDM API        : /usr/sbin/wancfg_tdmapi
                SMG SS7/BRI    : /usr/sbin/wancfg_smg
                WAN Routing/API: /usr/sbin/wancfg
        2) Use the /usr/sbin/wanrouter startup script to start and stop
           the router. (eg: wanrouter start)
        3) To uninstall WANPIPE package run ./Setup remove

Please read http://wiki.sangoma.com for further instructions.
----

Die Treiber, das Sangoma-Media-Gateway und Konfigurationsprogramme
sind nun installiert.

Jetzt muss man noch die Karte mithilfe der
Sangoma-Konfigurationstools konfigurieren:

[source,shell]
----
debian:~# /usr/sbin/wancfg_smg
[...]
########################################################################
#                          Sangoma Wanpipe                              #
#        Dahdi/Zaptel/SMG/TDMAPI/BOOT Configuration Script             #
#                             v2.22                                    #
#                     Sangoma Technologies Inc.                        #
#                        Copyright(c) 2008.                            #
########################################################################
[...]
----

Jetzt geht es um die Konfiguration der BRI-Ports. Zur Erinnerung:
„Point to multipoint“ bedeutet Mehrgeräteanschluss, also
„normales“ ISDN, und „Point to point“ bedeutet
Anlagenanschluss:

[source,shell]
----
-----------------------------------------------------------
A500 detected on slot:8 bus:0
-----------------------------------------------------------

Would you like to configure AFT-A500 port 1 on slot:8 bus:0
 1. YES
 2. NO
 3. Exit
[1-3]: 1
----

[source,shell]
----

Configuring port 1 on AFT-A500 [slot:8 bus:0 span:1]

Select connection type for port 1
 1. Point to multipoint
 2. Point to point
[1-2, ENTER='Point to multipoint']: 1
----

[source,shell]
----

Input the group for this port
: 1
----

[source,shell]
----

Select dialplan context for group:1
 1. from-pstn
 2. Custom
[1-2]: 1
----

[source,shell]
----

Configuring span:1 as TEI:127
 1. YES - Keep this setting
 2. NO  - Specify a different TEI
[1-2, ENTER='YES']: enter
----

Das Gleiche machen wir noch einmal für Port 2, 3, 4, 5 und 6 (je
nachdem, wie viele Module wir eingesteckt haben):

[source,shell]
----
[...]

Would you like to configure AFT-A500 port 2 on slot:8 bus:0
 1. YES
 2. NO
 3. Exit
[1-3, ENTER='YES']: enter
----

[source,shell]
----

Configuring port 2 on AFT-A500 [slot:8 bus:0 span:2]

Select connection type for port 2
 1. Point to multipoint
 2. Point to point
[1-2, ENTER='Point to multipoint']: enter
----

[source,shell]
----

Input the group for this port
def="1": 1
----

[source,shell]
----

Configuring span:2 as TEI:127
 1. YES - Keep this setting
 2. NO  - Specify a different TEI
[1-2, ENTER='YES']: enter
----

[source,shell]
----
[...]

ISBN BRI card configuration complete
----

[source,shell]
----

Press any key to continue: enter
----

[source,shell]
----
[...]

###################################################################
#                             SUMMARY                             #
###################################################################

  0 T1/E1 port(s) detected, 0 configured
  2 ISDN BRI port(s) detected, 2 configured
  0 analog card(s) detected, 0 configured

Configurator will create the following files:
        1. Wanpipe config files in /etc/wanpipe
        2. sangoma_brid config file /etc/wanpipe/smg_bri
        3. Zapata config file /etc/asterisk/zapata.conf

Your original configuration files will be saved to:

Your configuration has been saved in /etc/wanpipe/debug-2009-02-23.tgz.
When requesting support, email this file to techdesk@sangoma.com

###################################################################

Configuration Complete! Please select following:
 1. YES - Continue
 2. NO - Exit
[1-2]: 1
----

[source,shell]
----

Zaptel and Wanpipe configuration complete: choose action
 1. Save cfg: Restart Asterisk & Wanpipe now
 2. Save cfg: Restart Asterisk & Wanpipe when convenient
 3. Save cfg: Stop Asterisk & Wanpipe now
 4. Save cfg: Stop Asterisk & Wanpipe when convenient
 5. Do not save cfg: Exit
[1-5]: 1
----

[source,shell]
----
[...]

Would you like to continue?
 1. No - exit
 2. YES
[1-2, ENTER='No']: 2
----

[source,shell]
----
[...]

Wanrouter start complete...
Current boot level is 2

Wanrouter boot scripts configuration...

Removing existing wanrouter boot scripts...OK
Would you like wanrouter to start on system boot?
 1. YES
 2. NO
[1-2]: 1
----

[source,shell]
----

Verifying Zaptel boot scripts...Enabled (level:15)
Verifying Zaptel shutdown scripts...Enabled (level:30)
Enabling wanrouter boot scripts ...(level:14)
Enabling wanrouter shutdown scripts ...(level:29)
Verifying Network boot scripts...Not installed
Would you like smg_ctrl to start/stop on wanrouter start?
 1. YES
 2. NO
[1-2]: 1
----

[source,shell]
----

smgbri start scrtip installed scuessfully
smgbri stop script installed successfully
Sangoma cards configuration complete, exiting...
----

Jetzt geht es mit xref:sangoma-a500.adoc#a500-runlevel[„Runlevel“] weiter.

[[installation-a500-interaktiver-modus]]
== Interaktiver-Modus-Installation

Im interaktiven Modus kann man beim Installieren an allen Stellen
eingreifen. Normalerweise kann man aber überall die Default-Werte benutzen
oder sich das Leben mit dem Silent-Modus leichter machen (siehe xref:sangoma-a500.adoc#installation-a500-silent-modus[„Silent-Modus-Installation“]).

Als „Compilation Mode“ verwenden wir Nr. 6 („ SMG
(BRI) (Default for Asterisk SMG/BRI install)“).

[source,shell]
----
debian:/usr/src/wanpipe-3.6.0# ./Setup install
        ----------------------------------------------------------
                  WANPIPE v3.6.0 Installation Script
            Copyright (c) 1995-2008, Sangoma Technologies Inc.
        ----------------------------------------------------------
[...]
Would you like to install WANPIPE now? [y] (y/n) y
----

[source,shell]
----
[...]
Verifying files and fixing permissions ...Done
Checking for C developement tools ...(gcc) OK
Checking for C++ developement tools ...OK
Checking for Make utility ...OK
Checking for ncurses library ... OK
Checking for Perl developement tools ...OK
Checking for AWK ...OK
Checking for FLEX ...OK
Checking for Patch ...OK
Checking for libtermcap-devel...OK
Checking for bison...OK

Press [Enter] to continue... enter
----

[source,shell]
----
[...]
Please specify absolute path name of your linux directory

Press Enter for Default: /lib/modules/2.6.26-1-686/build

#> enter
----

[source,shell]
----

Setting linux directory to /lib/modules/2.6.26-1-686/build

Upgrading WANPIPE kernel documentation ...Done.

Upgrading WANPIPE kernel headers ...Done.

Upgrading WANPIPE kernel drivers ...Done.

WANPIPE device drivers upgraded successfully!

Press [Enter] to continue... enter
----

[source,shell]
----
[...]
        Please Select Compilation Mode
[...]

6. SMG (BRI) (Default for Asterisk SMG/BRI install)

[...]

Please select (1,2,3,4,5,6,7,8 or 9) [Default: 1]: 6
----

[source,shell]
----
Enabling the AFT TE1 Support
----

[source,shell]
----
Checking for SCTP Utilities....OK.
----

[source,shell]
----

Looking for Asteris/CallWeaver directory in /usr/src ...
-------------------------------------------
1 : /usr/src/asterisk-1.4.21 
------------------------------------------ 
------------------------------------------ 
m : Enter Asterisk/CallWeaver path manually

(ctrl-c to Exit)
Please select working Asterisk/CallWeaver directory [1-1][m]: 1
----

[source,shell]
----

Source kernel name:2.6.26-1-686

Checking for SMP support ...Enabled.

Checking current processor type ...i686

[...]

Checking for REGPARM kernel option ...Enabled.

Compiling General WANPIPE Driver for 2.6.X Kernel .....Done.

WAN HWEC module enabled and compiled!

Linking Wanpipe Driver and protocols ...Done.

Updating Kernel Modules ...Done.

Visually Confirm that driver compilation was successful! (y/n) y
----

[source,shell]
----
[...]

WANPIPE META CONFIGURATION

There are two configuration files associated with WANPIPE.  

1) /usr/src/wanpipe-3.6.0/wanrouter.rc: 
        - defines locations of important files such as lock
          and configuration files as well as start/stop 
          order of multiple WANPIPE devices.
2) /usr/src/wanpipe-3.6.0/wanpipe1.conf:
        - main configuration file for each WANPIPE device.
        - defines interfaces, hardware and protocol information.
        - this file can be created using the 'wancfg' GUI
          utility or manually based on sample files located
          in /etc/wanpipe/samples.
          
Please read the WanpipeInstallation.(pdf/txt) manual for further
information.

Press [Enter] to continue... enter
----

[source,shell]
----

Please specify a desired location for WANPIPE configuration files.

        (Press Enter for Default: /etc/wanpipe)

<specify path:> enter
----

[source,shell]
----

Please specify a desired location for WANPIPE interface files.

        (Press Enter for Default: /etc/wanpipe/interfaces)

<specify path:> enter
----

[source,shell]
----

Please specify a location for WANPIPE binary, firmware files.

        (Press Enter for Default: /etc/wanpipe/firmware)

<specify path:> enter
----

[source,shell]
----
[...]

WANPIPE UTILITIES SETUP

WANPIPE utilities are used to:
        1) create configuration files: for Zaptel and Asterisk
                /usr/sbin/wancfg_zaptel #Zaptel and Asterisk
                /usr/sbin/wancfg_smg    #BRI/SS7, Zaptel and Asterisk
                /usr/sbin/wancfg_tdmapi #TDM API
        2) create WANPIPE WAN/IP configuration files.
                (/usr/sbin/wancfg)
        3) start,stop,restart individual/all devices and interfaces.
                (/usr/sbin/wanrouter)
        4) debug line, protocol and driver problems.
                (/usr/sbin/wanpipemon)
        5) aid in WANPIPE API development
                (/etc/wanpipe/api)

Refer to the WanpipeInstallation.(pdf/txt) for more information.

Press [Enter] to continue... enter
----

[source,shell]
----

Compiling WANPIPE Utilities ...Done.

Compiling WANPIPE WanCfg Utility ...
Done.

Compiling WANPIPE Misc Utilities ...Done.

Compiling WANPIPE LibSangoma TDM API library ...Done.

Compiling WANPIPE API Development Utilities ...Done.

Compiling WANPIPE HWEC Utilities ...Done.

        WANPIPE Environment Setup Complete !!!

Press [Enter] to continue... enter
----

[source,shell]
----
Installing WANPIPE Files ... !
Installing  WANPIPE Utilities in /usr/sbin
Installing wanrouter.rc in /etc/wanpipe
Installing wanpipe libraries in /etc/wanpipe
Installing firmware in /etc/wanpipe/firmware
Installing documentation in /usr/share/doc/wanpipe
Installing sample api code in /etc/wanpipe/api
Installing AFT Firmware update utility in /etc/wanpipe/util
Installing driver headers in /etc/wanpipe/api/include/linux
Installing Hardware Echo Cancel Utilites
Press [Enter] to continue... enter
----

[source,shell]
----
[...]

WANPIPE BOOTSTRAP CONFIGURATION

Your system uses System V -style initialization scripts.  You have an option
to add router start-up script to those scripts so that the router will start
automatically when system enters multi-user mode and shut down when it enters
single-user mode or when it is halted.

i.e. By selecting this option WANPIPE will startup on system bootup and 
     stop on system shutdown.

Would you like to install WANPIPE start-up scripts? (y/n) y
----

[source,shell]
----
[...]
Current boot level is 2

Wanrouter boot scripts configuration...

Removing existing wanrouter boot scripts...OK
Enabling wanrouter boot scripts ...(level:8)
Enabling wanrouter shutdown scripts ...(level:91)
----

[source,shell]
----
[...]
Installing Sangoma Media Gateway Daemon...

Installing SMG Daemon...

Warning: asterisk is running
Would you like to stop asterisk? (y/n) y
----

[source,shell]
----

Checking Syslog ....
 found /etc/rsyslog.conf 
Stopping enhanced syslogd: rsyslogd.
Starting enhanced syslogd: rsyslogd.
Stopping enhanced syslogd: rsyslogd.
Starting enhanced syslogd: rsyslogd.
Ok

Checking logrotate ...
Error: Logrotate dir: /etc/logrotate.d not found !
OK.

Checking for SCTP Utilities....
OK.

Checking for SCTP modules...
OK.

Compiling Sangoma MGD ...
[...]
install -D -m 755 sangoma_mgd /usr/sbin/sangoma_mgd
BRI control scripts installed
install -D -m 755 ../sangoma_bri/smg_ctrl /usr/sbin/smg_ctrl
sangoma_mgd Installed
Ok.
Compiling Woomera Channel ...
[...]
install -D -m 755 chan_woomera.so /usr/lib/asterisk/modules/chan_woomera.so
chan_woomera Installed
Ok.
---------------------------------

 SMG Install Done

--> Config: /etc/sangoma_mgd.conf
--> Start:  sangoma_mgd -bg

 Chan Woomera Install Done

--> Config: /etc/asterisk/woomera.conf
--> Start: start asterisk (part of asterisk)

---------------------------------

Installing SMG BRI Daemon...

----------------------------------------
Sangoma BRI Installation Complete

 -> To configure for BRI run:
 -> /usr/bin/wancfg_smg

----------------------------------------
----

[source,shell]
----

Append sample config in Asterisk Extensions and Iax Conf (y/n) y
----

[source,shell]
----
cat: ./conf_bri/woomera_ext.conf: Datei oder Verzeichnis nicht gefunden
Asterisk extensions.conf file updated with woomera config
cat: ./conf_bri/woomera_iax.conf: Datei oder Verzeichnis nicht gefunden
Asterisk iax.conf file updated with bri guest config
Press [Enter] to continue... enter
----

[source,shell]
----
[...]

WANPIPE INSTALLATON: COMPLETE
        
WANPIPE installation is now complete. WANPIPE kernel drivers 
and configuration/debug utilities have been compiled and installed.

        1) Proceed to configure the WANPIPE drivers:
                Asterisk/Zaptel: /usr/sbin/wancfg_zaptel
                TDM API        : /usr/sbin/wancfg_tdmapi
                SMG SS7/BRI    : /usr/sbin/wancfg_smg
                WAN Routing/API: /usr/sbin/wancfg
        2) Use the /usr/sbin/wanrouter startup scrip to start and stop
           the router. (eg: wanrouter start)
        3) To uninstall WANPIPE package run ./Setup remove
                
Please read http://wiki.sangoma.com for further instructions.
----

[source,shell]
----

Wanpipe / SMG BRI Configuration
===============================

wancfg_smg configurator can create all wanpipe devices
for BRI as well as BRI config file and Asterisk config files.
-----------------------------------------------------
Would you like to configure wanpipe devices for SMG BRI/Asterisk/CallWeaver? (y/n) y
----

[source,shell]
----
[...]

Generating configuration files for Sangoma Media Gateway
[...]
------------------------------------
Configuring ISDN BRI cards [A500]
------------------------------------
----

Jetzt geht es um die Konfiguration der BRI-Ports. Zur Erinnerung:
„Point to multipoint“ bedeutet Mehrgeräteanschluss, also
„normales“ ISDN, und „Point to point“ steht für
den Anlagenanschluss:

[source,shell]
----
-----------------------------------------------------------
A500 detected on slot:8 bus:0
-----------------------------------------------------------

Would you like to configure AFT-A500 port 1 on slot:8 bus:0
 1. YES
 2. NO
 3. Exit
[1-3]: 1
----

[source,shell]
----

Configuring port 1 on AFT-A500 [slot:8 bus:0 span:1]

Select connection type for port 1
 1. Point to multipoint
 2. Point to point
[1-2, ENTER='Point to multipoint']: 1
----

[source,shell]
----

Input the group for this port
: 1
----

[source,shell]
----

Select dialplan context for group:1
 1. from-pstn
 2. Custom
[1-2]: 1
----

[source,shell]
----

Configuring span:1 as TEI:127
 1. YES - Keep this setting
 2. NO  - Specify a different TEI
[1-2, ENTER='YES']: enter
----

Das Gleiche machen wir noch einmal für Port 2, 3, 4, 5 und 6 (je
nachdem, wie viele Module wir eingesteckt haben):

[source,shell]
----
[...]

Would you like to configure AFT-A500 port 2 on slot:8 bus:0
 1. YES
 2. NO
 3. Exit
[1-3, ENTER='YES']: enter
----

[source,shell]
----

Configuring port 2 on AFT-A500 [slot:8 bus:0 span:2]

Select connection type for port 2
 1. Point to multipoint
 2. Point to point
[1-2, ENTER='Point to multipoint']: enter
----

[source,shell]
----

Input the group for this port
def="1": 1
----

[source,shell]
----

Configuring span:2 as TEI:127
 1. YES - Keep this setting
 2. NO  - Specify a different TEI
[1-2, ENTER='YES']: enter
----

[source,shell]
----
[...]

ISBN BRI card configuration complete
----

[source,shell]
----

Press any key to continue: enter
----

[source,shell]
----

Would you like to configure A500 BRI card as timing source for Zaptel?
(Visit http://wiki.sangoma.com/wanpipe-linux-asterisk-appendix#bri-tdmv for more information)
 1. YES
 2. NO
[1-2]:
2
----

[source,shell]
----
[...]

###################################################################
#                             SUMMARY                             #
###################################################################

  0 T1/E1 port(s) detected, 0 configured
  2 ISDN BRI port(s) detected, 2 configured
  0 analog card(s) detected, 0 configured

Configurator will create the following files:
        1. Wanpipe config files in /etc/wanpipe
        2. sangoma_brid config file /etc/wanpipe/smg_bri
        3. Zapata config file /etc/asterisk/zapata.conf

Your original configuration files will be saved to:

Your configuration has been saved in /etc/wanpipe/debug-2009-02-23.tgz.
When requesting support, email this file to techdesk@sangoma.com

###################################################################

Configuration Complete! Please select following:
 1. YES - Continue
 2. NO - Exit
[1-2]: 1
----

[source,shell]
----

Zaptel and Wanpipe configuration complete: choose action
 1. Save cfg: Restart Asterisk & Wanpipe now
 2. Save cfg: Restart Asterisk & Wanpipe when convenient
 3. Save cfg: Stop Asterisk & Wanpipe now
 4. Save cfg: Stop Asterisk & Wanpipe when convenient
 5. Do not save cfg: Exit
[1-5]: 1
----

[source,shell]
----
[...]

Would you like to continue?
 1. No - exit
 2. YES
[1-2, ENTER='No']: 2
----

[source,shell]
----
[...]

Wanrouter start complete...
Current boot level is 2

Wanrouter boot scripts configuration...

Removing existing wanrouter boot scripts...OK
Would you like wanrouter to start on system boot?
 1. YES
 2. NO
[1-2]: 1
----

[source,shell]
----

Verifying Zaptel boot scripts...Enabled (level:15)
Verifying Zaptel shutdown scripts...Enabled (level:30)
Enabling wanrouter boot scripts ...(level:14)
Enabling wanrouter shutdown scripts ...(level:29)
Verifying Network boot scripts...Not installed
Would you like smg_ctrl to start/stop on wanrouter start?
 1. YES
 2. NO
[1-2]: 1
----

[source,shell]
----

smgbri start scrtip installed scuessfully
smgbri stop script installed successfully
Sangoma cards configuration complete, exiting...
----

[[a500-runlevel]]
== Runlevel

Im Default-Runlevel 2 sollten jetzt folgende Einträge
stehen:

[source,shell]
----
debian:/usr/src/wanpipe-3.6.0# ls -l /etc/rc2.d/
[...]
lrwxrwxrwx 1 root root  19 10. Jan 12:00 S14wanrouter -> ../init.d/wanrouter
lrwxrwxrwx 1 root root  16 10. Jan 12:00 S15zaptel -> ../init.d/zaptel
lrwxrwxrwx 1 root root  18 10. Jan 12:00 S16smg_ctrl -> ../init.d/smg_ctrl
[...]
lrwxrwxrwx 1 root root  18 10. Jan 12:00 S50asterisk -> ../init.d/asterisk
----

Wichtig
sind dabei nicht die genauen Nummern, sondern die
_Reihenfolge_ beim Hochfahren:
`wanrouter`, `zaptel`,
`smg_ctrl`, `asterisk`.

Falls dies nicht der Fall ist oder Sie andere Runlevel bevorzugen,
können Sie diese folgendermaßen einrichten:

[source,shell]
----
debian:/usr/src/wanpipe-3.6.0# update-rc.d -f smg_ctrl remove
debian:/usr/src/wanpipe-3.6.0# update-rc.d smg_ctrl defaults 16 20
----

[[sangoma-a500-konfiguration]]
== Konfiguration für die A500

Das `Setup`-Skript hat die Konfiguration für die
Sangoma A500 bereits für uns angelegt. Daher soll die Konfigurationsdatei
hier nur der Vollständigkeit halber erwähnt werden. Wenn man im Setup
alles richtig eingegeben hat, muss man nichts verändern. Sollte man die
Konfiguration der Ports erneut vornehmen wollen, kann man später
+`setup-sangoma`+ aufrufen.

[[sangoma-a500-konfiguration-wanpipe]]
=== Wanpipe

Die Wanpipe-Konfiguration befindet sich im Verzeichnis
`/etc/wanpipe/`. Darin gibt es mehrere Dateien
+wanpipe_`X`_.conf+, wobei
+_`X`_+ für die Nummer des Ports
steht. 1 bis 6 sind die BRI-Ports.

[[sangoma-a500-konfiguration-smg]]
=== Sangoma Media Gateway (SMG)/Woomera

An der Datei `/etc/sangoma_mgd.conf` müssen wir
nichts ändern. Auch die `/etc/wanpipe/smg_bri.conf`
kann fast so bleiben, wie sie ist. Für eine detaillierte Beschreibung
der Parameter siehe http://wiki.sangoma.com/BriAdvancedOptions.
Das einzige, was wir hier ändern. ist:

[source]
----
national_prefix=0
international_prefix=00
----

[[sangoma-a500-konfiguration-asterisk]]
=== Asterisk

Im Folgenden sehen Sie die Einstellungen in der
Asterisk-Konfiguration für die Sangoma A500.

[[a500-asterisk-woomera]]
==== woomera.conf für die A500

Auch die Konfiguration der BRI-Kanäle in der
`/etc/asterisk/woomera.conf` für
`chan_woomera` ist fertig:

[source]
----
[settings]
debug=2

[default]
host=localhost
port=42420
audio_ip=127.0.0.1
default_context=sangoma
debug=2
dtmf_enable=1
jb_enable=0
progress_enable=0

context=from-pstn
group=1
----

[[a500-asterisk-extensions]]
==== extensions.conf für die A500

Nun erzeugen wir noch die
`/etc/asterisk/extensions.conf`:

[source]
----
; Context(e) für Anrufe die von den BRI-Ports der A500
; eingehen. Der Name entspricht dem/den in der
; /etc/asterisk/woomera.conf eingestellten Context(en).

[from-pstn]

exten => _X.,1,Verbose(1,### Eingehender Anruf von ${CALLERID(num)} an ${EXTEN})
exten => _X.,n,Ringing()
exten => _X.,n,Wait(8)
exten => _X.,n,Answer()
exten => _X.,n,Playback(demo-congrats)
exten => _X.,n,Hangup()

exten => 123456,1,Verbose(1,### Eingehender Anruf von ${CALLERID(num)} an ${EXTEN})
exten => 123456,n,Dial(SIP/10)
exten => 123456,n,Hangup()

; Context(e) für Anrufe von intern, also z. B. von einem SIP-Endgerät in Richtung Festnetz über die Sangoma-Karte
[from-internal]

exten => _X.,1,Verbose(1,### Anruf von intern an ${EXTEN})
exten => _X.,n,Dial(WOOMERA/g1/${EXTEN})  ; Gruppe 1
exten => _X.,n,Hangup()
----

[[wanpipe-wanrouter-befehle-sangoma-a500]]
== Wichtige Befehle für Wanpipe

Folgende Befehle sind beim Arbeiten mit Wanpipe/Wanrouter nützlich
und zeigen Informationen über die verbaute A500-Karte an.

+`wanrouter version`+ oder
+`/etc/init.d/wanrouter version`+ zeigt
die installierte Version von Wanpipe:

[source,shell]
----
debian:~# wanrouter version

WANPIPE Release: 3.3.15
----

+`wanrouter summary`+ oder
+`/etc/init.d/wanrouter summary`+ zeigt
eine Übersicht über die Konfigurationsdateien
+/etc/wanpipe/wanpipe_`*`_.conf+footnote:[Die Ausgabe wurde hier etwas in der Breite gekürzt.]:

[source,shell]
----
debian:~# wanrouter summary

Configuration File Summary in : /etc/wanpipe/

Device          Protocol        Type   Cpu/Io Slot/Irq  Bus     State
------------------------------------------------------------------------
wanpipe1        WAN_AFT_ISDN_BRI        PCI     A       8       0       Connected
wanpipe2        WAN_AFT_ISDN_BRI        PCI     A       8       0       Connected
----

+`wanrouter status`+ oder
+`/etc/init.d/wanrouter status`+ zeigt
den Status aller _aktiven_ Portsfootnote:[Die Ausgabe wurde hier etwas in der Breite gekürzt.]:

[source,shell]
----
debian:~# wanrouter status

Devices currently active:
        wanpipe1 wanpipe2

Wanpipe Config:

Device name | Protocol Map | Adapter  | IRQ | Slot/IO | If's | CLK | Baud rate |
wanpipe1    | N/A          | A500     | 17  | 8       | 1    | N/A | 0         |
wanpipe2    | N/A          | A500     | 17  | 8       | 1    | N/A | 0         |

Wanrouter Status:

Device name | Protocol | Station | Status        |
wanpipe1    | AFT ISDN | N/A     | Connected     |
wanpipe2    | AFT ISDN | N/A     | Connected     |
----

+`wanrouter hwprobe`+ oder
+`/etc/init.d/wanrouter hwprobe`+ zeigt
Informationen über die installierte Wanpipe-Hardware an:

[source,shell]
----
debian:~# wanrouter hwprobe

-------------------------------
| Wanpipe Hardware Probe Info |
-------------------------------
1 . AFT-A500-SH : SLOT=8 : BUS=0 : IRQ=17 : PORT=1 : HWEC=64 : V=32
2 . AFT-A500-SH : SLOT=8 : BUS=0 : IRQ=17 : PORT=2 : HWEC=64 : V=32

Card Cnt: A500=1 
----

+`wanrouter hwprobe verbose`+
funktioniert wie +`wanrouter hwprobe`+,
zeigt aber noch zusätzliche Informationen wie den TE/NT-Modus an:

[source,shell]
----
debian:~# wanrouter hwprobe verbose

-----------------------------------------
| Wanpipe Hardware Probe Info (verbose) |
-----------------------------------------
1 . AFT-A500-SH : SLOT=8 : BUS=0 : IRQ=17 : PORT=1 : HWEC=64 : V=32
+01:TE: PCI:C01
2 . AFT-A500-SH : SLOT=8 : BUS=0 : IRQ=17 : PORT=2 : HWEC=64 : V=32
+02:TE: PCI:C01

Card Cnt: A500=1
 
----

Und dann gibt es natürlich die ganz normalen Befehle
+`/etc/init.d/wanrouter`{`start`|`stop`|`restart`}+
wie bei jedem Skript in `/etc/init.d/` zum Starten bzw.
Stoppen des Dienstes.

Durch den Aufruf von +`wanrouter`+
ohne weitere Optionen erhalten Sie eine Liste aller möglichen
Befehle.

Mit +`wanpipemon -g`+ bekommen Sie
ein grafisches Menü zur Analyse der Wanpipe-Ports.

Mittels +`cat /proc/interrupts`+
können Sie prüfen, ob sich die Karte PCI-Interrupts mit anderen Geräten
(Festplatte, Netzwerkkarte, ...) teilen muss.

[source,shell]
----
debian:~# cat /proc/interrupts 
[...]
  17:     123533   IO-APIC-fasteoi   wanpipe1, wanpipe2
----

Experten finden weitere Status-Informationen in speziellen Dateien
im Verzeichnis `/proc/net/wanrouter/`.
