[[voicemail-dial-by-name]]
= Telefonbuch (Dial-by-Name)
:description: Dial-by-Name in Asterisk: Ein Telefonbuch aus den Voicemail-Einträgen generieren.

Auch wenn es eigentlich nicht unmittelbar mit der
VoiceMail-Funktion von Asterisk zu tun hat, gehört das
Dial-by-Name-Directoryfootnote:[Anstelle des deutschen Wortes _Verzeichnis_ verwenden wir der Einfachheit halber das englische Wort _Directory_.] sinngemäß in dieses Kapitel. Es wurde von den
Asterisk-Entwicklern als Teil des Voicemail-Systems programmiert und
greift auf Daten der Datei `voicemail.conf`
zu.

Wenn wir für das Beispiel in xref:voicemail-beispiele.adoc#voicemail-beispiele-meier[„Die Voicemailbox der Familie
Meier“] die folgende Konfiguration zugrunde
legen ...

[source]
----
[general]
format = gsm

[default]
; Ext. => Passw.,Vorname Nachname,E-Mail,P.,Optionen
;                ^^^^^^^^^^^^^^^^
200 => 1234,Horst Meier
201 => 1234,Eva Meier
202 => 1234,Peter Meier,peter@die-familie-meier.de
203 => 1234,Lisa Meier,lisa@die-familie-meier.de,,delete=yes
----

... dann können wir daraus recht einfach ein
Dial-by-Name-Directory generieren. Dies geschieht durch Aufruf des
Programms `Directory()` in der
`extensions.conf`:

[source]
----
exten => 800,1,Directory(default,from-intern)
----

[[voicemail-telefonbuch-syntax]]
== Syntax

[source]
----
Directory(vm-context[,dial-context[,options]])
----

`vm-context`:: Das Directory wird immer aus einem bestimmten Context generiert (alle Einträge aus diesem und nur diesem Context werden zur Auswahl gestellt). In den meisten Fällen kann man den `default`-Context nehmen. In großen Firmen kann man für bestimmte Abteilungen eigene Contexte definieren und somit Unter-Directories erstellen.
`dial-context`:: Das Directory wird benutzt, um eine bestimmte Person anzurufen. Entsprechend muss auch ein Context definiert werden, aus dem (in der `extensions.conf`) der Anruf geführt werden soll. Ist +_`dial-context`_+ nicht definiert, wird automatisch der Context von +_`vm-context`_+ benutzt.
+
Drückt der User des Systems die Taste `0`
(Null), so wird er in diesem Context auf die Extension
`o` (kleiner Buchstabe o) geleitet. Bei Eingabe des
`*` (Stern) wird er zur Extension `a`
(kleiner Buchstabe a) geleitet.
`options`:: Mit der Option `f` kann man das Directory so einstellen, dass nach Vornamen und nicht nach Nachnamen gesucht wird.

Details zur Applikation `Directory()` finden Sie in der offiziellen
Dokumentation unter https://docs.asterisk.org.

[[voicemail-telefonbuch-funktion]]
== Funktionsweise

Der Anrufer wird vom Directory aufgefordert, die ersten drei
Buchstaben des Nachnamens (beim Aufruf mit der Option `f`
sind es Buchstaben des Vornamens) mit dem Tastenfeld des Telefons
einzugeben. Das Programm sucht dann den entsprechenden Eintrag aus dem
Directory und verbindet den Anrufer auf Wunsch.
