[[warteschleifen]]
= Warteschleifen für Call-Center

In diesem Kapitel:

* xref:warteschleifen-musikextension.adoc[Extension zum Musiktest]
* xref:musiconhold.conf.adoc[`musiconhold.conf`]
* xref:queues.conf.adoc[`queues.conf`]
** xref:queues.conf.adoc#queues.conf-musiconhold[`musiconhold`]
** xref:queues.conf.adoc#queues.conf-announce[`announce`]
** xref:queues.conf.adoc#queues.conf-strategy[`strategy`]
** xref:queues.conf.adoc#queues.conf-servicelevel[`servicelevel`]
** xref:queues.conf.adoc#queues.conf-context[`context`]
** xref:queues.conf.adoc#queues.conf-timeout[`timeout`]
** xref:queues.conf.adoc#queues.conf-retry[`retry`]
** xref:queues.conf.adoc#queues.conf-weight[`weight`]
** xref:queues.conf.adoc#queues.conf-wrapuptime[`wrapuptime`]
** xref:queues.conf.adoc#queues.conf-maxlen[`maxlen`]
** xref:queues.conf.adoc#queues.conf-announce-frequency[`announce-frequency`]
** xref:queues.conf.adoc#queues.conf-announce-holdtime[`announce-holdtime`]
** xref:queues.conf.adoc#queues.conf-announce-round-seconds[`announce-round-seconds`]
** xref:queues.conf.adoc#queues.conf-sprachbausteine[Sprachbausteine]
** xref:queues.conf.adoc#queues.conf-periodic-announce-frequency[`periodic-announce-frequency`]
** xref:queues.conf.adoc#queues.conf-monitor-format[`monitor-format`]
** xref:queues.conf.adoc#queues.conf-monitor-join[`monitor-join`]
** xref:queues.conf.adoc#queues.conf-joinempty[`joinempty`]
** xref:queues.conf.adoc#queues.conf-leavewhenempty[`leavewhenempty`]
** xref:queues.conf.adoc#queues.conf-eventwhencalled[`eventwhencalled`]
** xref:queues.conf.adoc#queues.conf-eventmemberstatus[`eventmemberstatus`]
** xref:queues.conf.adoc#queues.conf-reportholdtime[`reportholdtime`]
** xref:queues.conf.adoc#queues.conf-memberdelay[`memberdelay`]
** xref:queues.conf.adoc#queues.conf-timeoutrestart[`timeoutrestart`]
** xref:queues.conf.adoc#queues.conf-autopause[`autopause`]
** xref:queues.conf.adoc#queues.conf-ringinuse[`ringinuse`]
** xref:queues.conf.adoc#queues.conf-member[`member`]
* xref:agents.conf.adoc[`agents.conf`]
** xref:agents.conf.adoc#agents.conf-autologoff[`autologoff`]
** xref:agents.conf.adoc#agents.conf-ackcall[`ackcall`]
** xref:agents.conf.adoc#agents.conf-endcall[`endcall`]
** xref:agents.conf.adoc#agents.conf-wrapuptime[`wrapuptime`]
** xref:agents.conf.adoc#agents.conf-musiconhold[`musiconhold`]
** xref:agents.conf.adoc#agents.conf-updatecdr[`updatecdr`]
** xref:agents.conf.adoc#agents.conf-recordagentcalls[`recordagentcalls`]
** xref:agents.conf.adoc#agents.conf-recordformat[`recordformat`]
** xref:agents.conf.adoc#agents.conf-createlink[`createlink`]
** xref:agents.conf.adoc#agents.conf-urlprefix[`urlprefix`]
** xref:agents.conf.adoc#agents.conf-savecallsin[`savecallsin`]
** xref:agents.conf.adoc#agents.conf-agent[`agent`]
* xref:warteschleifen-extensions.conf.adoc[`extensions.conf`]
* xref:warteschleifen-log.adoc[Log-Datei]
** xref:warteschleifen-log.adoc#queue-log-mysql[Queue-Log in MySQL importieren]

Warteschleifen sind der Horror vieler Kunden. Trotzdem sind sie in
kaum einer Firma mit einem telefonischen Kunden-Service mehr wegzudenken.
Daher soll hier beschrieben werden, wie man eine Warteschleife anlegt und
welche Einstellungen möglich sind.footnote:[Ein Beispiel-Setup in AEL von Digium wird ab Asterisk 1.4 in `doc/queues-with-callback-members.txt` beschrieben.]

Um Warteschlangen einzurichten, sind insbesondere 4 Dateien
wichtig:

`queues.conf`:: Definiert Warteschlangen.
`agents.conf`:: Definiert „Agenten“, also die Mitarbeiter, die die Anrufe entgegennehmen.
`musiconhold.conf`:: Definiert die Wartemusik.
`extensions.conf`:: Im Dialplan werden Anrufe mit `Queue()`in eine Warteschlange eingereiht und Agenten mit `AgentLogin()` oder `AgentCallbackLogin()` am System registriert.

Eine häufige Ursache für Missverständnisse ist die Verwechslung von
„Queue Members“ mit Anrufern: Mit den Mitgliedern einer
Warteschlange sind immer nur die Agenten, _nicht_ die
Anrufer gemeint.

[TIP]
====
Hier wird der Einfachheit halber der Begriff „Agenten“
verwendet, Markus Bönke macht aber folgende Anmerkung:Sie übersetzen Queue Member mit "Agenten", wenn man aus der
Call-Center-Welt kommt, ist das ein bisschen verwirrend, da Queue
Members durchaus normale SIP-Extensions sein können.
Das ist völlig richtig. Man muss nicht über den
`Agent`-Channel (der wie ein Proxy funktioniert) gehen, sondern
kann auch direkt `SIP`-Geräte zu einer Warteschlange
hinzufügen. Also schreibt man in der `queues.conf` z.
B. `member => SIP/1001`, oder man fügt das Interface
dynamisch aus dem Dialplan mit `AddQueueMember()`footnote:[siehe xref:applications-addqueuemember.adoc[Abschnitt C.2, „`AddQueueMember()`“\]] einer Queue hinzu.
====

Agenten können mehreren Warteschlangen angehören, und wir wollen,
dass sich jeder Agent von einer beliebigen Extension aus einloggen kann
(„Hot-Desking“). Das grundsätzliche Vorgehen zur Definition von
Agenten und Warteschlangen sieht vereinfacht so aus:

*`agents.conf`*

[source]
----
[agents]
;    AgentenNr,Passwort,Name
agent => 1001,1234,Mark Spencer
agent => 1002,1234,Will Meadows
----

*`queues.conf`*

[source]
----
[support-schlange]
member => Agent/1001   ; Agent 1001 zur support-schlange hinzufügen
member => Agent/1002   ;   ... 1002 ...
----

*`extensions.conf`*

[source]
----
exten => 20,1,Queue(support-schlange)   ; => Warteschlange
exten => 25,1,AgentLogin()              ; bei Anruf Login
----

Und so funktioniert es: Die Agenten loggen sich über Extension
`25` ein, hören fröhliche Musik und warten auf Anrufer. Anrufe
auf Extension `20` werden in die Schlange aufgenommen und der
Reihe nach (FIFO) abgearbeitet: Der Agent hört einen Piepton, und der erste
Anrufer wird verbunden.
