[[zaptel-to-dahdi-aenderungen]]
= DAHDI

=== Dial()

Wer in Asterisk 1.6 oder ab Asterisk 1.4.22 DAHDI einsetzen will
(bzw. muss), sei darauf hingewiesen, dass sich im Dialplan
+Dial(Zap/_`...`_)+ in
+Dial(DAHDI/_`...`_)+ ändert.

Allerdings kann man aus Gründen der Rückwärtskompatibilität falls
gewünscht in der `/etc/asterisk/asterisk.conf`
mit

[source]
----
dahdichanname = no
----

im Abschnitt
`[options]` einstellen, dass die Kanäle wie vorher mit Zaptel
`Zap` statt `DAHDI` heißen.

=== Kernel-Module (.ko)

[cols="2*"]
|===
| Zaptel | Dahdi

| `zaptel` | `dahdi`
| `ztd-eth` | `dahdi_dynamic_eth`
| `ztd-loc` | `dahdi_dynamic_loc`
| `ztdummy` | `dahdi_dummy`
| `ztdynamic` | `dahdi_dynamic`
| `zttranscode` | `dahdi_transcode`
|===

Die Kernel-Module der einzelnen Kartentreiber heißen wie
bisher.

=== Dateien

[cols="2*"]
|===
| Zaptel | Dahdi

| `/etc/zaptel.conf` | `/etc/dahdi/system.conf`
| `/etc/asterisk/zapata.conf` | `/etc/asterisk/chan_dahdi.conf`
|===

Mit `dahdichanname = no` (s. o.) liest Asterisk die
Konfiguration aus der `zapata.conf` statt aus der
`chan_dahdi.conf`.

=== Shell-Programme

[cols="2*"]
|===
| Zaptel | Dahdi

| `ztcfg` | `dahdi_cfg`
| `ztmonitor` | `dahdi_monitor`
| `ztscan` | `dahdi_scan`
| `ztspeed` | `dahdi_speed`
| `zttest` | `dahdi_test`
| `zttool` | `dahdi_tool`
| `zapconf` | `dahdi_genconf`
|===

=== Asterisk-Module

[cols="2*"]
|===
| Zaptel | Dahdi

| `chan_zap.so` | `chan_dahdi.so`
| `app_zapbarge.so` | `app_dahdibarge.so`
| `app_zapras.so` | `app_dahdiras.so`
| `app_zapscan.so` | `app_dahdiscan.so`
|===

Aus Gründen der Rückwärtskompatibilität können die Applikationen
auch weiterhin als +Zap_`...`_()+ statt
(neu:) +DAHDI_`...`_()+ aufgerufen
werden. Für mehr Informationen zu den Applikationen siehe xref:applications.adoc[Anhang C, _Applikationen im Dialplan_].
