site:
  title: Das Asterisk-Buch
  start_page: book::index.adoc

content:
  sources:
  - url: https://github.com/wintermeyer/asterisk-buch
    branches: main

ui:
  bundle:
    url: https://github.com/wintermeyer/wincon-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true

asciidoc:
  extensions:
  - ./asciidoctor-extensions/terminal-role.js

output:
  dir: ./build/site

runtime:
  fetch: true
